- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hv1_emulator/src/cpuid.rs
- vm/hv1/hvdef/src/lib.rs
- vmm_core/virt_kvm/src/arch/x86_64/mod.rs
Don't update cpuid results in place for VSM support revocation. Just
apply a fixup after the fact, like we do with all the other dynamic
leaves.
> virt_mshv_vtl: don't lock the cpuid results

- openhcl/underhill_core/src/worker.rs
- openhcl/underhill_mem/src/init.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
This removes some more unwraps and error paths, as well as making things easier to follow IMO.
> virt_mshv_vtl & uh_mem: Refactor cvm-only memory structs to be in cvm-only locations

- openhcl/virt_mshv_vtl/src/cvm_cpuid/mod.rs
XSAVE size and alignment calculation requires enumerating subleafs in ascending order. Previously, using a hashmap means that iteration order is not stable, so switch it to a BTreeMap. 
#708
> virt_mshv_vtl: use BTreeMap for cvm cpuid subleafs

- vm/devices/net/net_mana/src/lib.rs
net_mana has a hardware limit of on the number of segments (either 31 or 30).
Any packet with fewer than 31 segments, net_mana will send correctly.
When a packet has a number of segments greater than 31, openhcl crashes.
Note: netvsp has a max MDL chain length of 34, so for packets with an MDL chain longer than 34, netvsc will bounce buffer, and net_mana will see only 2 segments. This makes the crash rare / difficult to reproduce.
Fixing the problem by:
* Modifying net_mana code to bounce buffer whenever segment count exceeds the hardware limit.
* Adding functionality to ContiguousBufferManager to create logic for transactions and try_extend to support a single bounce buffer that can include either:
* Header's bounced segments + beginning segments of payload.
* The first sequence of the …
> For tx segments exceeding 31, coalesce into bounce buffer

- openvmm/hvlite_core/src/worker/dispatch.rs
- vm/devices/vmbus/vmbus_server/src/lib.rs
- vmm_core/src/partition_unit.rs
- vmm_core/state_unit/src/lib.rs
Simplify the state machine model by not allowing individual units to be stopped or reset.
To support the VTL2 servicing scenario, add a method to the partition unit to stop VPs, and add a method to vmbus to reset outside of the unit state machine.
> state_unit: remove subset stops, force reset

- openhcl/virt_mshv_vtl/src/lib.rs
We have this information available already, we shouldn't have to duplicate it. Although this is slightly less efficient, replacing an atomic load with a RwLock read, I think this path is cold enough that it's fine.
> virt_mshv_vtl: Replace guest_vsm_revoked with reading the BackingShared guest_vsm state

- Cargo.lock
- Cargo.toml
- openhcl/rootfs.config
- openhcl/underhill_core/src/worker.rs
- openhcl/underhill_mem/src/init.rs
- openhcl/underhill_mem/src/lib.rs
- openvmm/openvmm_entry/src/cli_args.rs
- openvmm/openvmm_entry/src/lib.rs
- tmk/simple_tmk/Cargo.toml
- tmk/simple_tmk/build.rs
- tmk/simple_tmk/src/main.rs
- tmk/simple_tmk/src/tmk.rs
- tmk/tmk_protocol/Cargo.toml
- tmk/tmk_protocol/src/lib.rs
- tmk/tmk_vmm/Cargo.toml
- tmk/tmk_vmm/build.rs
- tmk/tmk_vmm/src/host_vmm.rs
- tmk/tmk_vmm/src/load.rs
- tmk/tmk_vmm/src/main.rs
- tmk/tmk_vmm/src/paravisor_vmm.rs
- tmk/tmk_vmm/src/run.rs
- vm/loader/src/lib.rs
- xtask/src/tasks/fmt/house_rules/cfg_target_arch.rs
To make it easier to test core `virt_*` functionality without all the accoutrements of a full-featured VMM (virtual devices, etc.), create a VMM that can just run simple test microkernels (TMKs) and not full guest operating systems.
This VMM can run either on the host or in a paravisor environment.
Current limitations:
* No docs on using this
* No integration with CI test pass
* x86_64 only
* Non-CVM only
* Just define one simple TMK that doesn't test much of anything
Ideally, this will mesh up with the effort to define some rich TMKs for use with full-features VMMs, so that we can run some subset of TMKs in both environments. But even without that, this will be valuable for platform bringup.
> tmk: add simple VMM for running TMKs

- build_support/macos/sign_and_run.sh
- openhcl/minimal_rt/aarch64-config.toml
- openhcl/minimal_rt/aarch64-minimal_rt-none.json
- openhcl/minimal_rt/x86_64-config.toml
- openhcl/minimal_rt_build/src/lib.rs
- tmk/simple_tmk/src/main.rs
- tmk/simple_tmk/src/tmk.rs
- tmk/simple_tmk/src/tmk/aarch64.rs
- tmk/simple_tmk/src/tmk/x86.rs
- tmk/tmk_vmm/Cargo.toml
- tmk/tmk_vmm/src/load.rs
- tmk/tmk_vmm/src/main.rs
- tmk/tmk_vmm/src/run.rs
- vmm_core/virt_hvf/src/vp_state.rs
Add aarch64 support to `tmk_vmm` and `simple_tmk`.
As part of this, I defined a custom target to use when building `simple_tmk` so that it's relatively straightforward to build this on non-Linux platforms. It looks something like:
```
RUSTC_BOOTSTRAP=1 cargo build -p simple_tmk --config openhcl/minimal_rt/aarch64-config.toml
```
On Linux you can still just build with the `aarch64-unknown-linux-musl` target, like we do for `openhcl_boot`, so `RUSTC_BOOTSTRAP=1` remains optional.
> tmk: add aarch64 support

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
Since we no longer support emulating the APIC on hypervisor backings, this can move to be CVM only.
> virt_mshv_vtl: Move hv_start_enable_vtl_vp to CvmVpInner

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Continuing to move things off of PartitionInner. Once all my current PRs are in I think everything that can move off of the PartitionInner will have done so, and I'll start working on removing the getters that were necessary during this transition.
> virt_mshv_vtl: Move the partition-wide untrusted_synic into TdxBackedShared

- openhcl/underhill_core/src/worker.rs
- openhcl/underhill_mem/src/init.rs
We are seeing failures when registering shared memory with the kernel in
TDX configurations. Rather than try to debug this right now , just
prohibit it--this is only used in low-perf paths in practice, and it
introduces extra runtime failure paths that are impossible to recover
from.
> underhill_mem: cvm: don't register shared memory with the kernel

- Cargo.lock
- vmm_tests/vmm_tests/Cargo.toml
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
These tests have a ramdisk-backed NVMe block device translated by OpenHCL into a SCSI DVD device.
> vmm_tests: Add test for NVMe-backed SCSI DVD scenario

- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/x86/x86defs/src/vmx.rs
VP.ENTER can fail if the guest's VMCS is in a bad state. This is a VMM bug, so handle it rather specifically than just lumping it into the generic exit type. Add some additional tracing to capture VMCS fields to help debug issues.
Fix the VMX exit definition to correctly have the upper bits that show different error conditions so we can correctly check if VP.ENTER succeeded.
This is to help track down a current issue that has a very low repro rate where we're seeing this exit code. There's an identified issue with CR4 MCE (#1091), but it's unclear if that is the cause or not yet.
Backport of #1092
> virt_mshv_vtl/tdx: log more info for bad guest state exits (#1092)

- openhcl/hcl/src/ioctl/tdx.rs
- openhcl/sidecar/src/arch/x86_64/init.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/x86/x86defs/src/lib.rs
- vmm_core/virt/src/x86/vp.rs
- vmm_core/virt_support_x86emu/tests/tests/common.rs
Ensure VMCS and shadow register state is consistent at construction
time, and that VP reset state is properly applied before the AP starts.
This fixes an issue where the shadow efer register value was different
from the one on the VMCS, which was exposed by #1095.
> virt_mshv_vtl: tdx: apply more register state at VP init

- openhcl/hcl/src/ioctl.rs
- openhcl/hcl/src/ioctl/aarch64.rs
- openhcl/hcl/src/ioctl/snp.rs
- openhcl/hcl/src/ioctl/tdx.rs
- openhcl/hcl/src/ioctl/x64.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
- vm/hv1/hvdef/src/lib.rs
Save/restore will destroy the registry page contents, so flush them out to other locations on save.
> x64_regs: Flush dirty registry page contents at save

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
The previous logging change https://github.com/microsoft/openvmm/pull/1092 missed logging not just the cached EFER value, but the VMCS efer value.
Backport of #1102.
> virt_mshv_vtl/tdx: log vmcs efer on vm enter failures

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Checking for VINA in every exit is hurting TDX perf due to the read of VMX_VMCS_GUEST_INTERRUPTIBILITY. Tweak cvm_handle_cross_vtl_interrupts so that we don't do anything if VTL 1 isn't yet enabled to avoid this as much as we can. Also tweak the order of operations so this is checked later in the process, allowing earlier easier checks to bail us out. Also, thanks to how we've been moving around state everywhere, flatten out these ifs so things aren't so deeply nested.
> virt_mshv_vtl: Optimize and cleanup cvm_handle_cross_vtl_interrupts

- openhcl/underhill_core/src/livedump.rs
- openhcl/underhill_crash/src/lib.rs
- openhcl/underhill_crash/src/options.rs
- vm/devices/watchdog/watchdog_core/src/lib.rs
Both underhill-dump and underhill-crash will include a copy of kmsg in the final dump, as they weren't originally intended to be used together. Using them together works fine, but it means we have two copies of kmsg in the output. This doesn't cause any problems with reading the dump, it just wastes space. underhill-dump has the easier job here, so fix this by adding yet another option to underhill-crash.
> livedump: Don't include two copies of kmsg

- Cargo.lock
- openhcl/underhill_core/src/emuplat/watchdog.rs
- openhcl/underhill_core/src/lib.rs
- openhcl/underhill_core/src/livedump.rs
- openhcl/underhill_core/src/worker.rs
- openhcl/underhill_crash/Cargo.toml
- openhcl/underhill_crash/src/lib.rs
- openhcl/underhill_crash/src/options.rs
- openhcl/underhill_dump/Cargo.toml
- openhcl/underhill_dump/src/lib.rs
- openvmm/hvlite_entry/src/cli_args.rs
- openvmm/hvlite_entry/src/lib.rs
The aim here is to produce as much information as we can to in debugging these timeouts after-the-fact in prod. This dump should end up in watson whenever these timeouts are hit, which gives us something to investigate besides just "we timed out". This does not yet implement our idea of including inspect output in these dumps, that will be a follow up.
> Record a livedump of OpenHCL when hitting a guest or uefi watchdog timeout (#1093)

- Guide/src/user_guide/openvmm/run.md
Adds a note to the "Obtaining a copy of OpenVMM > Pre-Built Binaries" section, pointing out GitHub's requirement to be signed in in order to download artifacts.
Closes #1072
> guide: note github sign-in requirement to download artifacts

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs
Download all the artifacts a job needs (including flowey, if consuming via artifact) in parallel instead of one at a time, using the `pattern` feature of the `download-artifact` action.
> flowey: download artifacts in parallel

- Guide/src/dev_guide/getting_started/build_openvmm.md
Fix broken links to openvmm.dev in build-openvmm.md
> guide: fix broken links to openvmm.dev

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Add more vmcs, register and private state. 
Tested via adding the trace_processor_state via a different exit.
> virt_mshv_vtl/tdx: even more logging on vm enter failure

- openhcl/openhcl_boot/src/main.rs
Update swiotlb buffer size since the previous 256KB buffer caused IO failures on DVD during TDX Windows VM provisioning. Scope this to hardware isolated CVMs only until we better understand the implications of this change more broadly.
> openhcl_boot: update swiotlb to 8MB on hardware isolated CVMs

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Add more vmcs, register and private state.
Tested via adding the trace_processor_state via a different exit.
Backport of #1110
> virt_mshv_vtl/tdx: even more logging on vm enter failure (#1110)

- openhcl/openhcl_boot/src/main.rs
Update swiotlb buffer size since the previous 256KB buffer caused IO failures on DVD during TDX Windows VM provisioning. Scope this to hardware isolated CVMs only until we better understand the implications of this change more broadly.
Cherry pick of #1116
> openhcl_boot: update swiotlb to 8MB on hardware isolated CVMs (#1116)

- openhcl/underhill_attestation/src/lib.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/vm/openvmm/construct.rs
- petri/src/vm/openvmm/modify.rs
- vm/devices/get/get_resources/src/lib.rs
- vm/devices/get/guest_emulation_device/src/lib.rs
- vm/devices/get/guest_emulation_device/src/resolver.rs
- vm/devices/get/guest_emulation_device/src/test_utilities.rs
- vm/devices/tpm/src/lib.rs
- vm/devices/tpm/src/tpm_helper.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
This PR does the following
- Preserves the AK cert (if TPM seeds are not refreshed) across boots that increases the resiliency in case that the boot-time AK cert request succeeds in the first boot but fails in the subsequent boot.
- Ensure the AK cert index is always re-created with consistent properties (index size, platform-created, write permission per-boot auth value)
> tpm: Preserve AK cert across boots for resiliency

- vm/devices/hyperv_ic_protocol/src/heartbeat.rs
- vm/devices/hyperv_ic_protocol/src/kvp.rs
- vm/devices/hyperv_ic_protocol/src/lib.rs
- vm/devices/hyperv_ic_protocol/src/shutdown.rs
- vm/devices/hyperv_ic_protocol/src/timesync.rs
- vm/devices/hyperv_ic_protocol/src/vss.rs
Add definitions for KVP, timesync, and VSS.
These aren't tested yet. There is probably some extra or missing padding somewhere.
> hyperv_ic_protocol: add more protocol defs

- .config/nextest.toml
- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- Cargo.lock
- flowey/flowey_core/src/pipeline.rs
- flowey/flowey_hvlite/Cargo.toml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_lib_common/src/cache.rs
- flowey/flowey_lib_common/src/download_cargo_nextest.rs
- flowey/flowey_lib_common/src/install_rust.rs
- flowey/flowey_lib_hvlite/src/_jobs/build_and_run_nextest_vmm_tests.rs
- flowey/flowey_lib_hvlite/src/_jobs/consume_and_test_nextest_vmm_tests_archive.rs
- Fixes an issue where a cached item for the wrong platform/architecture could be downloaded. 
- Installs nextest if the cache isn't working, even on jobs that download a pre-built version of flowey (vmm_tests).
- Changes the nextest configuration to only print failure logs at the end to make the logs more readable.
- Refactors the vmm test flowey nodes to allow VHDs/ISOs to be specified by the caller where the test filter is defined, instead of being inferred based on architecture.
> flowey: nextest and rust install fixes

- openhcl/underhill_attestation/src/lib.rs
- openhcl/underhill_attestation/src/secure_key_release.rs
Fix the logic introduced by #1124 --- only return the error of wrapped key response is required when VMGS is encrypted.
> attestation: relax the wrapped key response check when VMGS is not encrypted

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Update build to pull in the most recent openvmm-deps update: https://github.com/microsoft/openvmm-deps/releases/tag/0.1.0-20250403.3.
> Update to latest openvmm-deps release

- openhcl/lower_vtl_permissions_guard/src/lib.rs
- openhcl/openhcl_dma_manager/src/lib.rs
- vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs
- vm/devices/user_driver/src/lib.rs
- vm/devices/user_driver/src/lockmem.rs
- vm/page_pool_alloc/src/lib.rs
Rather than having to call `attach_dma_buffer` for each pending allocation, it would be convenient to just attach them all and get the resulting `MemoryBlock`s. This change adds `attach_pending_buffers` to do that.
> openhcl: attach all pending dma restorations at once instead of handing out one by one

- hyperv/tools/hypestv/src/windows/mod.rs
Don't terminate on ctrl+c and instead just skip the current line.
> hypestv: ignore current line on ctrl+c

- Cargo.lock
- Cargo.toml
- petri/petri-tool/Cargo.toml
- petri/petri-tool/src/main.rs
- petri/src/disk_image.rs
- petri/src/lib.rs
For now, just have a command to build the cloud-init disk image. In the future, this could include commands to interact with running petri tests or even to launch test VMs using petri code.
> petri-tool: add CLI for petri-related functionality

- build_support/windows_cross/cross_tool.py
If a tool isn't present in the cache and the user is trying to invoke
it, rebuild the cache.
This was always the intended behavior.
> windows_cross: don't cache tool absence

- support/mesh/mesh_protobuf/src/encoding.rs
- support/mesh/mesh_protobuf/src/lib.rs
This is useful for sending IP addresses across mesh processes.
> mesh_protobuf: add encoding for Ipv4Addr/Ipv6Addr

- petri/guest-bootstrap/network-config
We specify a networking configuration to work around a cloud-init bug. Make sure this networking configuration initializes the NIC configured for the VM when one is present.
> petri: cloud-init: configure eth0 when present

- openhcl/underhill_core/src/worker.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/mod.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/mod.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/topology.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/xfem.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/vm_topology/src/processor/x86.rs
- vmm_core/virt/src/cpuid.rs
- vmm_core/virt/src/x86/mod.rs
- vmm_core/virt_kvm/src/arch/x86_64/mod.rs
Move the cvm_cpuid fixups (e.g., per-VP topology changes and
xfem-dependent xsave fields) out into the CVM partition code, so that
cvm_cpuid is only responsible for static data.
Use data from `X86PartitionCapabilities` to compute the xsave sizes
rather than recompute them from the cpuid data.
Use data from `ProcessorTopology` to compute the AMD topology leaf at
runtime.
Fix AMD processor topology computation.
Incorporate cvm_cpuid static data into the existing `CpuidLeafSet`
structure for looking up cpuid results.
Future changes should further simplify `cvm_cpuid`, but at least it is
no longer a separate thing at runtime.
> virt_mshv_vtl: refactor cvm_cpuid

- vmm_tests/vmm_tests/tests/tests/multiarch.rs
In some environments, we are seeing multiple IP addresses from VMs in the `kvp_ic` test. Log the full IP information in order to be able to diagnose this.
> vmm_tests: log KVP IP information

- Cargo.lock
- Cargo.toml
Update openssl to 0.10.72 to remove the dependabot flagged issue. We don't use the methods that had the use-after-free, so there's not a security issue for us.
> deps: update openssl to 0.10.72

- vmm_tests/vmm_tests/tests/tests/multiarch.rs
Windows seems to bind to a link-local IP for a bit sometimes. In the
`kvp_ic` test, filter out such IPs when verifying the IP address
information returned by the guest.
> vmm_tests: filter link-local IPs in KVP IC test

- vm/x86/tdcall/src/lib.rs
Turns out that's not how bitmasks work
> Tdcall: Fix page attr mask debug validation

- openhcl/virt_mshv_vtl/src/lib.rs
- vm/devices/net/netvsp/src/lib.rs
- vm/devices/vmbus/vmbus_channel/src/bus.rs
- vm/devices/vmbus/vmbus_client/src/lib.rs
- vm/devices/vmbus/vmbus_core/src/lib.rs
- vm/devices/vmbus/vmbus_relay/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/channels.rs
- vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs
- vm/devices/vmbus/vmbus_server/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
- vm/vmcore/src/monitor.rs
- vm/vmcore/src/synic.rs
- vmm_core/src/synic.rs
- vmm_core/virt/src/generic.rs
- vmm_core/virt_hvf/src/lib.rs
- vmm_core/virt_kvm/src/arch/aarch64/mod.rs
- vmm_core/virt_kvm/src/arch/x86_64/mod.rs
- vmm_core/virt_mshv/src/lib.rs
- vmm_core/virt_whp/src/synic.rs
This change updates vmbus_server's support for monitored interrupts.
- The `SynicPortAccess` trait is updated to provide information about monitor usage during host and guest event port creation. When creating guest event ports, initial parameters for their creation must be supplied.
- The `MonitorPortAccess` trait is updated to require the VTL that a monitor page is for.
- The VmBus server delays creation of guest event ports until the channel is opened, at which point all the information needed to create it with initial parameters is known.
- Monitored interrupt latency is passed along for vmbusproxy channels, and provided by internal channels using MnF (this is not used by openvmm's implementation of MnF, since it is emulated, but can be used by other implementations).
> vmbus_server: improve MnF support

- Cargo.lock
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- vm/hv1/hv1_emulator/Cargo.toml
- vm/hv1/hv1_emulator/src/hv.rs
- vm/hv1/hv1_emulator/src/lib.rs
- vm/hv1/hv1_emulator/src/locked_page.rs
- vm/hv1/hvdef/src/lib.rs
By locking the pages we are configured for we can guarantee there will be no errors reading or writing to the page. This makes the code shorter and easier to read.
If we like this approach I'll keep going with the rest of hv1_emulator, just wanted to get this out for initial impressions.
> hv1_emulator: Lock overlay pages

- vmm_tests/vmm_tests/tests/tests/multiarch.rs
This test is unreliable since the shutdown IC isn't always ready when it says it is.
> ci: disable ubuntu no agent hyper-v test

- petri/src/vm/hyperv/mod.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/mod.rs
- petri/src/vm/openvmm/modify.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
Builds on https://github.com/microsoft/openvmm/commit/b96460a7dbcb510bda1499868213ad02e348f8c1 to allow the number of VPs to be configured for a Hyper-V or generic VMM test. Adds a single proc vbs/tdx test for hyper-v as an example.
> petri: configurable processor count for hyper-v

- vm/devices/vmbus/vmbus_channel/src/channel.rs
- vm/devices/vmbus/vmbus_server/src/lib.rs
During stop, the vmbus channels are stopped before the vmbus server, which leaves a small window where a vmbus request from the guest can arrive after the channel is stopped. Handle this by pending the message in the vmbus channel code. These pended messages do not need to be saved, because vmbus_server will replay them on restore. The maximum number of pended requests should be two per channel_idx, for the case of a pended modify request followed by a pended close. Any other combination should be rejected by vmbus as the device will not be in a valid state.
> vmbus_channel: Stopped vmbus devices should not see vmbus requests.

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This lets Guest VSM boot get even farther.
> TDX: Read and write CR8 in AccessVpState

- vm/devices/vmbus/vmbus_server/src/lib.rs
Most of these values can just be default anyway.
> vmbus, test: fix break caused by struct change

- vm/devices/vmbus/vmbus_client/src/lib.rs
- vm/devices/vmbus/vmbus_client/src/saved_state.rs
If there are active GPADL or modify channel requests when the host revokes a channel, it will still send responses for those requests. This is different from channel open, for which the host will only send a response if the channel has not yet been revoked.
`vmbus_client` was not handling this properly, so it would release the channel ID after receiving a revoke and before the GPADL responses arrived. This would cause panics when the request responses eventually arrived.
Fix this by tracking the state more carefully and only releasing the channel once all active requests have been completed by the host. Wait for such requests during pause so that we do not have to save channels in a revoked-with-requests-outstanding state.
Also, fix a theoretical deadlock in the pause path. And now that …
> vmbus_client: fix handling of revoked channels with active requests

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- openhcl/virt_mshv_vtl/src/processor/vp_state.rs
Removes some "BUGBUG" messages and overall cleans up this code.
> TDX: Cleanup some error handling around efer/cr0/cr4

- petri/src/vm/hyperv/powershell.rs
- petri/src/vm/hyperv/vm.rs
Since our tests do not currently use the default network adapter, remove it. This helps speed up Ubuntu tests on Hyper-V, since Ubuntu waits for a network connection if a NIC is present.
(pulled from @chris-oo's change in this wip PR: https://github.com/microsoft/openvmm/pull/1187)
> petri: remove default vm network adapter on hyper-v

- openhcl/underhill_core/src/lib.rs
- openhcl/underhill_core/src/loader/mod.rs
- openhcl/underhill_core/src/options.rs
- openhcl/underhill_core/src/worker.rs
Add the ability to do this via an environment variable. While the device platform settings also specify this setting, not all hosts (such as Hyper-V) support configuring this setting in all scenarios.
This is to be used in an upcoming petri change to match the correct expected behavior for petri vm configuration.
> openhcl: add cmdline option to disable uefi frontpage

- openhcl/underhill_core/src/loader/mod.rs
- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- openvmm/hvlite_core/src/worker/vm_loaders/uefi.rs
- openvmm/hvlite_defs/src/config.rs
- openvmm/openvmm_entry/src/cli_args.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/vm/openvmm/construct.rs
- vm/devices/get/get_protocol/src/dps_json.rs
- vm/devices/get/get_resources/src/lib.rs
- vm/devices/get/guest_emulation_device/src/lib.rs
- vm/devices/get/guest_emulation_device/src/resolver.rs
- vm/devices/get/guest_emulation_device/src/test_utilities.rs
- vm/devices/get/guest_emulation_transport/src/api.rs
- vm/devices/get/guest_emulation_transport/src/client.rs
Plumbs UEFI's DefaultBootAlwaysAttempt setting through DevicePlatformSettingsV2 on OpenHCL and to the OpenVMM CLI. This allows a VM with persistent VMGS to recover when the boot disk in replaced or modified in a way that would invalid the existing boot entries.
> uefi: make default_boot_always_attempt configurable

- openhcl/virt_mshv_vtl/src/cvm_cpuid/mod.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
Addresses Issue #556. 
Added missing validation for CPUID leaf 0xB.
Maximum xfd calculation could have been used by MSRs 0x1C4 (MSR_XFD) and 0x1C5 (MSR_XFD_ERR). However, the L1 doesn't get any intercept for these MSRs. Hence, removed the related redundant code.
> Adding validation for CPUID leaves

- openhcl/hcl/src/ioctl.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hvdef/src/lib.rs
- vm/x86/x86defs/src/snp.rs
- vmm_core/virt_support_apic/src/lib.rs
- vmm_core/virt_whp/src/apic.rs
Support for VTL 1 to register for write intercepts on certain registers.
Tested:
- SNP + Guest VSM boots no debugger
- SNP boots
> snp guest vsm: register intercepts

- flowey/flowey_lib_hvlite/src/init_cross_build.rs
- flowey/flowey_lib_hvlite/src/run_split_debug_info.rs
For the linker, that's x86_64 though. Flowey code assumes everyone does the same, but at least Fedora doesn't, and Fedora uses x86_64 for both gcc and binutils.
> flowey: Ubuntu uses x86-64 for gcc and binutils packages

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This fixes a bug where we weren't disabling the virtual_interrupt_delivery bit for VTL 1, and also removes the potentially error prone approach of caching all of secondary_processor_controls. Also cleans up some diagnostic tracing.
> TDX: Clean up apic offload setting and remove secondary controls caching

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
The first PR of what will likely be many for TDX VTL 1 intercepts. This fully hooks up CR0, CR4, XCR0/XFEM, and hooks up the handling of MSRs. The remaining items that need work are descriptor table intercept registration and handling, and updating the MSR bitmap registration.
> Begin wiring up TDX intercepts, update CR intercepts

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- Cargo.lock
- Cargo.toml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_lib_common/src/install_rust.rs
- flowey/flowey_lib_common/src/run_cargo_build.rs
- flowey/flowey_lib_hvlite/src/_jobs/build_and_run_nextest_vmm_tests.rs
- flowey/flowey_lib_hvlite/src/_jobs/consume_and_test_nextest_vmm_tests_archive.rs
- flowey/flowey_lib_hvlite/src/build_tmk_vmm.rs
- flowey/flowey_lib_hvlite/src/build_tmks.rs
- flowey/flowey_lib_hvlite/src/init_vmm_tests_env.rs
- flowey/flowey_lib_hvlite/src/lib.rs
- flowey/flowey_lib_hvlite/src/run_cargo_build.rs
- petri/src/disk_image.rs
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/openvmm/construct.rs
- petri/src/vm/openvmm/modify.rs
- tmk/tmk_tests/Cargo.toml
- tmk/tmk_tests/build.rs
- tmk/tmk_tests/src/lib.rs
- tmk/tmk_vmm/Cargo.toml
- tmk/tmk_vmm/src/main.rs
- vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs
- vmm_tests/petri_artifacts_vmm_test/src/lib.rs
- vmm_tests/vmm_tests/Cargo.toml
- vmm_tests/vmm_tests/tests/tmks.rs
Enable the TMKs to run in CI. Run them both in host VMM mode and in paravisor mode.
> tmk: run in CI as part of vmm tests

- petri/src/vm/hyperv/hyperv.psm1
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/hyperv/powershell.rs
- petri/src/vm/hyperv/vm.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/construct.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
Make the no boot device uefi test now work on Hyper-V. This requires setting all VMs to not enable the UEFI frontpage (which matches openvmm behavior) via configuring this thru an OpenHCL environment override.
> petri/hyperv: onboard uefi no boot device test

- openhcl/underhill_core/src/lib.rs
- openhcl/underhill_core/src/options.rs
Add a new option, `OPENHCL_SIGNAL_VTL0_STARTED`, for signaling the host that VTL0 is ready very early in paravisor start. This is useful when you don't want a Hyper-V host to wait for VTL0 to start (e.g., because it will never start or will delayed indefinitely via `OPENHCL_WAIT_FOR_START`).
> underhill_core: add OPENHCL_SIGNAL_VTL0_STARTED option

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_lib_hvlite/src/_jobs/build_and_run_nextest_vmm_tests.rs
- flowey/flowey_lib_hvlite/src/_jobs/consume_and_test_nextest_vmm_tests_archive.rs
- flowey/flowey_lib_hvlite/src/download_openvmm_vmm_tests_artifacts.rs
- flowey/flowey_lib_hvlite/src/lib.rs
- vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs
- vmm_tests/vmm_test_images/src/lib.rs
- xtask/src/tasks/guest_test/download_image.rs
Since flowey does not care whether an artifact is a VHD, ISO, or something else, we can make this more loosely typed and simplify the code. This also allows us to add different types of artifacts that have different characteristics (like VMGS). The type information is still enforced in the `petri_artifacts_vmm_test` crate.
> flowey: use KnownTestArtifacts instead of KnownVhds and KnownIsos

- openhcl/hcl/src/ioctl.rs
- openhcl/hcl/src/ioctl/aarch64.rs
- openhcl/hcl/src/ioctl/snp.rs
- openhcl/hcl/src/ioctl/tdx.rs
- openhcl/hcl/src/ioctl/x64.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- vm/hv1/hvdef/src/lib.rs
Port of #1077
Save/restore will destroy the registry page contents, so flush them out to other locations on save.
---------
> 2411: x64_regs: Flush dirty registry page contents at save.

- vm/devices/vmbus/vmbus_channel/src/channel.rs
- vm/devices/vmbus/vmbus_server/src/lib.rs
Port of #1128
During stop, the vmbus channels are stopped before the vmbus server, which leaves a small window where a vmbus request from the guest can arrive after the channel is stopped. Handle this by pending the message in the vmbus channel code. These pended messages do not need to be saved, because vmbus_server will replay them on restore. The maximum number of pended requests should be two per channel_idx, for the case of a pended modify request followed by a pended close. Any other combination should be rejected by vmbus as the device will not be in a valid state.
---------
> 2411: vmbus_channel: Stopped vmbus devices should not see vmbus requests.

- Guide/src/user_guide/openhcl/troubleshooting.md
When investigating the DT issues, it might be of great help to look at the textual representation of the DT blob.
Add notes to the Guide on how to get that done.
> Guide: add notes on DeviceTree diagnostics

- Cargo.lock
- openhcl/virt_mshv_vtl/src/cvm_cpuid/mod.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/mod.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/topology.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/xfem.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hv1_emulator/src/cpuid.rs
- vmm_core/virt/src/generic.rs
- vmm_core/virt_whp/src/lib.rs
As previously discussed, this moves the creation of various CPUID leaves into per-backing code inside virt_mshv_vtl, instead of being lumped together in hv1_emulator. It also adds the previously missing register_pat_available bit to both SNP and TDX, since we support reading PAT. It also removes the bit for access_vp_runtime_msr, as it is not an msr we implement anywhere.
> virt_mshv_vtl/hv1_emulator: Move hypervisor cpuid construction into cvm_cpuid

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/x86/x86defs/src/tdx.rs
- vm/x86/x86defs/src/vmx.rs
- vm/x86/x86emu/src/emulator.rs
- vm/x86/x86emu/src/emulator/bt.rs
- vm/x86/x86emu/src/emulator/mov.rs
- vm/x86/x86emu/src/emulator/rep.rs
- vm/x86/x86emu/src/lib.rs
- vm/x86/x86emu/tests/tests/segments.rs
- vmm_core/virt_support_x86emu/Cargo.toml
- vmm_core/virt_support_x86emu/src/emulate.rs
Adds support for intercepting descriptor table access instructions and generating intercept messages when appropriate. Because VMX only gives us an 'all-or-nothing' bit to enable exits we have to emulate instructions that generate an exit but were not actually asked for by VTL 1. Adds support for half of these, those that touch GDT or IDT, with the other half to come in a follow up because I need a brain break. Their design will likely be very similar anyways.
Slightly refactor the instruction emulator to allow external emulation of memory accesses, without going through the full decoding pipeline first. This primitive could be useful if we end up having to emulate more instructions like this for specific backends with decoding assistance in the future.
Note that only the two IDT …
> TDX: Add support for descriptor table intercepts & some emulation

- openhcl/bootloader_fdt_parser/src/lib.rs
- openhcl/openhcl_boot/src/dt.rs
Backport of #1219, that only contains the functional changes, not the test changes.
>  openhcl_boot: report partition memory with different device type to workaround kernel numa parsing

- openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hv1_hypercall/src/imp.rs
- vm/hv1/hvdef/src/lib.rs
Implements handling of the synthetic cluster ipi hypercalls for CVM guest vsm support.
Tested:
SNP with and without guest vsm boots
> CVM Guest VSM: Synthetic Cluster IPI hypercall handling

- tmk/tmk_core/src/lib.rs
- tmk/tmk_protocol/src/lib.rs
Shows that what is running is indeed what should be:
```log
2025-04-23T18:19:48.093322Z  INFO test: test started, name: "x86_64::ud2"
2025-04-23T18:19:48.098730Z  INFO tmk: running test x86_64::ud2, entrypoint 0x0000000000204cf0, with input StartInput {
command: 0xffff0000,
test_index: 0x3,
vp_count: 0x1,
}
2025-04-23T18:19:48.098907Z  INFO tmk: ISR: vector = 6, has_error_code = false, error_code = 0x0
2025-04-23T18:19:48.098993Z  INFO tmk: test x86_64::ud2 completed
2025-04-23T18:19:48.099948Z  INFO test: test passed, name: "x86_64::ud2"
```
Perhaps useful, lmk :)
> tmk: log test name and parameters

- Cargo.lock
- vm/devices/net/gdma_defs/src/bnic.rs
- vm/devices/net/net_backend/Cargo.toml
- vm/devices/net/net_backend/src/lib.rs
- vm/devices/net/net_backend/src/loopback.rs
- vm/devices/net/net_backend/src/null.rs
- vm/devices/net/net_consomme/src/lib.rs
- vm/devices/net/net_dio/src/lib.rs
- vm/devices/net/net_mana/src/lib.rs
- vm/devices/net/net_packet_capture/src/lib.rs
- vm/devices/net/net_tap/src/lib.rs
- vm/devices/net/netvsp/src/lib.rs
- vm/devices/net/netvsp/src/test.rs
- vm/devices/virtio/virtio_net/src/lib.rs
The net_mana::tx_poll() does not properly handle a CQE of type CQE_TX_GDMA_ERR.  GDMA_ERR is sent from the Hardware to indicate that the queue has been disabled. Once the queue is disabled, no further traffic can be sent out from the Guest. The proper way to handle the Gdma error is to recreate/restart the tx queue. 
Changes:
* Adding logging to help track and triage these issues. A Gdma error can be returned due to any number of problems, so the only way to determine the cause is by logging the vendor error and properties of the packet.
* Modifying net_mana::tx_poll to return an error that indicates the queue should be restarted.
* Modifying netvsp to handle the TxError::TryReturn
* If process_endpoint_tx sees a TryReturn error, it completes any pending tx packets before the queues are …
> Fixing net_mana handling of Gdma Errors

- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Makes finding stuff a little more obvious when you're just digging around the tree.
> CVM: Flatten Cvm inspect state on each VpBacking

- tmk/simple_tmk/src/x86_64/apic.rs
- tmk/tmk_tests/src/lib.rs
- tmk/tmk_vmm/src/run.rs
- vmm_core/virt_support_apic/src/lib.rs
Inject GP on writes to reserved bits, properly propagate changes to the APIC base page.
Add TMK tests to cover this functionality (as well as some basic timer functionality).
On virt_whp, run tmk tests in CI for using the emulated APIC path as well.
> virt_support_apic: improve APIC base MSR handling

- Cargo.lock
- vm/devices/net/gdma_defs/src/bnic.rs
- vm/devices/net/net_backend/Cargo.toml
- vm/devices/net/net_backend/src/lib.rs
- vm/devices/net/net_backend/src/loopback.rs
- vm/devices/net/net_backend/src/null.rs
- vm/devices/net/net_consomme/src/lib.rs
- vm/devices/net/net_dio/src/lib.rs
- vm/devices/net/net_mana/src/lib.rs
- vm/devices/net/net_packet_capture/src/lib.rs
- vm/devices/net/net_tap/src/lib.rs
- vm/devices/net/netvsp/src/lib.rs
- vm/devices/net/netvsp/src/test.rs
- vm/devices/virtio/virtio_net/src/lib.rs
The net_mana::tx_poll() does not properly handle a CQE of type CQE_TX_GDMA_ERR. GDMA_ERR is sent from the Hardware to indicate that the queue has been disabled. Once the queue is disabled, no further traffic can be sent out from the Guest. The proper way to handle the Gdma error is to recreate/restart the tx queue.
Changes:
* Adding logging to help track and triage these issues. A Gdma error can be returned due to any number of problems, so the only way to determine the cause is by logging the vendor error and properties of the packet.
* Modifying net_mana::tx_poll to return an error that indicates the queue should be restarted.
* Modifying netvsp to handle the TxError::TryReturn
* If process_endpoint_tx sees a TryReturn error, it completes any pending tx packets before the queues are …
> Tx GDMA error handling on 2411

- flowey/flowey_lib_hvlite/src/build_openhcl_igvm_from_recipe.rs
The dbgrd.cpio.gz package seems to be broken on aarch64. Disable it for now.
Works around #1234.
> openhcl: disable dbgrd.cpio.gz package for aarch64

- openhcl/underhill_init/src/lib.rs
- tmk/tmk_tests/src/lib.rs
This should fix (or at least make less likely) a race that causes VTL2 pipette to sometimes fail to load.
> tmk_tests: wait for modules to load before trying to launch VTL2 pipette

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/x86/x86defs/src/lib.rs
On my TDX VMs I'm seeing a write to this MSR, which is normally used to trigger microcode updates. I'm not sure why Windows is trying to write to it, but we can't support microcode updates, so just quiet the warning.
> TDX: Quiet a write to an unsupported MSR

- Cargo.lock
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- petri/petri_artifacts_common/src/lib.rs
- petri/src/test.rs
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/mod.rs
- petri/src/vm/openvmm/runtime.rs
- petri/src/vm/openvmm/start.rs
- tmk/tmk_tests/Cargo.toml
- tmk/tmk_tests/build.rs
- tmk/tmk_tests/src/lib.rs
- vmm_tests/vmm_test_macros/src/lib.rs
- vmm_tests/vmm_tests/Cargo.toml
- vmm_tests/vmm_tests/build.rs
- vmm_tests/vmm_tests/tests/tests/main.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/ttrpc.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
- xtask/src/tasks/fmt/house_rules/cfg_target_arch.rs
Stop using `cfg(guest_arch = ...)` for filtering out arch-specific tests. Instead, add a mechanism to skip a test from being reported in the test list.
Also use this mechanism to filter out openvmm+openhcl tests on platforms that don't support this combination, rather than have flowey explicitly filter out such tests.
> vmm_tests: remove uses of guest_arch

- vm/loader/src/paravisor.rs
- vm/x86/x86defs/src/lib.rs
The existing code works by luck because we use the ring 0
GDT selectors. The selector is computed by multiplying the
index by the size of the small GDT entry (by 8 bytes), and
the ring 0 GDT selectors can be computed by shifting by 3.
That gives the correct result by chance rather than by
following the specification.
Extend the x86 definitions, calculate the selectors as the
specification defines.
> loader: use the x86 selector definition

- .cargo/config.toml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_lib_hvlite/src/_jobs/check_openvmm_hcl_size.rs
This newer relocation format produces considerably smaller relocation sections, saving 1.6MB from openvmm_hcl.
> Build musl binaries with RELR relocations

- .github/workflows/openvmm-pr.yaml
#[965](https://github.com/microsoft/openvmm/pull/965) introduced a minor issue in the checked in pipeline yaml. This resolves this by running 'cargo xflowey regen'.
> CI: update out of date line number in openvmm-pr.yaml

- .cargo/config.toml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_lib_hvlite/src/_jobs/check_openvmm_hcl_size.rs
This reverts commit fd5e1a482bb25403b59d9176a5c1b9fa1393bcd6.
I'm in the process of stabilizing the 6.12 kernel release and at first, I thought it would make sense for this to go in at the same time, to offset some of the size increase from 6.12. However, some new test failures that need to be debugged have popped up, so I think it makes sense to get 6.12 stable first.
> Revert "Build musl binaries with RELR relocations (#965)"

- .cargo/config.toml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_lib_hvlite/src/_jobs/check_openvmm_hcl_size.rs
This newer relocation format produces considerably smaller relocation sections, saving 1.6MB from openvmm_hcl.
This reverts commit 493092ce6aa6cf8d9800d7efe0141afa151abc23.
> Reapply "Build musl binaries with RELR relocations (#965)"

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/x86/x86defs/src/vmx.rs
This fills in the todo for emulating these 4 instructions, as well as including some small refactors to the previous 4, and adding a missing security check for load instructions. I don't have a way to test this end-to-end currently, but the refactors at least don't break the code that I can test.
> TDX: LDTR and TR access emulation

- .github/workflows/openvmm-pr.yaml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs
- vmm_tests/petri_artifacts_vmm_test/src/lib.rs
- vmm_tests/vmm_test_images/src/lib.rs
- vmm_tests/vmm_test_macros/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
Add Windows 11 ARM64 tests. Windows 11 (and Windows Server 2025) reboot once on first boot, so add a temporary workaround for OpenVMM tests (Hyper-V tests work fine since we don't notice that it reboots).
> vmm_tests: add windows arm tests

- openhcl/hcl/src/ioctl/tdx.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Remove the MSR bitmap struct since we were never storing it anywhere, just set MSR bits with individual calls. This is simpler and uses less stack space, but slightly less efficient since we now make more vmcs writes overall, but since these are cold paths with a small number of calls I think this tradeoff is worthwhile. Then update intercept registration to set the required bits.
> TDX: Configure MSR intercepts for VTL 1, refactor MSR intercepts in general

- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
The TLB flush hypercalls are necessary when multiple VTLs are being run in order to synchronize our TLB locks, but when there's no VSM going on we don't need them. They're also slower than just not using them. Add some runtime cpuid fixup code that removes our normal cpuid recommendation of them when VSM is disabled or revoked. Then enable them for TDX just like SNP. We know the TDX implementation still has a race condition, but since VSM is still a WIP that's fine.
Tested that a non-VSM TDX VM issues these hypercalls with only the enablement change, then doesn't issue them with the full change.
Part of #699
> CVM: Don't recommend TLB flush hypercalls in cpuid without VSM

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_lib_hvlite/src/_jobs/build_and_run_nextest_vmm_tests.rs
- flowey/flowey_lib_hvlite/src/_jobs/consume_and_test_nextest_vmm_tests_archive.rs
This code was added as a quick hack long ago to try to debug crashes in CI, but it never actually worked. Just remove it so we don't pretend we're doing something useful and save a few seconds of CI time per run.
> CI: Remove broken crash dump upload attempt

- support/pal/pal_uring/src/threadpool.rs
- tmk/tmk_vmm/src/paravisor_vmm.rs
Ensure the paravisor partition has been fully dropped before proceeding to the next test. This should fix some race conditions causing VTL0 triple faults.
> tmk_vmm: drain paravisor partition before starting next test

- vm/loader/manifests/openhcl-x64-release.json
The Linux kernel sizes tmpfs for rootfs based on half of the available ram. When OpenHCL is loaded at high memory addresses, for some reason the kernel reports different amounts of available memory, which results in tmpfs being a different size with no free space available, leading to issues writing the underhill_pid:
```
<6>[    1.552853] [U] Error: failed to write pid to /run/underhill.pid
<6>[    1.563864] [U] Caused by:
<6>[    1.565310] [U]     No space left on device (os error 28)
```
Bump the size up slightly to 70MB, which should allow these minimum memory tests to work when loaded at high GPAs. 
#1266 tracks investigating why the kernel does this behavior.
> loader: bump ohcl minimum memory size for x64 release to 70 MB

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_cli/src/flow_resolver/stage1_dag.rs
- flowey/flowey_core/src/node.rs
- flowey/flowey_lib_common/src/cache.rs
- flowey/flowey_lib_common/src/cfg_persistent_dir_cargo_install.rs
- flowey/flowey_lib_common/src/download_azcopy.rs
- flowey/flowey_lib_common/src/download_cargo_fuzz.rs
- flowey/flowey_lib_common/src/download_cargo_nextest.rs
- flowey/flowey_lib_common/src/download_gh_cli.rs
- flowey/flowey_lib_common/src/download_gh_release.rs
- flowey/flowey_lib_common/src/run_cargo_build.rs
- flowey/flowey_lib_common/src/run_cargo_nextest_run.rs
- flowey/flowey_lib_hvlite/src/build_openhcl_initrd.rs
* Add a method for turning a `WriteVar<SideEffect>` into a `WriteVar<T>`, for throwing away the results of an operation but retaining the side effect.
* Allow collections (tuples, vecs, maps) of `ClaimedReadVar` to be read as one, like we allow collections of `ReadVar` to be claimed as one.
* Make `SideEffect` an alias for `()` rather than an uninhabited type so that it can be read and returned from Rust step functions. This is not yet used for anything useful, but future cleanup will leverage this.
> flowey: simplify some variable patterns

- openhcl/underhill_core/src/emuplat/tpm.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/vm/openvmm/construct.rs
- petri/src/vm/openvmm/modify.rs
- vm/devices/get/get_resources/src/lib.rs
- vm/devices/get/guest_emulation_device/src/lib.rs
- vm/devices/get/guest_emulation_device/src/resolver.rs
- vm/devices/get/guest_emulation_device/src/test_utilities.rs
- vm/devices/tpm/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
This PR updates the TPM AK cert handling logic to allow the guest to trigger an AK cert request if the first request made during boot fails. Other changes include
* Update `request_ak_cert` to return empty vector, allowing TPM to distinguish between AK cert request failure and host agent unavailable. TPM only supports AK cert retry on the former case.
* Fix the bug for TVM that AK cert request triggered by NV read does not work correctly.
* Update vmm_tests  and the IgvmAttest state machine in test GED to test the code change.
> tpm: support AK cert retry if the boot-time request fails

- openhcl/underhill_core/src/vmbus_relay_unit.rs
- vmm_core/state_unit/src/lib.rs
Only `vmbus_server` was using this state transition, but refactoring has made it unnecessary.  Simplify the state machine model by removing it from all devices.
> state_unit: remove PostRestore transition

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
Fixes a VSM regression introduced by #1207.
> virt_mshv_vtl: Don't try to update proxy_irr when VTL 1 touches its synic

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hvdef/src/lib.rs
Handles the install intercept hypercall on io ports for guest vsm support in cvms.
Tested:
SNP +/- guest vsm boots
> cvm guest vsm: install intercept hypercall handling

- vm/devices/tpm/src/tpm_helper.rs
PR 1120 added a TPM NVRAM behavior where the AKCert NVRAM index is always undefined and redefined, with size 4kB and the platform-defined attribute. In some cases, existing VMs may have an NVRAM blob that is too small to accommodate a 4kB index. This change works around that by not modifying the existing index if it is not platform-defined. This change also keeps other behavior added in 1120, such as preserving any existing contents of that NVRAM index.
> Avoid NVRAM out-of-space issue

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Makes things a bit nicer. Found while poking around yesterday debugging cstar.
> virt_mshv_vtl: Flatten some more CVM-related inspects

- hyperv/tools/hypestv/src/windows/mod.rs
- hyperv/tools/hypestv/src/windows/vm.rs
Add an `nmi` command to inject a non-maskable interrupt into the VM.
This is useful to force a panic when the VM appears to be completely unresponsive.
> hypestv: add nmi command

- flowey/flowey_cli/src/pipeline_resolver/direct_run.rs
Reduce clutter in local `cargo xflowey build-igvm` output--skip writing minor step output, since those steps cannot fail and are not doing anything interesting.
> flowey: don't log minor steps

- openhcl/gen_init_ramfs.py
The generated openhcl initrd file has embedded modification times. Remove these so that subsequent invocations of build-igvm produce an identical binary.
A less aggressive change would have set the mtime to the time of the config file or something. But these modification times really have no value for us, and in the future the config file itself may be generated at runtime by flowey (if it's not already--I didn't check). So just use zero (Unix epoch).
> gen_init_ramfs: set all modification times to 0

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
This change updates the dev kernel to a version which contains a fix for sidecar when using nested virtualization. For more information, see https://github.com/microsoft/OHCL-Linux-Kernel/pull/70.
> kernel: update dev kernel to 6.12.9.2 release

- openhcl/underhill_core/src/lib.rs
- openhcl/underhill_core/src/options.rs
- openhcl/underhill_core/src/worker.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- tmk/tmk_vmm/src/paravisor_vmm.rs
Now that both SNP and TDX support for guest vsm is nearing preview-feature-complete status this env var is no longer needed. It is up to the guest whether to enable VBS/VSM or not.
> Remove the CVM Guest VSM configuration env var

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
An NMI_unmasking_due_to_IRET exit is not spurious, it has a reason. Instead, always check this bit first and only check for spuriousness afterwards.
> TDX: Tweak ordering of ept_violation actions

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
> TDX: Enable MBEC for VTL 0

- openhcl/underhill_core/src/worker.rs
OpenHCL has the ability to allocate it's own memory from the partition memory map, but that information is only available via inspect today. Log the memory allocation mode and what vtl2 ranges were chosen. You can technically back-calculate this somewhat from the e820 map, but it's annoying so just log it like we do vtl0 memory. 
The output now looks like this:
```
<30>[    2.582076] underhill_core::worker:  INFO worker_new{ name="UnderhillWorker" action="new"}:init:init/new_underhill_vm:  memory allocation mode memory_allocation_mode=Vtl2 { memory_size: Some(20000000), mmio_size: Some(8000000) }
<30>[    2.592587] underhill_core::worker:  INFO worker_new{ name="UnderhillWorker" action="new"}:init:init/new_underhill_vm:  vtl2 ram vtl2_ram="0x8000000-0x27000000, 0x107000000-0x108000000" …
```
> openhcl: log vtl2 memory allocation mode and memory allocation size

- openhcl/hcl/src/ioctl.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
Currently passing VP index, and the kernel might return the per-CPU data of another processor.
Should work. Out of abundance of caution, will do basic tests.
> virt_mshv_vtl: the VMSA PFN IOCTL takes a CPU number

- .github/workflows/openvmm-pr.yaml
- flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs
This change updates the default GitHub concurrency behavior to define a concurrency group that is workflow-specific rather than the current behavior of using the just the git reference (which prevents multiple unrelated workflows from running concurrently).
For more information, see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-using-concurrency-and-the-default-behavior.
> flowey: change default concurrency group behavior

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This removes one access of the annoying Backing::hv getter, and also makes it clearer what is happening when.
> virt_mshv_vtl: Cleanup MSR accessing for all backends

- openhcl/hcl/src/ioctl.rs
- openhcl/underhill_mem/src/lib.rs
- openhcl/underhill_mem/src/mapping.rs
A page visibility change in the guest may partially succeed. This was `todo!`-ed before, so implement it.
Most guests will probably crash right after this, but openhcl itself should not crash. This way we can attribute the failure correctly. 
Fixes #1312
> openhcl/cvm: correctly handle partial success on page visibility requests

- support/task_control/src/lib.rs
- vm/devices/pci/vpci/src/bus.rs
- vm/devices/pci/vpci/src/device.rs
- vm/devices/vmbus/vmbus_channel/src/simple.rs
As I work on the VPCI client driver, it will be nice to use the VPCI
server implementation in tests. Make this easier:
* Split the VPCI chipset device from the channel (keeping them together
for product code).
* Allow simple vmbus devices to be used with generic ring buffer
memories, not just with GPADL-backed ring buffers.
* Make it easy to construct a `StopTask` needed to run the simple
vmbus channel.
> devices: make vpci easier to use in tests

- .github/workflows/openvmm-docs-ci.yaml
- .github/workflows/openvmm-docs-pr.yaml
- flowey/flowey_hvlite/src/pipelines/build_docs.rs
After merging #1299 I noticed that we are using our selfhosted pools for some of the jobs, which are a limited resource. This change moves all the docs jobs over to using GitHub hosted pools which will reduce contention on the selfhosted pools and reduce runtime.
> CI: Update docs pipeline to use GitHub hosted pools

- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/partition.rs
- vm/devices/pci/vpci/src/bus.rs
- vm/devices/pci/vpci/src/device.rs
- vm/devices/pci/vpci/src/test_helpers/mod.rs
- vm/vmcore/src/vpci_msi.rs
- vmm_core/src/device_builder.rs
- vmm_core/virt/src/aarch64/gic_software_device.rs
- vmm_core/virt/src/generic.rs
- vmm_core/virt/src/x86/apic_software_device.rs
- vmm_core/virt_whp/src/device.rs
The OpenHCL VPCI relay will need to make asynchronous vmbus requests to the host to map/unmap interrupts on behalf of the guest. Make the underlying trait async in anticipation of that.
> vpci: make interrupt mapping async

- vm/devices/net/netvsp/src/lib.rs
- vm/devices/net/netvsp/src/test.rs
OpenVMM Netvsp driver has a hardcoded assumption that the RSS Indirection Table size will not change during servicing. There are rare cases where capabilities may be modified during re-advertisement. This occurred when MANA switched from giving a flat 128 to scaling based on the number of vcpu cores during a FHR. The result was a failed servicing operation.
Dynamic changes to the RSS Table Size are difficult because there is no mechanism for informing the Guest to re-query RSS capabilities, which it assumes do not change during its lifetime. Reducing the Indirection Table size can cause unexpected and difficult to investigate issues with network performance and processor overloading. In Azure, VMs are allocated the minimum number of indirection table entries for VTL2 VF at startup. And we …
> netvsp: Mismatched Indirection Table error on servicing

- vm/vmgs/vmgs/src/vmgs_impl.rs
The test fails due to overflow 1/256 of the time. Fix this by changing
the nonce manipulation to avoid overflow.
> vmgs: fix overflow in test_logger()

- vm/hv1/hvdef/src/lib.rs
There are some extra leading spaces in the `HvError` messages due to the way the macro works. Trim them.
> hvdef: fix spacing around hypervisor errors

- Cargo.lock
- openhcl/hcl/src/ioctl.rs
- vm/x86/tdcall/Cargo.toml
- vm/x86/tdcall/src/lib.rs
Fix some missing `#[source]` attributes and redundant error string reporting.
> hcl: clean up error messages

- Cargo.lock
- support/mesh/mesh_remote/Cargo.toml
- support/mesh/mesh_remote/src/alpc_node.rs
- support/mesh/mesh_remote/src/lib.rs
- support/mesh/mesh_remote/src/test_common.rs
- support/mesh/mesh_remote/src/unix_node.rs
- support/pal/src/windows/alpc.rs
Messages on the Windows ALPC backend near the small message limit fail
to send due to a miscalculation of the maximum message size. Fix this
the maximum size calculation and add tests.
> mesh_remote: windows: fix messages near the small message limit

- Cargo.lock
- openhcl/hcl/src/ioctl.rs
- openhcl/underhill_core/Cargo.toml
- openhcl/underhill_core/src/worker.rs
- openhcl/virt_mshv_vtl/src/lib.rs
These routines are being used only by the fallback MMIO code in `underhill_core`, so make them available without needing a whole `Hcl` instance. This gets `virt_mshv_vtl` and `UhPartition` out of the path.
> hcl: move MMIO routines from Hcl to MshvHvcall

- openhcl/openhcl_boot/src/cmdline.rs
- openhcl/openhcl_boot/src/host_params/dt.rs
- openhcl/openhcl_boot/src/host_params/mod.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/openhcl_boot/src/sidecar.rs
Add `OPENHCL_SIDECAR` boot loader command-line option for controlling whether sidecar gets enabled:
* `OPENHCL_SIDECAR=off`: Disable sidecar support.
* `OPENHCL_SIDECAR=on`: Enable sidecar support, if possible.
* `OPENHCL_SIDECAR=log`: Enable sidecar logging.
This replaces the existing `SIDECAR_LOGGING` command line option.
> openhcl_boot: add sidecar command line options

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
- flowey/flowey_lib_hvlite/src/build_openhcl_igvm_from_recipe.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
This change updates the main kernel version and adds sidecar to all x64 non-CVM recipes. The only difference between this version of the kernel and the previous version, the new version contains sidecar patches which were previously only in the dev kernel. With this update, there is currently no delta between dev and main kernel versions.
https://github.com/microsoft/OHCL-Linux-Kernel/releases/tag/rolling-lts%2Fhcl-main%2F6.12.9.3
> igvm: add sidecar to all non-CVM x64 recipes

- vm/devices/net/netvsp/src/lib.rs
- vm/devices/net/netvsp/src/test.rs
OpenVMM Netvsp driver has a hardcoded assumption that the RSS Indirection Table size will not change during servicing. There are rare cases where capabilities may be modified during re-advertisement. This occurred when MANA switched from giving a flat 128 to scaling based on the number of vcpu cores during a FHR. The result was a failed servicing operation.
Dynamic changes to the RSS Table Size are difficult because there is no mechanism for informing the Guest to re-query RSS capabilities, which it assumes do not change during its lifetime. Reducing the Indirection Table size can cause unexpected and difficult to investigate issues with network performance and processor overloading. In Azure, VMs are allocated the minimum number of indirection table entries for VTL2 VF at startup. And we …
> netvsp: Mismatched Indirection Table error on servicing ( #771) 2411

- support/mesh/mesh_channel/src/cancel.rs
- vm/devices/vmbus/vmbus_proxy/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This still needs to be wired up to vmbus server start.
> vmbusproxy: add code to flush pending actions

- vmm_tests/vmm_tests/tests/tests/x86_64.rs
These tests were fixed by microsoft/OHCL-Linux-Kernel#70. Enable them.
> vmm_tests: enable sidecar tests in Hyper-V

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-docs-ci.yaml
- .github/workflows/openvmm-docs-pr.yaml
- .github/workflows/openvmm-pr.yaml
- Cargo.lock
- flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs
- flowey/flowey_core/Cargo.toml
- flowey/flowey_core/src/pipeline/artifact.rs
We use hidden files to tag opaque directories in artifacts, but GitHub discards them out of an abundance of caution. Since we are generally quite careful about artifact construction, there is no security concern with including hidden files, so include away.
Also add some tests of the artifact parsing functionality, since originally I thought that might be the issue.
> flowey: publish hidden files in GitHub artifacts

- petri/src/vm/openvmm/runtime.rs
This should make it much easier to read the register state.
> petri: use hex output when VM triple faults

- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
> vmm_tests: disable sidecar in keepalive servicing tests

- flowey/flowey_core/src/pipeline/artifact.rs
Don't put relative paths inside artifact variables.
> flowey: ensure resolved artifact paths are absolute

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Continuing the attempts at cleanup and separation of concerns.
> virt_mshv_vtl: Move some cvm-only interrupt handling code into cvm-only locations

- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
This is a follow-up to https://github.com/microsoft/openvmm/pull/1324 to close feedback on that.
> virt_mshv_vtl, snp: Provide control data for SEV errors

- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
init_vmsa() logs only SEV status but not the SEV features it sets in the VMSA. Report that, too.
Also use the structured tracing throughout the function. Maybe could consider logging in this function at the debug level to produce less output on large VMs
> virt_mshv_vtl, snp: Log computed SEV features, too

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
TSC_AUX MSR writes are rare in guests. Unconditionally exit on such writes so that the kernel does not have to read the guest's TSC_AUX on every exit.
> virt_mshv_vtl: tdx: exit on TSC_AUX writes

- support/fast_select/src/lib.rs
This makes it clean under miri
> fast_select: Support provenance and add a sanity debug_assert

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hv1_hypercall/src/imp.rs
This is called by SK in certain error conditions to send an NMI to VTL 0, but implement it for regular interrupts too since it's easy enough.
> CVM: Implement AssertVirtualInterrupt for CVMs

- vm/devices/net/net_mana/src/lib.rs
Unsafe code presents risks and should be carefully tested. First step is to be explicit about where we do and don't use unsafe code.
Adding forbid unsafe_code to networking libraries:
* net_mana
> net_mana: adding explicit forbidding of unsafe code

- Cargo.lock
- Cargo.toml
- support/address_filter/Cargo.toml
- support/address_filter/src/lib.rs
- vmm_core/virt_support_apic/Cargo.toml
- vmm_core/virt_support_apic/src/lib.rs
- vmm_core/vmotherboard/Cargo.toml
- vmm_core/vmotherboard/src/chipset/io_ranges/mod.rs
This allows us to filter out specific vectors from appearing in tracing output, such as timers or DPCs, allowing us to see only the interrupts we actually care about. The inspect path to get here is kinda gnarly though: `vm/partition/vp/{vp_index}/backing/lapics/{vtl}/lapic/vector_filter`
> virt_support_apic: Add runtime configurable tracing filtering of vectors

- vm/devices/net/gdma/src/lib.rs
- vm/devices/net/gdma_defs/src/lib.rs
Unsafe code presents risks and should be carefully tested. First step is to be explicit about where we do and don't use unsafe code.
Adding forbid unsafe_code to networking libraries:
* gdma
* gdma_defs
> gdma: adding explicit forbidding of unsafe code

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
This change updates the Linux kernel to the latest version. The only difference between this and the previous kernel is that it contains two additional patches:
1. *drivers: hv: mshv_vtl: introduce ioctl for kicking a remote cpu* - https://github.com/microsoft/OHCL-Linux-Kernel/pull/68
2. *mshv_vtl: fix and optimize MSR context switching* - https://github.com/microsoft/OHCL-Linux-Kernel/pull/76
> kernel: update dev / main kernels to latest available

- Cargo.lock
- openhcl/hcl/Cargo.toml
- openhcl/hcl/src/ioctl.rs
- openhcl/hcl/src/protocol.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Part of #699. Tested that a 128 VP with Guest VSM still boots.
Depends on https://github.com/microsoft/OHCL-Linux-Kernel/pull/68, which came in through https://github.com/microsoft/openvmm/pull/1357
> TDX: Fix TLB flush waking by using new ioctl

- petri/src/test.rs
- tmk/simple_tmk/src/main.rs
- tmk/tmk_core/src/lib.rs
- tmk/tmk_tests/src/lib.rs
- vm/devices/get/get_protocol/src/lib.rs
- vm/devices/get/guest_emulation_device/src/lib.rs
- vm/devices/get/guest_emulation_device/src/test_utilities.rs
- vm/devices/get/guest_emulation_transport/src/lib.rs
- vm/devices/get/guest_emulation_transport/src/process_loop.rs
- xtask/src/tasks/fmt/house_rules/unsafe_code_comment.rs
1. Add forbid(unsafe) to tmk_tests by removing the expect inside the macro in petri.
2. Change some allows to expects in tmk crates
3. Add forbid to get_protocol with some zerocopy tweaks
> Add a few more forbid(unsafe)s

- openhcl/minimal_rt/src/enlightened_panic.rs
- openhcl/openhcl_boot/src/arch/x86_64/hypercall.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/openhcl_boot/src/rt.rs
- openhcl/sidecar/src/arch/x86_64/mod.rs
* Enable panic messages early in boot.
* Include the panicking component's identity in the panic message (openhcl-boot vs sidecar)
* Add more context for one of the possible early panics.
> openhcl_boot: improve panic output

- petri/src/vm/mod.rs
- petri/src/vm/openvmm/runtime.rs
- vmm_core/src/partition_unit.rs
- vmm_core/src/partition_unit/vp_set.rs
- vmm_core/virt_whp/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
Ensure that the VTL2 state of the partition gets scrubbed after every
servicing operation, not just the first one.
Also, update the servicing test to loop a few times, and add or improve
tracing in a couple of places.
> partition_unit: consistently scrub VTL2 during VTL2 servicing

- openvmm/openvmm_entry/src/lib.rs
This makes it easier to diagnose issues.
> openvmm: cli: allow inspections during VTL2 servicing

- openhcl/underhill_core/src/nvme_manager.rs
- vm/devices/storage/disk_nvme/nvme_driver/fuzz/fuzz_nvme_driver.rs
- vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs
- vm/devices/storage/disk_nvme/nvme_driver/src/queue_pair.rs
- vm/devices/storage/disk_nvme/nvme_driver/src/tests.rs
A previous change increased the DMA memory allocated per queue to 128 pages, to handle the need for additional pages to bounce buffer on CVMs. Make this configurable, so that the pages allocated go back to the previous of 64, when not isolated.
> nvme_driver: allocate different DMA memory sizes if not bounce buffering

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
Fix EnableVpVtl handling so that it gets the VMSA for the VP that's being targeted, not (necessarily) the current one.
Tested that SNP + guest vsm boots now.
Fixes #1367
> snp guest vsm: target correct vp in getting vtl1 vmsa for enablevpvtl

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
This is based on the legacy HCL's, but slightly modified to fit our slightly different organization. Tested that a 128 VP TDX VM with VSM still boots and shuts down cleanly.
Closes #699 together with #1325.
> TDX: Remove RwLock on tlb flush state tracking to allow reads to interleave with a single write

- openhcl/underhill_core/src/nvme_manager.rs
Injected simulated errors and got the print in the log. Good for debugging in the fleet.
VTL2 servicing will fail and restart on error.
> Print error message on NVMe restore failure

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-docs-ci.yaml
- .github/workflows/openvmm-docs-pr.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_cli/src/cli/debug/interrogate.rs
- flowey/flowey_cli/src/cli/exec_snippet.rs
- flowey/flowey_cli/src/cli/mod.rs
- flowey/flowey_cli/src/cli/var_db.rs
- flowey/flowey_cli/src/flow_resolver/stage1_dag.rs
- flowey/flowey_cli/src/pipeline_resolver/ado_yaml.rs
- flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs
- flowey/flowey_cli/src/var_db/in_memory.rs
- flowey/flowey_cli/src/var_db/single_json_file.rs
- flowey/flowey_core/src/node.rs
- flowey/flowey_core/src/node/github_context.rs
- flowey/flowey_core/src/patch.rs
- flowey/flowey_core/src/pipeline.rs
- flowey/flowey_lib_common/src/gh_download_azure_key_vault_secret.rs
- flowey/flowey_lib_common/src/gh_task_azure_login.rs
- flowey/flowey_lib_hvlite/src/_jobs/cfg_gh_azure_login.rs
Currently, a `ReadVar`/`WriteVar` pair can be marked as secret, in which case flowey is careful never to display its value in logs. To mark a variable as such, the user must remember to create the variable pair with `new_secret_var()`, and the user must ensure that users of the variable to do not rewrite its contents into some other, non-secret variable. This is hard to do accurately, especially as we change the code to create more variables implicitly (via `<foo>v`-style methods such as `reqv` and `emit_rust_stepv`).
Change the model so that _variables_ are not secret but their _values_ can be--when any variable is written to, the caller can specify that the value is secret. Propagate this to readers of the variable, even if this variable is converted into and back from a CI environment …
> flowey: make values secret, not variables

- Cargo.lock
- openvmm/hvlite_core/src/worker/dispatch.rs
- vm/devices/vmbus/vmbus_proxy/Cargo.toml
- vm/devices/vmbus/vmbus_proxy/src/lib.rs
- vm/devices/vmbus/vmbus_proxy/src/proxyioctl.rs
- vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs
- vm/devices/vmbus/vmbus_server/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This PR integrates the `vmbus_server` saved state support with `proxyintegration`. Previously, `proxyintegration` and vmbusproxy had no concept of save and restore, and their respective states were completely reconstructed from scratch on each start.
On start, if using the proxy, the server sends its saved state to the proxy integration, which in turn repopulates the saved channels and GPADLs in vmbusproxy. On start, the saved state is cleared.
- Create a new mesh channel in `vmbus_server` and `proxyintegration` which allows the server to send and clear saved state to the proxy.
- On receive of the saved state, create skeleton channels in vmbusproxy with their GPADLs to be later claimed by a device.
- On receiving an offer from vmbusproxy, send `ChannelServerRequest::Restore  to the …
> vmbusproxy: Support saved state

- openhcl/underhill_core/src/dispatch/mod.rs
- vm/devices/get/get_protocol/src/lib.rs
- vm/devices/get/guest_emulation_device/src/lib.rs
The protocol definition for nvme keepalive changed but the old definition did not get removed from the release branch. Disable the feature altogether.
This is a partial cherry pick of #464 / 6236ceec3238ed2a68ed829c2b344e363c6dfe81.
> openhcl: disable nvme keepalive

- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
The change made in #1361 did not correctly clear the VTL2 saved state request channel, preventing the kernel proxy from shutting down cleanly if the VM was using VTL2.
> vmbus_server: fix VTL2 shutdown for proxy integration.

- Cargo.lock
- Cargo.toml
- openhcl/underhill_mem/Cargo.toml
- openhcl/underhill_mem/src/lib.rs
- openhcl/virt_mshv_vtl/Cargo.toml
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- support/minircu/Cargo.toml
- support/minircu/src/lib.rs
- support/minircu/src/linux.rs
- support/minircu/src/other.rs
- support/minircu/src/windows.rs
- vm/vmcore/guestmem/Cargo.toml
- vm/vmcore/guestmem/fuzz/Cargo.toml
- vm/vmcore/guestmem/src/lib.rs
When guest memory page protections are changed (e.g., pages are transitioned between shared and private), we need to flush concurrent accesses to those pages by the paravisor before updating the page state in hardware. Otherwise, faults or cross-VTL data leaks may occur.
Add this synchronization as cheaply as we can: add a simple RCU (Read-Copy-Update) mechanism that allows threads accessing guest memory to cheaply synchronize with threads mutating the page access bitmaps. Use the membarrier() syscall on Linux to allow readers to operate without memory barriers, shifting the expensive to the (infrequent) bitmap update paths.
Only enable this mechanism in OpenHCL, since other environments do not rely on bitmap-based guest memory access controls.
> underhill_mem: add RCU implementation to synchronize bitmap changes

- support/inspect/src/lib.rs
Not seen in CI since we don't have a cargo-hack check, but seen locally.
> inspect: Fix docs when building for no_std

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Continuing on separating out these two, and removing the unwraps doing so allows for.
> virt_mshv_vtl: Separate out CVM and non-CVM deliver_synic_messages

- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This extra level of indirection is no longer necessary, now that this code lives purely in HardwareIsolatedBacking.
> virt_mshv_vtl: Cleanup cross-vtl interrupt checking

- .config/nextest.toml
- Cargo.lock
- Cargo.toml
- openhcl/virt_mshv_vtl/Cargo.toml
- openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
- support/atomic_ringbuf/Cargo.toml
- support/atomic_ringbuf/src/lib.rs
- vm/hv1/hvdef/src/lib.rs
- xtask/src/tasks/fmt/house_rules/cfg_target_arch.rs
The added tests use [loom](https://docs.rs/loom/0.7.2/loom/) to ensure that all possible order of operations work correctly. This required tweaking the orderings we use. Can be reviewed commit-by-commit.
> TDX: Pull TLB flush ringbuf struct into support/, add tests

- openhcl/underhill_core/src/nvme_manager.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- support/inspect/src/defer.rs
- support/inspect/src/initiate.rs
- support/inspect/src/lib.rs
- support/mesh/mesh_process/src/lib.rs
- vm/devices/net/netvsp/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/channels.rs
- vmm_core/src/partition_unit/vp_set.rs
- vmm_core/state_unit/src/lib.rs
- vmm_core/virt/src/state.rs
Wrap `Deferred` in a `Box` so that it's cheaper to pass around. Move immutable parts of `Request` into a structure that can be stored at the base of the call stack. Remove some deferred initialization in `Response`.
As part of this, eliminate the `Response::request` method for getting a new `Request` from an existing `Response`. Instead, use the `merge` method along with `adhoc`. This is necessary to avoid needing extra checks in the common path. It's also more consistent with other uses of `Response`.
> inspect: reduce object sizes

- openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
We support these regs on all backends, so no reason not to.
> CVM: Set GuestCrashRegsAvailable in cpuid

- rust-toolchain.toml
This branch will be on 1.86.0 for the forseeable future. As per our internal support policy this is an even version.
> Repo: Lock to our rust version for this release branch

- vm/devices/vmbus/vmbus_proxy/src/lib.rs
- vm/devices/vmbus/vmbus_proxy/src/proxyioctl.rs
- vm/devices/vmbus/vmbus_proxy/src/vmbusioctl.rs
- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This change updates proxyintegration to pass the channel's target VTL to the vmbusproxy driver when restoring channels. This allows the driver to mark the channels with the correct VTL immediately.
> vmbus_server: include VTL when restoring proxy channels

- openhcl/underhill_core/src/dispatch/mod.rs
Reduces the timeout for flushing logs during servicing to reduce blackout time if there is some issue with flushing the logs.
> openhcl servicing: decrease flush logs timeout

- Guide/src/reference/openhcl/diag/cvm_restrictions.md
- vm/cvm_tracing/src/lib.rs
After long discussions we have decided to flip the default of our tracing filter, and to allow untagged tracing statements by default. We believe that the risks and costs of being unable to debug incidents in production are too high, and that we can manually scrub our tracing statements to ensure that no sensitive information is leaked.
Part of #852.
> cvm_tracing: Allow untagged tracing statements by default

- openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/tdx.rs
We support these regs on all backends, so no reason not to.
Cherry-pick of #1308
> CVM: Set GuestCrashRegsAvailable in cpuid (#1308)

- .config/nextest.toml
- Cargo.lock
- Cargo.toml
- openhcl/virt_mshv_vtl/Cargo.toml
- openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
- support/atomic_ringbuf/Cargo.toml
- support/atomic_ringbuf/src/lib.rs
- vm/hv1/hvdef/src/lib.rs
- xtask/src/tasks/fmt/house_rules/cfg_target_arch.rs
The added tests use [loom](https://docs.rs/loom/0.7.2/loom/) to ensure that all possible order of operations work correctly. This required tweaking the orderings we use.
Cherry-pick of #1387
> TDX: Pull TLB flush ringbuf struct into support/, add tests (#1387)

- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
Technically a guest is allowed to report multiple crashes, for example if they reboot after a crash without resetting VTL 2 state. Currently the host will tear us down when we report a crash, but that's a host-side policy and not something we should depend on.
> virt_mshv_vtl: Be more spec-compliant with crash_ctl reads

- openvmm/openvmm_entry/src/cli_args.rs
- openvmm/openvmm_entry/src/lib.rs
This PR enables routing serial output to a file. Example usage: 
```
openvmm.exe ... --com3 file="./path/to/file"
```
> openvmm: add ability to route serial output to a file

- .github/workflows/upload-petri-results.yml
> ci: escape special characters in workflow names

- flowey/flowey_cli/Cargo.toml
- flowey/flowey_cli/src/cli/var_db.rs
- flowey/flowey_cli/src/var_db/single_json_file.rs
We are trying to write a non-JSON-formatted value to track that an env-var-sourced variable is secret. Fix this by writing `null`. Also add in some diagnostics and improve the in-memory variable representation to avoid so many allocations.
> flowey: fix saving secret vars (#1417)

- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/tlb_lock.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vmm_core/virt_mshv/src/lib.rs
- vmm_core/virt_support_aarch64emu/src/emulate.rs
- vmm_core/virt_support_x86emu/src/emulate.rs
- vmm_core/virt_support_x86emu/tests/tests/checkvtlaccess.rs
- vmm_core/virt_support_x86emu/tests/tests/emulate.rs
- vmm_core/virt_support_x86emu/tests/tests/translate.rs
- vmm_core/virt_whp/src/emu.rs
- vmm_core/virt_whp/src/hypercalls.rs
- vmm_core/virt_whp/src/lib.rs
- vmm_core/virt_whp/src/vp.rs
Don't bother telling the hypervisor what it already knows.  Also fixup ARM code, since it wasn't handling this.
> virt_mshv_vtl/mshv: Cleanup TLB lock tracking

- Guide/src/reference/openhcl/diag/cvm_restrictions.md
- vm/cvm_tracing/src/lib.rs
After long discussions we have decided to flip the default of our tracing filter, and to allow untagged tracing statements by default. We believe that the risks and costs of being unable to debug incidents in production are too high, and that we can manually scrub our tracing statements to ensure that no sensitive information is leaked.
Cherry-pick of #1402.
Part of #852.
> cvm_tracing: Allow untagged tracing statements by default (#1402)

- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/vm_topology/src/memory.rs
On TDX, we see some cases where the guest attempts to access an address with an incorrect shared bit. It's unclear if this is an issue in OpenHCL, the guest, or the host, but fix OpenHCL crashing with an emulation failure due to a `GuestMemory` access failure, and instead inject a machine check into the guest. 
For addresses outside of mmio and ram, continue to emulate but log that the guest did something strange. In the future, we may also inject a machine check on that path. 
Tested via a uefi app that attempts to access a shared page at a private gpa (see https://github.com/chris-oo/openvmm/blob/uefi-tmk-write-to-shared/tmk/tmk_launch/src/main.rs) with the following crash:
```
[kmsg]: [3.058450] virt_mshv_vtl::processor::tdx: WARN  guest accessed inaccessible gpa, injecting MC …
```
> openhcl/tdx: inject machine check on ept exits caused by bad guest addresses

- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/vm_topology/src/memory.rs
On TDX, we see some cases where the guest attempts to access an address with an incorrect shared bit. It's unclear if this is an issue in OpenHCL, the guest, or the host, but fix OpenHCL crashing with an emulation failure due to a `GuestMemory` access failure, and instead inject a machine check into the guest.
For addresses outside of mmio and ram, continue to emulate but log that the guest did something strange. In the future, we may also inject a machine check on that path.
Tested via a uefi app that attempts to access a shared page at a private gpa (see
https://github.com/chris-oo/openvmm/blob/uefi-tmk-write-to-shared/tmk/tmk_launch/src/main.rs) with the following crash:
```
[kmsg]: [3.058450] virt_mshv_vtl::processor::tdx: WARN  guest accessed inaccessible gpa, injecting MC …
```
> openhcl/tdx: inject machine check on ept exits caused by bad guest addresses (#1340)

- openhcl/sidecar/src/arch/x86_64/init.rs
- openhcl/sidecar/src/arch/x86_64/mod.rs
- openhcl/sidecar/src/arch/x86_64/vp.rs
The register page is not valid until it has been mapped and the hypervisor says it's valid. However, the in-memory contents of the page before it is mapped could be non-zero, especially across a servicing operation. This can cause the VMM to think the register page contents are valid, causing register corruption.
Fix this by explicitly clearing the valid flag in the register page during sidecar startup.
Also zero a few more potentially stale structures to avoid potential bugs.
> sidecar: zero initialize unmapped register page

- openhcl/sidecar/src/arch/x86_64/init.rs
- openhcl/sidecar/src/arch/x86_64/mod.rs
- openhcl/sidecar/src/arch/x86_64/vp.rs
The register page is not valid until it has been mapped and the hypervisor says it's valid. However, the in-memory contents of the page before it is mapped could be non-zero, especially across a servicing operation. This can cause the VMM to think the register page contents are valid, causing register corruption.
Fix this by explicitly clearing the valid flag in the register page during sidecar startup.
Also zero a few more potentially stale structures to avoid potential bugs.
Cherry-pick of #1440
> sidecar: zero initialize unmapped register page (#1440)

- petri/logview/index.html
Apparently strings and numbers are different. Who knew?
> petri/logview: fix total column computation

- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- openvmm/membacking/src/mapping_manager/va_mapper.rs
- vm/vmcore/guestmem/src/lib.rs
Allow the memory backing to provide an error kind, which the virt backends will later use to determine whether to attempt emulation, inject a machine fault, resume the VP, or terminate the VM.
> guestmem: add error kind for access failures

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Update the kernel to the latest available version which contains this sidecar fixes:
https://github.com/microsoft/OHCL-Linux-Kernel/pull/82
https://github.com/microsoft/OHCL-Linux-Kernel/pull/83
> kernel: update main and dev kernels with fix for sidecar

- petri/logview/test.html
Correctly compute the number of seconds, to avoid showing more than
60 seconds.
> petri/logview: fix time output

- openhcl/underhill_core/src/nvme_manager.rs
- vm/devices/net/gdma/src/queues.rs
- vm/devices/net/mana_driver/src/gdma_driver.rs
- vm/devices/net/netvsp/src/lib.rs
Had to review all networking traces for a security review. In the process, found a number of tracing statements that did not align with our usual practices/style.
* Errors traced as %err instead of being cast to std::error::Error.
* Variables formatted into string text instead of being traced directly.
> Networking tracing improvements

- Cargo.lock
This change updates ms-tpm-20-ref-rs to a version that includes a TPM backing store size fix.
> Update ms-tpm-20-ref-rs package (#1452)

- openhcl/kmsg_defs/src/lib.rs
- openhcl/underhill_core/src/get_tracing/kmsg_stream.rs
- support/kmsg/src/lib.rs
Filter panic messages (printed to /dev/ttyprintk) out to a separate target and raise their effective trace level from verbose to critical.
Fixes #439
> underhill_core: trace panic messages appropriately

- openhcl/bootloader_fdt_parser/src/lib.rs
- openhcl/openhcl_attestation_protocol/src/igvm_attest/get.rs
- openhcl/openhcl_boot/src/dt.rs
- openhcl/openhcl_boot/src/host_params/dt.rs
- openhcl/openhcl_boot/src/host_params/mod.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/underhill_attestation/src/hardware_key_sealing.rs
- openhcl/underhill_attestation/src/igvm_attest/mod.rs
- openhcl/underhill_core/src/worker.rs
For issue 695: add runtime claims to the attestation that indicate whether confidential debug is enabled and includes any host-provided command line. Note (host_params/dt.rs) that the host-provided command line is currently passed down to OpenHCL only if the host is trusted.
> Add attestation for host command line and debug tracing

- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- openvmm/membacking/src/mapping_manager/va_mapper.rs
- vm/vmcore/guestmem/src/lib.rs
Allow the memory backing to provide an error kind, which the virt backends will later use to determine whether to attempt emulation, inject a machine fault, resume the VP, or terminate the VM.
Cherry-pick of #1430
> guestmem: add error kind for access failures (#1430)

- openhcl/kmsg_defs/src/lib.rs
- openhcl/underhill_core/src/get_tracing/kmsg_stream.rs
- support/kmsg/src/lib.rs
Filter panic messages (printed to /dev/ttyprintk) out to a separate target and raise their effective trace level from verbose to critical.
Cherry-pick of #1455
> underhill_core: trace panic messages appropriately (#1455)

- flowey/flowey_core/src/pipeline/artifact.rs
- openhcl/virt_mshv_vtl/src/cvm_cpuid/mod.rs
- vm/devices/pci/pci_core/src/cfg_space_emu.rs
- vm/hv1/hv1_structs/src/vtl_array.rs
- vm/vmcore/src/device_state.rs
- vm/vmcore/src/interrupt.rs
- vm/vmcore/src/isa_dma_channel.rs
- vm/vmcore/src/lib.rs
- vm/vmcore/src/line_interrupt.rs
- vm/vmcore/src/local_only.rs
- vm/vmcore/src/monitor.rs
- vm/vmcore/src/non_volatile_store.rs
- vm/vmcore/src/notify.rs
- vm/vmcore/src/reference_time.rs
- vm/vmcore/src/save_restore.rs
- vm/vmcore/src/slim_event.rs
- vm/vmcore/src/synic.rs
- vm/vmcore/src/vm_task.rs
- vm/vmcore/src/vmtime.rs
- vm/vmcore/src/vpci_msi.rs
Notably this removes the crate-level expect(unsafe_code) from vmcore, replacing it with much more narrowly scoped expects, and adding forbid(unsafe_code) to its other modules. This expect is needed due to our use of linkme inside the implementation of deriving SavedStateRoot. It is not needed on our derivations of this trait elsewhere, as the lint is suppressed when it comes from a macro invocation from a different crate. This is the only place we derive SavedStateRoot in vmcore itself.
> Repo: Clean up some lint attributes

- Guide/src/dev_guide/contrib/release.md
We have now entered ask mode for the 2505 release of OpenHCL.
> guide: update table for 2505 release to 'Ask Mode'

- flowey/flowey_lib_hvlite/src/_jobs/check_openvmm_hcl_size.rs
The current size check is failing in the release/2505 branch because it's currently comparing against main and the branches have diverged.
> ci: update size check to use release/2505 branch baseline

- openhcl/underhill_mem/src/init.rs
- openhcl/underhill_mem/src/lib.rs
- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- vm/hv1/hv1_emulator/src/hv.rs
- vm/vmcore/guestmem/fuzz/fuzz_guestmem.rs
- vm/vmcore/guestmem/src/lib.rs
When VTL 2 accesses VTL 0 memory on behalf of VTL 0, it needs to be able to check whether VTL 1 has restricted access to the memory. This change introduces tracking of VTL 1 permissions using bitmaps and adds some of the enforcement of these permissions.
Tested:
SNP +/- guest VSM boots
> cvm guest vsm: track vtl 1 permissions in bitmaps

- openhcl/underhill_mem/src/init.rs
- openhcl/underhill_mem/src/lib.rs
- openhcl/underhill_mem/src/mapping.rs
…wide (#1370)
In preparation for VTL 1 memory support for CVMs, make the shared/encrypted bitmap tracking available on a partition-level, rather than in the GuestMemoryMapping (which ends up being per-VTL). Also includes some refactoring to isolate out the bitmap logic so that it can be reused for vtl protection bitmaps.
Tested: SNP +/- guest vsm boots
> CVM Guest VSM: refactor the shared/encrypted bitmaps to be partition

- Cargo.lock
- clippy.toml
- vmm_core/virt_support_apic/Cargo.toml
- vmm_core/virt_support_apic/src/lib.rs
This removes functionality added in https://github.com/microsoft/openvmm/commit/7278a20daf243507baab1a912b1bd335a8c534d0 to avoid hitting https://github.com/tokio-rs/tracing/issues/2519. While the functionality is nice to have, it is not so important as to be worth potentially dropping events, and there is no performant way to implement it that can avoid this bug.
Then ban the tracing::enabled macro codebase-wide.
> virt_support_apic: Remove vector tracing filter

- Cargo.lock
This change updates ms-tpm-20-ref-rs to a version that includes a TPM backing store size fix.
> Update ms-tpm-20-ref-rs package (#1452) (#1453)

- openhcl/underhill_core/src/get_tracing/kmsg_stream.rs
https://github.com/tokio-rs/tracing/issues/2519 can cause the tracing
crate to mistakenly drop logs emitted after calling the `enabled!`
macro. Today we only call that macro in two places; this PR removes one
of them, the second is coming in another PR.
We currently are using our dynamic tracing filtering to filter out what
system-level messages get sent to the host, in addition to its normal
purposes. After much investigation and thought I've come to the
conclusion that there is no good way to work around this bug while
maintaining dynamic configuration. So instead just statically code these
levels. Realistically in terms of what these messages can help us
diagnose this is almost certainly fine.
Cherry-pick of #1462
> ohcl: Work around tracing bug by avoiding calling enabled (#1462)

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Changes flowey config for mu_msvm to use v25.1.3 release.
mu_msvm release here: https://github.com/microsoft/mu_msvm/releases/tag/v25.1.3
> deps: change mu_msvm version to v25.1.3 release

- vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs
- vm/devices/storage/disk_nvme/nvme_driver/src/registers.rs
With the emulated devices likely it will be 0x00000000 or 0xFFFFFFFF but we need to distinguish the cases for further diagnostics.
> Print full CSTS value when NVMe device failed to init

- Cargo.lock
- vm/devices/vmbus/vmbus_proxy/Cargo.toml
- vm/devices/vmbus/vmbus_proxy/src/lib.rs
- vm/devices/vmbus/vmbus_proxy/src/proxyioctl.rs
- vm/devices/vmbus/vmbus_proxy/src/vmbusioctl.rs
- vm/devices/vmbus/vmbus_server/src/channels.rs
- vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs
- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This change makes some improvements to how revoke (particularly while terminating) and restore are handled for proxy driver channels. These are mainly aimed at situations where the proxy driver may maintain state for some open channels in between save/restore, though they should improve the general reliability as well.
- When the proxy task is being cancelled, only "next action" ioctls are aborted/prevented from issuing. All other ioctls are still allowed, so that state changes are fully propagated to the driver until the server terminates. It's now also possible to wait for proxy task completion.
- When the proxy driver revokes a channel, that is now handled inline using `ChannelServerRequest::Revoke`, so we can wait for its completion and immediately release the channel to the driver.
- …
> vmbus_server: improve revoke and restore flows for proxy driver channels.

- openhcl/virt_mshv_vtl/src/lib.rs
This breaks petri log parsing and makes inspect harder to use.
> virt_mshv_vtl: don't use spaces in inspect keys

- openvmm/openvmm_entry/src/cli_args.rs
Fixes a bug in the openvmm cli where the argument without `file:` stripped was incorrectly used as the path.
> openvmm_entry: fix file disk openvmm cli

- vm/devices/firmware/firmware_uefi/src/lib.rs
- vm/devices/firmware/firmware_uefi/src/service/diagnostics.rs
- vm/devices/firmware/firmware_uefi/src/service/mod.rs
- vm/devices/firmware/uefi_specs/src/hyperv/advanced_logger.rs
- vm/devices/firmware/uefi_specs/src/hyperv/debug_level.rs
- vm/devices/firmware/uefi_specs/src/hyperv/mod.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
(This is a backport PR)
This PR adds EFI Diagnostics, which is a service used to parse UEFI diagnostics data from an in-memory buffer and send it to our tracing facilities.
The UEFI firmware will write the GPA of the advanced logger buffer to an Io port intercept called `SET_EFI_DIAGNOSTICS_GPA`.
The diagnostics service is responsible for reading guest memory at the specified GPA and parsing the data. This gets triggered when the UEFI firmware writes to an Io port intercept called
`PROCESS_EFI_DIAGNOSTICS`.
The `PROCESS_EFI_DIAGNOSTICS` UefiCommand gets triggered by the following conditions:
- UEFI encounters a failure (guest driven via `PROCESS_EFI_DIAGNOSTICS`)
- UEFI fails to boot any device (guest driven via `PROCESS_EFI_DIAGNOSTICS`)
- UEFI reaches exit boot services
The simplest way …
> firmware_uefi: Backport EFI Diagnostics

- flowey/flowey_cli/src/cli/regen.rs
In https://github.com/microsoft/openvmm/pull/1481 I removed the `flowey` build profile, because it was no longer necessary. This changed the output directory for cargo, since it was now using the normal debug profile. However I didn't catch this since I still had leftover binaries at the previous path, so there were no errors. Running a cargo clean then trying to run regen reveals the bug. Fix it by just updating to the right folder name.
> flowey: Fix regen break from changing build profile

- openhcl/underhill_mem/src/init.rs
- openhcl/underhill_mem/src/lib.rs
- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- vm/hv1/hv1_emulator/src/hv.rs
- vm/vmcore/guestmem/fuzz/fuzz_guestmem.rs
- vm/vmcore/guestmem/src/lib.rs
When VTL 2 accesses VTL 0 memory on behalf of VTL 0, it needs to be able to check whether VTL 1 has restricted access to the memory. This change introduces tracking of VTL 1 permissions using bitmaps and adds some of the enforcement of these permissions.
Tested:
SNP +/- guest VSM boots
TVM and TDX VMs also boot
> 1.6 cvm guest vsm: track vtl 1 permissions in bitmaps (#1457)

- vm/devices/tpm/src/lib.rs
- vm/devices/tpm/src/recover.rs
- vm/devices/tpm/src/tpm_helper.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
Mitigate TPM corruption due to previous VMs having a 16K TPM NVRAM reported as 32K, and commited bad state to the vTPM NVRAM.
This involves the following:
For every 16K TPM NVRAM, walk the dynamic section and truncate the last header if it points to data past the end.
Additionally, run the following mitigation steps for 16K NVRAM:
1. Check for a 4K bytes AK cert nv index. 1. This VM needs to be mitigated. 2. Undefine the 4K AK cert to save space. 3. Attempt to write a 1 byte mitigation platform marker, which can fail. 4. Attempt to write a just-sized platform ak cert.
2. Else, check for a mitigated marker or no platform cert 1. Log that this vm is mitigated, and if an ak cert is present or not
3. Else, check for an owner cert 1. Log that this VM is in the expected state
Related work …
> Merged PR 13114344: tpm: mitigate corruption due to corrupted TPM NVRAM blob

- vm/devices/tpm/src/lib.rs
- vm/devices/tpm/src/recover.rs
- vm/devices/tpm/src/tpm_helper.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
Mitigate TPM corruption due to previous VMs having a 16K TPM NVRAM reported as 32K, and commited bad state to the vTPM NVRAM.
This involves the following:
For every 16K TPM NVRAM, walk the dynamic section and truncate the last header if it points to data past the end.
Additionally, run the following mitigation steps for 16K NVRAM:
1. Check for a 4K bytes AK cert nv index. 1. This VM needs to be mitigated. 2. Undefine the 4K AK cert to save space. 3. Attempt to write a 1 byte mitigation platform marker, which can fail. 4. Attempt to write a just-sized platform ak cert.
2. Else, check for a mitigated marker or no platform cert 1. Log that this vm is mitigated, and if an ak cert is present or not
3. Else, check for an owner cert 1. Log that this VM is in the expected state
> tpm: mitigate corruption due to corrupted TPM NVRAM blob

- .cargo/config.toml
- Cargo.toml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_lib_hvlite/src/build_igvmfilegen.rs
- flowey/flowey_lib_hvlite/src/build_openhcl_igvm_from_recipe.rs
- flowey/flowey_lib_hvlite/src/build_xtask.rs
- flowey/flowey_lib_hvlite/src/run_cargo_build.rs
This makes sure we still get debug checks in igvmfilegen, but keeps it fast. Fixes #42.
> flowey: rename the xtask build profile to 'light', use it for igvmfilegen

- openhcl/underhill_mem/src/lib.rs
- openhcl/underhill_mem/src/mapping.rs
Uses RCU implementation to synchronize reads and writes of the VTL 1 permission bitmaps.
Tested:
SNP +/- guest vsm boots
> 1.6 CVM Guest VSM: synchronization around VTL permission bitmaps (#1483)

- openhcl/openhcl_dma_manager/src/lib.rs
- openhcl/underhill_core/src/worker.rs
This hypercall should not be used on hardware isolated platforms, as the hypervisor is untrusted. It shouldn't be used already today, but enforce it.
> openhcl/openhcl_dma_manager: disallow lower vtl hypercall on hardware isolated platforms

- openhcl/virt_mshv_vtl/src/lib.rs
Nobody calls it, and they should be going through uh_mem instead anyways. We probably need to explore unifying traits between virt and uh_mem in the future, but that can wait.
> virt_mshv_vtl: Remove impl of VtlMemoryProtection for UhPartition

- openhcl/underhill_mem/src/lib.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
Pretty straightforward wiring. The hypercall page is one of these registered pages, so nothing here is lost.
> virt_mshv_vtl: Fix TODO relating to translating gpas to overlay pages

- openhcl/virt_mshv_vtl/src/lib.rs
Nobody calls it, and they should be going through uh_mem instead anyways. We probably need to explore unifying traits between virt and uh_mem in the future, but that can wait.
Cherry-pick of #1535
> virt_mshv_vtl: Remove impl of VtlMemoryProtection for UhPartition (#1535)

- vm/loader/src/paravisor.rs
On TDX, the kernel uses the ACPI AP Mailbox protocol to start APs. However, the kernel assumes that all kernel ram is identity mapped, as the kernel will jump to a startup routine in any arbitrary kernel ram range.
For now to hotfix main, describe 3GB of memory identity mapped in the page table used by the mailbox assembly stub, so the kernel can start APs regardless of how large the initial memory size was. An upcoming change will instead have the bootshim modify the pagetable at runtime to guarantee all ranges reported in the E820 map to kernel as ram are mapped.
A future kernel change could remove this requirement entirely by making the kernel spec compliant, and only require that the reset vector page is identity mapped.
> openhcl/tdx: hotfix for ap mailbox startup kernel requirements

- openhcl/underhill_mem/src/lib.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/hv1/hv1_emulator/src/hv.rs
- vm/hv1/hv1_emulator/src/lib.rs
- vm/hv1/hv1_emulator/src/pages.rs
- vm/hv1/hv1_emulator/src/synic.rs
- vmm_core/virt_hvf/src/hypercall.rs
- vmm_core/virt_hvf/src/lib.rs
- vmm_core/virt_whp/src/lib.rs
- vmm_core/virt_whp/src/vp.rs
Move tracking of VTL protections for hv1 specific pages into hv1_emulator itself with a new ReadOnlyLockedPage helper struct. Then use this to ensure the hypercall code page and tsc reference page have proper protections and access checks. It also applies similar checks to the VP assist page and synic's simp and siefp pages.
Tested SNP with VSM still boots
cherry-pick of #1502 and https://github.com/microsoft/openvmm/pull/1566
> hv1_emulator: Wire up VTL protections for hypercall and tsc pages (#1502)

- openhcl/underhill_mem/src/lib.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
Pretty straightforward wiring. The hypercall page is one of these registered pages, so nothing here is lost.
Cherry-pick of #1552
> virt_mshv_vtl: Fix TODO relating to translating gpas to overlay pages (#1552)

- vm/devices/tpm/src/tpm_helper.rs
For now, the AKCert index needs to be owner-defined, not platform-defined. This change will fix up a mitigated vTPM appropriately.
> Fix up AKCert index attributes

- vm/devices/firmware/firmware_uefi/src/service/diagnostics.rs
This is a backport PR for EfiDiagnostics to suppress known logs that spam kmsg. Original PR is here: https://github.com/microsoft/openvmm/pull/1551
> firmware_uefi: suppress known warning logs backport

- openhcl/openhcl_dma_manager/src/lib.rs
- openhcl/underhill_core/src/worker.rs
This hypercall should not be used on hardware isolated platforms, as the hypervisor is untrusted. It shouldn't be used already today, but enforce it.
Cherry pick of (#1542)
> openhcl/openhcl_dma_manager: disallow lower vtl hypercall on hardware isolated platforms (#1542)

- Cargo.lock
- vm/devices/vmbus/vmbus_client/Cargo.toml
- vm/devices/vmbus/vmbus_client/src/driver.rs
- vm/devices/vmbus/vmbus_client/src/filter.rs
- vm/devices/vmbus/vmbus_client/src/lib.rs
- vm/devices/vmbus/vmbus_client/src/saved_state.rs
- vm/devices/vmbus/vmbus_ring/src/lib.rs
Add infrastructure to `vmbus_client` for writing vmbus channel drivers. This includes a filter, which can be used to allow some offers to go to `vmbus_relay` and others to be set aside, and infrastructure to allocate a ring buffer and open the channel.
> vmbus_client: add filter and channel driver support

- openhcl/underhill_mem/src/init.rs
- openhcl/underhill_mem/src/lib.rs
- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/devices/storage/scsi_buffers/src/lib.rs
- vm/vmcore/guestmem/fuzz/fuzz_guestmem.rs
- vm/vmcore/guestmem/src/lib.rs
Locked pages should not be able to have anything about them changed, that's what locking means. Implement this. This requires implementing new methods on GuestMemoryAccess to inform uh_mem when a page is locked and unlocked.
> uh_mem: Implement prevention of permissions changes on locked pages (#1531)

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/src/monitor.rs
This code is ugly, but we need to do per-backend things here despite being on the partition level, so it's necessary. We could maybe clean and split it up later somehow. Fixes https://github.com/microsoft/openvmm/issues/694
> virt_mshv_vtl: Wire up proper memory protections for the monitor page and enable it

- Cargo.lock
- openhcl/underhill_core/Cargo.toml
- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/Cargo.toml
- openvmm/hvlite_core/src/worker/dispatch.rs
- vm/devices/firmware/firmware_uefi/Cargo.toml
- vm/devices/firmware/firmware_uefi/src/lib.rs
- vm/devices/firmware/firmware_uefi/src/service/nvram/mod.rs
- vm/devices/firmware/firmware_uefi/src/service/nvram/spec_services/mod.rs
- vm/devices/firmware/firmware_uefi/src/service/nvram/spec_services/nvram_services_ext.rs
- vm/devices/firmware/hcl_compat_uefi_nvram_storage/Cargo.toml
- vm/devices/firmware/hcl_compat_uefi_nvram_storage/src/lib.rs
- vm/devices/firmware/uefi_nvram_storage/Cargo.toml
- vm/devices/firmware/uefi_nvram_storage/src/in_memory.rs
- vm/devices/firmware/uefi_nvram_storage/src/lib.rs
- vm/devices/firmware/uefi_specs/src/uefi/time.rs
- vm/vmgs/vmgstool/src/uefi_nvram.rs
- vmm_core/vmotherboard/src/base_chipset.rs
Implement save/restore for HclCompatNvram/NvramStorage/InMemoryNvram so that OpenHCL doesn't need to re-read from the VMGS file after a servicing or other save-restore operation. This will help avoid panics if the VMGS file is not accessible in certain VM teardown cases.
> uefi_nvram_storage: save restore nvram contents

- Guide/src/dev_guide/getting_started/linux.md
Some components depend on openssl, which won't build unless you've installed `pkg-config`. Mention that in the guide.
> guide: add pkg-config for linux users

- openhcl/underhill_mem/src/lib.rs
Currently it appears many VPs are registering the same GPNs for their synics. Support this.
> uh_mem: Handle duplicate overlay registration

- Cargo.lock
- openhcl/openhcl_attestation_protocol/Cargo.toml
- openhcl/openhcl_boot/Cargo.toml
- openhcl/openhcl_boot/src/arch/x86_64/tdx.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/underhill_core/src/worker.rs
- support/tdx_guest_device/Cargo.toml
- support/tdx_guest_device/src/ioctl.rs
- support/tdx_guest_device/src/lib.rs
- support/tdx_guest_device/src/protocol.rs
- support/tee_call/Cargo.toml
- vm/loader/igvmfilegen/Cargo.toml
- vm/loader/igvmfilegen/src/main.rs
- vm/x86/tdcall/Cargo.toml
- vm/x86/tdcall/src/lib.rs
If the debug bit is set in the VM's TDX attributes, the host can be trusted. This change gets the TD report in the boot shim and checks the debug bit. If it's set, parse the dynamic command line to allow enabling, e.g., confidential debugging.
> Set can_trust_host if TDX debug bit is set (#1501)

- openhcl/kmsg_defs/src/lib.rs
- openhcl/underhill_core/src/get_tracing/kmsg_stream.rs
- support/kmsg/src/lib.rs
Cherry-picks of #1455 and #1462. #1469 is not needed on this branch.
> Tracing fixes backport to 2411

- openhcl/underhill_core/src/get_tracing/json_layer.rs
- support/pal/pal_async/src/timer.rs
We already had a comment here indicating underflow is possible, we just weren't doing anything about it. We should do something about it. Fixes ICM 645583617
> uh_core: Avoid potential time underflow in tracing math

- openhcl/underhill_core/src/get_tracing/json_layer.rs
- support/pal/pal_async/src/timer.rs
We already had a comment here indicating underflow is possible, we just weren't doing anything about it. We should do something about it. Fixes ICM 645583617
Cherry-pick of #1607
> uh_core: Avoid potential time underflow in tracing math (#1607)

- Guide/src/dev_guide/dev_tools/hypestv.md
- hyperv/tools/hypestv/src/windows/mod.rs
- hyperv/tools/hypestv/src/windows/vm.rs
This is a quick implementation of reloading a running paravisor (e.g. issuing an openhcl servicing workflow). As the comment in the code indicates, the code could do much more to parse the `Msvm_ConcreteJob` that is returned (see `Trace-CimMethodExecution` in Set-OpenHCL-HyperV-VM.ps1)
> hypestv: support `paravisor reload`

- vm/devices/net/netvsp/src/lib.rs
- vm/devices/net/netvsp/src/test.rs
Netvsp driver does not accept an RNDIS header from Linux NetVSC, if that RNDIS header crosses a 4KB page boundary. handle_rndis_packet_message will return WorkerError::RndisMessageTooSmall. The error bubbles up out of process_ring_buffer causing netvsp to stop processing packets.
RNDIS headers crossing the page boundary has been a longstanding issue with the Linux NetVSC driver, but it has become more frequent recently with the Linux v6.14 kernel due to a recent upstream commit in the Linux networking subsystem that may have slightly affected the way SKBs are constructed.
Making the OpenHCL Netvsp driver more resilient (and more like the Windows Netvsp driver) by adding logic to log the error and complete the packet with a Failure status.
> netvsp: handle invalid rndis packets

- petri/logview/inspect.html
As a follow-on to #1620, fix the inspect parser to handle keys with spaces in the name.
The changes to `parseString` made it easier to debug issues in my regex changes.
> petri: logview: parse keys with spaces

- flowey/flowey_lib_hvlite/src/init_vmm_tests_env.rs
- vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs
- vmm_tests/petri_artifacts_vmm_test/src/lib.rs
I noticed "petri doesn't support this OpenHCL recipe:" printed to my console when running the vmm tests via xflowey. Looks like this was straightforward to hook up.
> vmm_tests: support aarch64 dev kernel

- openhcl/build_info/src/lib.rs
Adds `internal_scm_revision`, `internal_scm_branch`, and `openhcl_version`, which are filled out by the build pipeline and make it easier to identify what version of OpenHCL is running.
> build_info: add internal build info

- Guide/src/user_guide/openvmm/run.md
Fix a link from https://openvmm.dev/guide/user_guide/openvmm/run.html
to https://openvmm.dev/guide/reference/devices/firmware/pcat_bios.html
> guide: Fix broken link to PCAT BIOS

- vm/loader/manifests/openhcl-x64-cvm-dev.json
- vm/loader/manifests/openhcl-x64-cvm-release.json
PR #1501 modified igvmfilegen to no longer explicitly add OPENHCL_CONFIDENTIAL_DEBUG to the static command line if debug is enabled. This broke SNP: SNP cannot yet directly read the debug bit, and the vmbus relay depends on trusting the host for now. This change adds OPENHCL_CONFIDENTIAL_DEBUG to the static command line explicitly in the meantime (except for TDX, because it can directly read the debug bit).
> Add OPENHCL_CONFIDENTIAL_DEBUG to manifest

- openhcl/openhcl_attestation_protocol/src/igvm_attest/get.rs
- openhcl/underhill_attestation/src/hardware_key_sealing.rs
- openhcl/underhill_attestation/src/igvm_attest/mod.rs
- openhcl/underhill_core/src/worker.rs
Add an attestation claim indicating whether the vmbus relay is active for an isolated VM, which indicates that our vPCI filter will allow Azure-specific devices into the VM.
> Add attestation claim for Azure device filter

- vm/devices/vmbus/vmbus_ring/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/lib.rs
This change updates how "inspect" accesses channel ring buffers by only mapping the control page, and using `lockable_subrange` so that a `GuestMemory` implementation that doesn't have a full mapping has the opportunity to create a partial mapping.
This allows inspecting the ring buffers to work with alternative `GuestMemory` implementations used in Hyper-V.
The data included in the "inspect" output is unchanged; the only change is how it's retrieved.
> vmbus_server: allow inspect to access ring buffers without full memory mapping

- Guide/src/dev_guide/getting_started/cross_compile.md
- build_support/setup_windows_cross.sh
Installing `llvm-dev` will fix this:
```
warning: libsqlite3-sys@0.32.0:   File "/home/mattkur/openvmm/build_support/windows_cross/x86_64-clang-cl", line 206, in <module>
warning: libsqlite3-sys@0.32.0:     config = get_config(arch, tool, ignore_cache)
warning: libsqlite3-sys@0.32.0:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warning: libsqlite3-sys@0.32.0:   File "/home/mattkur/openvmm/build_support/windows_cross/x86_64-clang-cl", line 147, in get_config
warning: libsqlite3-sys@0.32.0:     raise Exception(
warning: libsqlite3-sys@0.32.0: Exception: tool 'clang-cl' not found, try installing it
error: failed to run custom build command for `libsqlite3-sys v0.32.0`
```
> guide: recommend one installs llvm-dev for cross compilation

- Cargo.lock
- openhcl/openhcl_attestation_protocol/Cargo.toml
- openhcl/openhcl_boot/Cargo.toml
- openhcl/openhcl_boot/src/arch/x86_64/tdx.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/underhill_core/src/worker.rs
- support/tdx_guest_device/Cargo.toml
- support/tdx_guest_device/src/ioctl.rs
- support/tdx_guest_device/src/lib.rs
- support/tdx_guest_device/src/protocol.rs
- support/tee_call/Cargo.toml
- vm/loader/igvmfilegen/Cargo.toml
- vm/loader/igvmfilegen/src/main.rs
- vm/loader/manifests/openhcl-x64-cvm-dev.json
- vm/loader/manifests/openhcl-x64-cvm-release.json
- vm/x86/tdcall/Cargo.toml
- vm/x86/tdcall/src/lib.rs
Release backport of PR #1501 and PR #1627.
If the debug bit is set in the VM's TDX attributes, the host can be trusted. This change gets the TD report in the boot shim and checks the debug bit. If it's set, parse the dynamic command line to allow enabling, e.g., confidential debugging.
Note that https://github.com/microsoft/OHCL-Linux-Kernel/pull/79 will need to be resolved before hardware debug can be disabled in the manifest.
> Set can_trust_host if TDX debug bit is set

- flowey/flowey_lib_common/src/install_rust.rs
Fixes:
```
=== ensure Rust is installed (flowey_lib_common::install_rust) ===
$ rustc -vV
rustc 1.88.0 (6b00bc388 2025-06-23)
binary: rustc
commit-hash: 6b00bc3880198600130e1cf62b8f8a93494488cc
commit-date: 2025-06-23
host: aarch64-unknown-linux-gnu
release: 1.88.0
LLVM version: 20.1.5
Error: missing required compoment: rust-src; to install: `rustup compoment add rust-src`
```
> flowey: fix typo checking for installed components

- flowey/flowey_cli/src/pipeline_resolver/ado_yaml.rs
- flowey/flowey_core/src/pipeline.rs
- flowey/schema_ado_yaml/src/lib.rs
This change introduces the ability to trigger pipelines when tags are created. While developing this change I also noticed that the current ADO CI triggers functionality did not generate correct yaml when an empty vector of trigger branches is specified, so a fix for that issue is included as well.
> flowey: add ADO trigger for tags

- openhcl/openhcl_attestation_protocol/src/igvm_attest/get.rs
- openhcl/underhill_attestation/src/hardware_key_sealing.rs
- openhcl/underhill_attestation/src/igvm_attest/mod.rs
- openhcl/underhill_core/src/worker.rs
Add an attestation claim indicating whether the vmbus relay is active for an isolated VM, which indicates that our vPCI filter will allow Azure-specific devices into the VM.
> Add attestation claim for Azure device filter (#1613)

- vm/devices/net/netvsp/src/lib.rs
- vm/devices/net/netvsp/src/test.rs
Netvsp driver does not accept an RNDIS header from Linux NetVSC, if that RNDIS header crosses a 4KB page boundary. handle_rndis_packet_message will return WorkerError::RndisMessageTooSmall. The error bubbles up out of process_ring_buffer causing netvsp to stop processing packets.
RNDIS headers crossing the page boundary has been a longstanding issue with the Linux NetVSC driver, but it has become more frequent recently with the Linux v6.14 kernel due to a recent upstream commit in the Linux networking subsystem that may have slightly affected the way SKBs are constructed.
Making the OpenHCL Netvsp driver more resilient (and more like the Windows Netvsp driver) by adding logic to log the error and complete the packet with a Failure status.
Cherry-pick of #1590
> netvsp: handle invalid rndis packets (#1590)

- openhcl/underhill_core/src/dispatch/mod.rs
Reduces the timeout for flushing logs during servicing to reduce blackout time if there is some issue with flushing the logs.
> openhcl servicing: decrease flush logs timeout (#1385)

- vm/devices/net/mana_driver/src/mana.rs
- vm/devices/net/netvsp/src/lib.rs
Currently, it's difficult to ascertain where time is spent on mana during servicing as we don't have instrumentation around some vital parts of servicing. This PR adds some instrumentation to inform us where time is being spent so that we can prioritize keepalive in the right places.
Cherry-pick of #1584
> netvsp, mana_driver: add instrumentation around parts of mana servicing (#1584)

- Cargo.lock
- Cargo.toml
- openvmm/openvmm_entry/src/cli_args.rs
- openvmm/openvmm_entry/src/lib.rs
- openvmm/openvmm_resources/Cargo.toml
- openvmm/openvmm_resources/src/lib.rs
Adding delay disk as an option for openvmm upon entry. This should make it such that the disk_delay crate is actually being used in the openvmm project (And not just in internal microsoft testing). Fixed #1680
> openvmm_entry: Adding delay disk as a cli args option for openvmm disks

- Cargo.lock
- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- vm/devices/firmware/firmware_uefi/Cargo.toml
- vm/devices/firmware/firmware_uefi/src/lib.rs
- vm/devices/firmware/firmware_uefi/src/service/diagnostics.rs
- vm/devices/watchdog/watchdog_core/src/platform.rs
Today, we do not issue an NMI when ARM64 VMs encounter a UEFI watchdog timeout. This prevents UEFI from going through the `ReportCrash()` path, failing to issue the signal to process UEFI diagnostics.
This PR solves this by forcing EfiDiagnostics to flush when learning about a watchdog timeout.
Additionally, if you use `uhdiag` to inspect the `UefiDevice`, this will also trigger EfiDiagnostics to flush.
For the watchdog path, here is an example from an OpenHCL build of this with a private UEFI that forces RngDxe to stall for > 2 minutes:
```
[121.383009] watchdog_core: ERROR  Encountered a watchdog timeout name="uefi-watchdog"
[121.566205] underhill_core::livedump: INFO  livedump succeeded
[121.566769] firmware_uefi::service::diagnostics: INFO  EFI log entry debug_level=LOAD+ERROR …
```
> firmware_uefi: Flush EfiDiagnostics on Watchdog Timeout and Inspect

- vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs
- vm/devices/storage/disk_nvme/nvme_driver/src/queue_pair.rs
Adding the qid field to the assert output during failures (Mismatched completion ids). Fixes: #1685
> nvme_driver: Added the qid field to the pending commands

- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This code got refactored a dozen times, and at some point this check ended up inverted. Offloading can be enabled when there is no pending TLB flush.
> Fix TDX TLB flush offload enabled inversion

- flowey/flowey_hvlite/src/pipelines/vmm_tests.rs
- flowey/flowey_lib_hvlite/src/_jobs/local_build_and_run_nextest_vmm_tests.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/lib.rs
- petri/src/openhcl_diag.rs
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/hyperv/powershell.rs
- petri/src/vm/hyperv/vm.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/construct.rs
- petri/src/vm/openvmm/mod.rs
- petri/src/vm/openvmm/modify.rs
- petri/src/vm/openvmm/runtime.rs
- petri/src/vm/openvmm/start.rs
- tmk/tmk_tests/src/lib.rs
- vm/devices/get/get_resources/src/lib.rs
- vm/devices/get/guest_emulation_device/src/resolver.rs
- vmm_tests/vmm_test_macros/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/openhcl_servicing.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
- vmm_tests/vmm_tests/tests/tests/x86_64_exclusive.rs
Refactors petri to use generics instead of Box for backends. This should reduce duplicate code going forward and makes it possible to use generics in backend-agnostic configuration functions.
> petri: use generics instead of Box for backends

- vm/devices/get/get_protocol/src/lib.rs
Even though there's only the one flag, it's offset by one bit. This allows these calls to succeed now.
> Fix CreateRamGpaRangeFlags to match host definition

- Cargo.lock
- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- vm/devices/firmware/firmware_uefi/Cargo.toml
- vm/devices/firmware/firmware_uefi/src/lib.rs
- vm/devices/firmware/firmware_uefi/src/service/diagnostics.rs
- vm/devices/watchdog/watchdog_core/src/lib.rs
- vmm_core/vmotherboard/src/base_chipset.rs
This PR aims to take a different approach to flushing EfiDiagnostics on Watchdog timeout. 
- Removes Arc<Mutex<>>, which was originally used to share the diagnostics service between UefiDevice and its WatchdogPlatform
- Creates a mesh::channel before creating the UefiDevice. The watchdog_callback that gets added to the UefiDevice has its `on_timeout` method modified to invoke the sender to send a notification.
- The mesh::receiver end gets sent down the UefiDevice, and it is used in `poll_device()` to freely respond to watchdog events
> firmware_uefi: EfiDiagnostics switch to polling instead of Arc<Mutex<>>

- vm/devices/get/get_protocol/src/lib.rs
Even though there's only the one flag, it's offset by one bit. This allows these calls to succeed now.
Clean cherry-pick of #1700
> Fix CreateRamGpaRangeFlags to match host definition (#1700)

- hyperv/tools/hypestv/src/windows/vm.rs
- openhcl/ohcldiag-dev/src/main.rs
- petri/src/tracing.rs
- support/kmsg/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
We've seen a crash here in the wild, but haven't yet figured out what exactly is failing to parse. Add some more logging so we can hopefully get this if it happens again.
> kmsg: Log the raw buffer if we fail to parse

- hyperv/tools/hypestv/src/windows/vm.rs
- openhcl/ohcldiag-dev/src/main.rs
- petri/src/tracing.rs
- support/kmsg/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
We've seen a crash here in the wild, but haven't yet figured out what exactly is failing to parse. Add some more logging so we can hopefully get this if it happens again.
Cherry-pick of #1704
> kmsg: Log the raw buffer if we fail to parse (#1704)

- openhcl/virt_mshv_vtl/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
MNF support does not work on CVM. Disable it for now to unbreak scenarios such as MANA nic relay, while we root cause the actual issue. Tracked by #1711. 
Onboard a test that forces MNF for TDX and other flavors. Note that this test is not complete, as we do need to verify within the guest that MNF is actually present. But at a minimum, we can at least see that toggling this property does not break the guest. Tracked by #1713.
> openhcl/CVM: disable mnf support

- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- vm/devices/firmware/hcl_compat_uefi_nvram_storage/src/lib.rs
- vm/vmgs/vmgstool/src/uefi_nvram.rs
while staging my backport, I realized HclCompatNvram::new no longer needs to be async.
> hcl_compat_uefi_nvram: remove unnecessary async

- openvmm/hvlite_defs/src/config.rs
- vmm_core/src/device_builder.rs
Found when debugging a test (I was confused where duplicate ID 0's were coming from).
> vmm_core: slightly more info on how pci device IDs are constructed

- openhcl/underhill_crash/src/lib.rs
This PR simply adds the openhcl_version, pulled from the `OPENHCL_VERSION` environment variable, into our crash trace messages
> underhill_crash: Add openhcl_version to underhill crash traces

- vm/devices/firmware/firmware_uefi/src/lib.rs
This PR removes having `inspect` on the UefiDevice trigger EfiDiagnostics to write to kmsg, as that is causing performance issues currently.
> firmware_uefi: Remove functionality to have inspect trigger EfiDiagnostics

- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/src/monitor.rs
We've discovered that the current design for monitor pages on CVMs is incompatible with OpenHCL as it relies on assigning to a shared page, which we can't support. Remove all the code added for this, as it adds complexity and is no longer needed. Vmbus will be going down a different path in the future.
> Revert "virt_mshv_vtl: Wire up proper memory protections for the monitor page and enable it (#1541)"

- Cargo.lock
- support/pal/src/windows.rs
- vm/whp/Cargo.toml
- vm/whp/src/api.rs
- vm/whp/src/lib.rs
This change addresses bugs in virt_whp's `delayload` macro (it doesn't try to load the module) by merging it with the shared `pal::delayload`.
`pal::delayload` was missing support for `is_supported` checks and per-function `[#cfg(...)]` attributes, both of which WHP was using, so those have been ported over.
> virt_whp/pal: merge whp delayload into pal::delayload

- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
Needs #1722 to pass, so leaving as draft for now.
The motivation for this test case is to chase down some performance issues across OpenHCL servicing.
> vmm_tests: craft a servicing test with 8 nvme devices

- openhcl/underhill_crash/src/lib.rs
This is a backport from: https://github.com/microsoft/openvmm/pull/1716
This PR simply adds the openhcl_version, pulled from the `OPENHCL_VERSION` environment variable, into our crash trace messages
> underhill_crash: Backport Add openhcl_version to underhill crash traces

- openhcl/underhill_crash/src/lib.rs
This is a backport from: https://github.com/microsoft/openvmm/pull/1716
This PR simply adds the openhcl_version, pulled from the OPENHCL_VERSION environment variable, into our crash trace messages
> underhill_crash: Backport Add openhcl_version to underhill crash traces (2411)

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr-release.yaml
- .github/workflows/openvmm-pr.yaml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_hvlite/src/pipelines/vmm_tests.rs
- flowey/flowey_hvlite/src/pipelines_shared/gh_pools.rs
- flowey/flowey_lib_hvlite/src/_jobs/local_build_and_run_nextest_vmm_tests.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
Attempt to run SNP tests now that we have one machine. Wait for 2 machines online to merge.
> ci: enable snp tests

- vm/devices/pci/pci_bus/src/lib.rs
Otherwise it's a lot harder to figure out why things are failing.
Cherry-pick of #1729.
> PCI: Also log the offset on access failures (#1729)

- openhcl/underhill_core/src/lib.rs
- openhcl/underhill_core/src/nvme_manager.rs
- openhcl/underhill_core/src/options.rs
- openhcl/underhill_core/src/worker.rs
The default `vfio` device behavior is to issue a function level reset when attaching or detaching devices. It does so because the device is in an unknown or untrusted state. However, within the context of a trusted virtualization stack, OpenHCL can reasonably trust the state and behavior of the device. So, optimize performance by removing these function level resets for nvme devices. This follows the same model as already exists for MANA devices.
The `nvme_driver` already shuts down the device (see `NvmeDriver::reset()`) and waits for the device to become disabled. A well behaved nvme device will not issue DMA after this point. That same device should tolerate a graceful start without an FLR.
Pending work before this PR is ready to commit:
> nvme_driver: don't flr nvme devices

- flowey/schema_ado_yaml/src/lib.rs
This resolves an issue with downlevel deserialization code that isn't correctly handling this field not being present.
> flowey: remove skip_serializing_if decoration on depends_on

- vm/devices/chipset_legacy/src/piix4_uhci.rs
Our generation 1 chipset includes a heavily stubbed out usb chip that doesn't actually support anything. Quiet warnings on reads/writes to unknown offsets in it, since it's not meant to do anything functional, and the bios touches it unconditionally. Removes some gen 1 log noise.
> gen1: Quiet pci warnings to our usb stub device

- vm/devices/storage/ide/src/lib.rs
- vmm_core/vmotherboard/src/base_chipset.rs
Most guests like to read the entire Header00 range of their PCI devices, but IDE didn't implement those. Just return 0 to quiet the warnings.
> IDE: Dont warn on reads from undefined cfg space offsets

- .config/nextest.toml
Hopefully this resolves some test flakiness/raciness I've been seeing lately.
> repo: Configure "heavy" tests as heavy with nextest

- vm/devices/pci/vpci/src/device.rs
Fixes #1721 . Namely: unless `vpci` clears config space mappings upon vmbus channel close, there is a chance of conflicts upon a future boot. This also matches the Hyper-V host behavior.
Tested via a new, in-development vmm test. Will link here when I publish that test.
> vpci: clear config space mappings upon vmbus channel disconnect (#1722)

- openhcl/underhill_core/src/worker.rs
As the newly added comment mentions, current host code only looks at the very first RAM block when determining where to locate PCAT mappings. We need to do the same, or else we get errors back when we try to adjust them. Fixes VGA (and probably other devices) on gen 1 VMs with multiple NUMA nodes.
> gen1: Only consider the first ram block when locating PCAT mappings

- petri/src/vm/hyperv/mod.rs
- petri/src/vm/hyperv/vm.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/runtime.rs
- petri/src/vm/openvmm/start.rs
- vmm_tests/petri_artifacts_vmm_test/src/lib.rs
Always wait an extra second after the shutdown IC reports OK to hopefully get around some occasional flakiness where the shutdown IC hangs if the request is sent too early. This seems to happen most often with "heavy" tests: [Example](https://openvmm.dev/test-results/test.html?run=16451062380&job=x64-windows-intel-tdx-vmm-tests-logs&test=multiarch__hyperv_openhcl_uefi_x64_windows_datacenter_core_2025_x64_tdx_boot_no_agent_heavy)
This change also moves the handling of the delay, including guest quirks, into the generic `PetriVm` instead of being backend-specific. Backends could still add extra time via an additional wait in `wait_for_enlightened_shutdown_ready` if necessary.
> petri: extra wait for shutdown ic, move to generic

- openhcl/underhill_core/src/lib.rs
- openhcl/underhill_core/src/nvme_manager.rs
- openhcl/underhill_core/src/options.rs
- openhcl/underhill_core/src/worker.rs
The default `vfio` device behavior is to issue a function level reset when attaching or detaching devices. It does so because the device is in an unknown or untrusted state. However, within the context of a trusted virtualization stack, OpenHCL can reasonably trust the state and behavior of the device. So, optimize performance by removing these function level resets for nvme devices. This follows the same model as already exists for MANA devices.
The `nvme_driver` already shuts down the device (see `NvmeDriver::reset()`) and waits for the device to become disabled. A well behaved nvme device will not issue DMA after this point. That same device should tolerate a graceful start without an FLR.
Pending work before this PR is ready to commit:
> nvme_driver: don't flr nvme devices (#1714)

- repo_support/relabel_backported.py
Minor update to the backport relabeling script to include the release the change was backported to. This will be useful for PRs that are backported to multiple release branches.
> relabel_backported: add release in PR comment

- vm/devices/storage/disk_nvme/nvme_driver/fuzz/fuzz_nvme_driver.rs
Using the first half of the guest memory, as was done previously, overlaps with the memory space allocated to the emulated NVMe device.
> fuzz_nvme_driver: Use payload memory for transfer buffer

- Cargo.lock
- openhcl/underhill_mem/Cargo.toml
- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/guestmem/src/lib.rs
- vm/x86/x86defs/src/snp.rs
This fixes some crashes within OpenHCL when memory protections are violated in SNP that were already handled properly in TDX. Also updates the logic to send memory intercepts on VTL 1 permissions violations.
Fixes #689, and some OS repo tests
> CVM: Move logic around memory faults from TDX to be shared with SNP, send memory intercepts

- Cargo.lock
- openhcl/underhill_mem/Cargo.toml
- openhcl/underhill_mem/src/mapping.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- vm/vmcore/guestmem/src/lib.rs
- vm/x86/x86defs/src/snp.rs
This fixes some crashes within OpenHCL when memory protections are violated in SNP that were already handled properly in TDX. Also updates the logic to send memory intercepts on VTL 1 permissions violations.
Fixes #689, and some OS repo tests
Cherry-pick of #1764
> CVM: Move logic around memory faults from TDX to be shared with SNP, send memory intercepts (#1764)

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Update the Linux kernel to the latest available version with upstream stable patches. See https://github.com/microsoft/OHCL-Linux-Kernel/pull/91 for more details.
The dev and main kernels are currently identical.
> kernel: update main and dev kernel to 6.12.36

- vm/loader/manifests/openhcl-aarch64-dev.json
The default size is too small and does not actually boot and we instead get an OOM error. Increase it to match the x64 one.
> openhcl/loader: increase aarch64 dev manifest default memory size

- petri/guest-bootstrap/user-data-no-agent
- petri/petri-tool/src/main.rs
- petri/src/disk_image.rs
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/start.rs
- tmk/tmk_tests/src/lib.rs
- vmm_tests/vmm_test_macros/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
This change makes using pipette for vtl0 optional, which allows us to use the unrelated parts of cloudinit to speed up boot on Ubuntu 24.04.
> petri: use cloudinit even if not using pipette

- support/inspect/src/lib.rs
- support/inspect_derive/src/lib.rs
I figure there's a good chance we don't actually want to take this, and instead continue requiring devs to give proper names to their fields, but I went down this rabbit hole already so I figured I might as well push it.
This change was prompted by a rust-analyzer bug. rust-analyzer today passes input streams to derive macros **after** expanding any attribute macros inside them, instead of correctly passing the attribute macro into the derive macro (I couldn't find an issue link, but a rust-analzyer dev in discord promised me this is known). When combining an Inspect derivation and a bitfield struct this results in the Inspect derive seeing the single field tuple struct created by the bitfield macro, instead of the pre-transformed list of fields. This causes rust-analyzer to emit …
> inspect_derive: Support tuple structs

- vmm_core/vmotherboard/src/base_chipset.rs
I originally made this change to make it a little clearer where the ide device was, but apparently this device label is being used as part of save state, so this change broke servicing. Just set the name back.
> vmotherboard: Fix restore errors from pci rename

- vmm_core/vmotherboard/src/base_chipset.rs
I originally made this change to make it a little clearer where the ide device was, but apparently this device label is being used as part of save state, so this change broke servicing. Just set the name back.
Cherry-pick of #1786
> vmotherboard: Fix restore errors from pci rename (#1786)

- petri/src/vm/openvmm/runtime.rs
Only try launch pipette for linux direct on reboot if pipette is included in the CI data disk.
Fix bug introduced in https://github.com/microsoft/openvmm/commit/2e8760d1a970b04ec6b98ee120063d9f76b41ed7, which caused linux direct reboot tests to fail intermittently.
> petri: don't try to start pipette on reboot if it doesn't exist

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Update nextest to the latest release. This fixes some bugs it seems in nextest around detecting leaks on windows, which was causing test failures.
Cherry pick of #1790.
Fixes #1782
> deps: update nextest to latest 0.9.101 (#1790)

- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- openvmm/hvlite_defs/src/config.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/vm/openvmm/construct.rs
- tmk/tmk_vmm/src/run.rs
- vm/acpi_spec/src/madt.rs
- vm/vmcore/vm_topology/src/processor/aarch64.rs
- vmm_core/src/acpi_builder.rs
- vmm_tests/vmm_tests/tests/tests/aarch64_exclusive.rs
- vmm_tests/vmm_tests/tests/tests/main.rs
On AArch64, the Performance Monitor Unit (PMU) is supposed to be
supported by every platform. Add this information to the vm's topology,
and correctly report a configured value in the MADT via the GICC
structure. Onboard a test to verify that Linux sees the correct
interrupts.
Hyper-V and WHP support a hardcoded value of 0x17, so for now hardcode
that value on those platforms. A follow up change will correctly report
this value via a `pmu` device tree node, but take this more minimal
change to backport to the release/2505 branch.
Although macOS also supports this interrupt with the same value of 0x17,
enabling that did not cause Linux to work as expected, so more
investigation there is needed.
This fixes xperf on Windows and perf on Linux which rely on this being
present.
#1775 
Backport …
> vmcore/vm_topology: support pmu interrupt on aarch64 (#1776)

- openvmm/openvmm_entry/src/cli_args.rs
Move the handling of `VMGS_DEFAULT` size into `parse_memory` so that it works with memory disks in addition to files.
> openvmm_entry: allow mem disk of VMGS default size

- openvmm/hvlite_core/src/worker/dispatch.rs
- openvmm/hvlite_defs/src/config.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/vm/openvmm/construct.rs
- vmm_core/virt_whp/src/lib.rs
Remove the hardcoded PMU GSIV value, and instead of `None` add a platform enum type. 
#1775
> openvmm/aarch64: query pmu value from platform

- openhcl/virt_mshv_vtl/src/processor/mod.rs
Probably got accidentally added during a merge conflict.
> Remove a duplicated trace

- vm/devices/vmbus/vmbus_server/src/channels.rs
This change fixes an issue where, if all channels are already reset when a disconnect happens, the server would not invoke `Notifier::modify_connection`. This means that the state such as the interrupt page and monitor pages is not reset, and in the case of OpenHCL the relay is not notified of the disconnect (which can leave host state intact, including monitor pages if MNF is handled by the host).
This caused an issue where Linux would occasionally crash during resume from hibernate. When resuming, Linux makes two connections, first to read the memory image, and then to resume normal operations, both using MNF. When the first connection unloads, the overlay pages for the monitor pages were not removed until the reconnect, leading to memory corruption when Linux proceeds to use these …
> vmbus_server: always notify that the connection is modified when disconnecting

- openhcl/bootloader_fdt_parser/src/lib.rs
- openhcl/host_fdt_parser/src/lib.rs
- openhcl/openhcl_boot/src/dt.rs
- openhcl/openhcl_boot/src/host_params/dt.rs
- openhcl/openhcl_boot/src/host_params/mod.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/vm_loaders/linux.rs
- vmm_tests/vmm_tests/tests/tests/aarch64_exclusive.rs
Report the PMU via device tree, and parse it from device tree in OpenHCL in both `openhcl_boot` and usermode. 
Note that the kernel reports some sampling events not supported error in OpenHCL:
```
[kmsg]: [0.011789] armv8-pmu pmu: hw perfevents: no irqs for PMU, sampling events not supported
[kmsg]: [0.011916] hw perfevents: enabled with armv8_pmuv3 PMU driver, 6 (0,8000001f) counters available
```
Tracked by #1808. Due to openhcl-diag shell not working on AArch64, it's possible `perf` doesn't actually work. However, VTL0 sees the correct value being described via ACPI. 
Fixes #1775.
> openvmm,openhcl: describe and parse the pmu via dt

- support/inspect/src/lib.rs
- vm/devices/storage/disk_delay/src/lib.rs
- vm/vmcore/src/vmtime.rs
Adds inspect support for the Duration type. Prints out with the format 1234.567800000s (Nanoseconds precision).
Fixes #1784
> inspect: Adding Inspect support for the Duration type

- support/mesh/mesh_derive/src/lib.rs
- support/pal/src/windows.rs
- vm/devices/firmware/firmware_uefi/src/service/nvram/spec_services/nvram_services_ext.rs
- vm/devices/support/fs/lxutil/src/windows/mod.rs
- vm/devices/user_driver_emulated_mock/src/lib.rs
- vm/devices/vga/src/emu.rs
- vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
Pretty small cleanups from this version, though there is one new warning in mesh not fixed in this PR that will take some thought to fix.
> Fix lints for Rust 1.89

- vm/devices/net/mana_driver/src/queues.rs
- vm/devices/net/net_mana/src/lib.rs
Fixing a todo to improve the tracing when net_mana sees CQE_TX_GDMA_ERR and CQE_TX_INVALID_OOB. Both are results of incorrectly formatted packets. Hopefully logging WQE header parameters and s_oob parameters will help us determine why these packets are being rejected.
Example output of a small packet with an invalid OOB:
```
[114.615866] net_mana: ERROR  tx completion error cqe_type=0x23 vendor_err=0xe00001 wq_number=0x1 tx_data_offset=0x0 tx_sgl_offset=0x0 tx_wqe_offset=0x2c done_length=0x2000 posted_tx_len=0x1
[114.616286] net_mana: ERROR  tx wqe header last_vbytes=0x0 num_sgl_entries=0x1 inline_client_oob_size=0x2 client_oob_in_sgl=false reserved=0x0 gd_client_unit_data=0x0 reserved2=false sgl_direct=false
[114.616522] net_mana: ERROR  tx s_oob pkt_fmt=0x0 is_outer_ipv4=true …
```
> net_mana: adding tracing of the WQE on GDMA and OOB errors

- openhcl/underhill_core/src/worker.rs
- vm/vmcore/vm_topology/src/memory.rs
This should help us catch bad memory setups earlier.
Note: we're still debugging what causes failures here, but the sooner we can catch them the better.
Also includes some additional tracing.
> uh_core: Also memory self-test ends of ranges

- vm/acpi_spec/src/madt.rs
- vmm_core/src/acpi_builder.rs
Add LINT1 as the local NMI error source in the MADT.
> Amd64 Trusted VMs with Open HCL fail to inject an NMI

- openhcl/underhill_attestation/src/key_protector.rs
- openhcl/underhill_attestation/src/lib.rs
There is a vulnerability in OpenHCL's VMGS key-rolling code that allows the host to cause the VMGS to be encrypted with a host-controlled key. unwrap_and_rotate_keys now returns a pair of egress keys: one that may have been used to previously encrypt the VMGS and can only be used for that purpose; and a second key, always derived anew, that can safely be used to re-encrypt the VMGS.
CVE-2025-53781
> Remove VMGS host tampering vulnerability

- vm/devices/vmbus/vmbus_ring/src/gparange.rs
`MultiPagedRangeBuf::subrange` previously was not respecting cur_offset in the case where try_subrange returned None. Replaced that chunk with cleaner math.
`parse` was previously not validating that the given byte_offset was within range. Later code would use this value unmasked, resulting in bad behavior. Fix this by ensuring that the value fits within the mask.
Added unit tests for both these cases.
Both bugs found by GPT-5.
> vmbus_ring: Fix two small math oversights

- openhcl/underhill_mem/src/init.rs
- vmm_core/virt_whp/src/hypercalls.rs
- vmm_core/virt_whp/src/memory.rs
On VBS, the hypervisor requires pages to be accepted first before they can be transitioned to the shared state. 
Fix virt_whp's implementation to enforce this as well.
> openhcl/vbs: correctly accept pages before changing visibility for shared pool

- openhcl/openhcl_boot/src/dt.rs
- openhcl/openhcl_boot/src/host_params/shim_params.rs
This bound only exists in `openhcl_boot`, remove it.
> openhcl_boot: remove target arch on isolation type

- Cargo.lock
- vm/devices/tpm/Cargo.toml
- vm/devices/tpm/src/lib.rs
- vm/devices/tpm/src/tpm20proto.rs
- vm/devices/tpm/src/tpm_helper.rs
A malicious admin can evict the AK from their VM's vTPM and replace it with their own key. At boot, Azure will load that key from the VMGS and then sign an AKCert with that key, allowing the admin to spoof KeyGuard and CVM attestation.
CVM: This change mirrors changes in the legacy HCL: Regenerate the AK at boot from the TPM seeds, instead of loading it from VMGS. This ensures that the original AKCert is always present in the vTPM.
TVM: OpenHCL currently cannot regenerate the AK for a TVM, because the original AK (provisioned by the vtpmservice) contains an auth policy; OpenHCL does not implement that policy creation. As an alternative, when OpenHCL boots, it will check the attributes on the AK that it loads from VMGS. If the attributes are wrong (indicating a possibly malicious key), it …
> [MSRC 97247] Fix Trust Fall MSRC

- vm/loader/manifests/openhcl-x64-cvm-release.json
This release is almost ready, time to disable debug support in the builds that will end up in prod.
> Disable debug mode for TDX release builds

- Cargo.lock
- vm/devices/tpm/Cargo.toml
- vm/devices/tpm/src/lib.rs
- vm/devices/tpm/src/tpm20proto.rs
- vm/devices/tpm/src/tpm_helper.rs
A malicious admin can evict the AK from their VM's vTPM and replace it with their own key. At boot, Azure will load that key from the VMGS and then sign an AKCert with that key, allowing the admin to spoof KeyGuard and CVM attestation.
CVM: This change mirrors changes in the legacy HCL: Regenerate the AK at boot from the TPM seeds, instead of loading it from VMGS. This ensures that the original AKCert is always present in the vTPM.
TVM: OpenHCL currently cannot regenerate the AK for a TVM, because the original AK (provisioned by the vtpmservice) contains an auth policy; OpenHCL does not implement that policy creation. As an alternative, when OpenHCL boots, it will check the attributes on the AK that it loads from VMGS. If the attributes are wrong (indicating a possibly malicious key), it …
> [MSRC 97247] Fix Trust Fall MSRC (#1849)

- support/mesh/mesh_protobuf/src/protofile/mod.rs
- support/mesh/mesh_protobuf/src/protofile/writer.rs
As a new warning in Rust 1.89 points out, comparisons of function pointers are unreliable (https://doc.rust-lang.org/nightly/core/ptr/fn.fn_addr_eq.html). The derive of PartialEq on a type containing a function pointer will produce such a comparison, triggering this warning. Instead of deriving the trait and inserting MessageDescriptors into a HashMap, just use their package and name as a deduplication key, under the assumption that nobody would declare two different types with the same package and name.
> mesh_protobuf: Only deduplicate descriptors by package and name

- openhcl/underhill_mem/src/lib.rs
- openhcl/virt_mshv_vtl/src/lib.rs
- openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
When we are sharing a page we remove all VTL 0 permissions to that page. Later on, when we re-private the page, we were failing to reset these permissions, which led to failures when the guest tried to use pages it should have had access to. This code is a bit confusing due to conflating private/shared with VTL 1 access permissions. Add a bunch of comments, and fix the reset.
Cherry-pick of #1891
> uh_mem: Properly reset permissions when unsharing pages (#1891)

- openhcl/openhcl_boot/src/boot_logger.rs
- openhcl/openhcl_boot/src/cmdline.rs
- openhcl/openhcl_boot/src/main.rs
There's no reason not to have it. This also removes the configuration of logging and the ability to disable it, since we still only have the one output backend.
> ohcl_boot: Always enable logging ASAP

- openhcl/underhill_core/src/dispatch/mod.rs
- openhcl/underhill_core/src/worker.rs
Introduce separate functions instead of a rollback parameter so it is easier to parse.
> shutdown_relay: make the hibernate/rollback code easier to read

- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
Skip this test on unsupported hosts, as otherwise it may also spuriously fail.
> vmm_tests: skip nvme servicing test on unsupported hosts

- Cargo.lock
- Cargo.toml
- flowey/flowey_lib_hvlite/src/install_vmm_tests_deps.rs
- petri/Cargo.toml
- petri/src/tracing.rs
- petri/src/vm/hyperv/hvc.rs
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/hyperv/powershell.rs
- petri/src/vm/hyperv/vm.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/construct.rs
- petri/src/vm/openvmm/runtime.rs
- petri/src/vm/openvmm/start.rs
- tmk/tmk_tests/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/ttrpc.rs
Using COM3 instead of diag_client allows us to get OpenHCL logs if it crashes early in boot. Currently this only works on our TDX and SNP runners, since our nested runners have a build of windows that is too old and additional com ports are not yet supported on ARM. To make this work, the powershell and hvc commands needed to be run in a separate process (using the `unblock` function) to avoid blocking the process doing the logging.
> petri: unblock commands and use com3 for hyper-v kmsg logs when possible

- vm/devices/hyperv_ic_guest/src/lib.rs
- vm/devices/hyperv_ic_guest/src/shutdown.rs
- vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
These crates compile perfectly fine on Windows, might as well allow them, even if they're only used by OpenHCL currently.
> Remove a few unneeded linux-only cfgs

- openhcl/openhcl_boot/src/arch/x86_64/tdx.rs
- openhcl/openhcl_boot/src/main.rs
- vm/loader/manifests/openhcl-x64-cvm-dev.json
- vm/loader/manifests/uefi-x64.json
As discussed in today's meeting, the hw debug bit on TDX has unfortunate side effects to being set. Stop using it entirely.
> ohcl_boot: Do not check the hw debug bit for OHCL debug configuration

- vm/devices/storage/nvme_resources/src/fault.rs
- vm/devices/storage/nvme_test/src/pci.rs
- vm/devices/storage/nvme_test/src/workers.rs
- vm/devices/storage/nvme_test/src/workers/coordinator.rs
This is a support PR being made to reduce size of #1858. Added `NvmeWorkersContext` that stores the input for `NvmeWorkers`. This will subsequently be used to create new `NvmeWorkers` when FLR is issued to the test controller.
> nvme_test: Added NvmeWorkersContext input for the NvmeWorkers struct

- vm/devices/storage/nvme_resources/src/fault.rs
- vm/devices/storage/nvme_test/src/workers/admin.rs
The controller delay fault was previously being implemented by the callback function mechanism. However, since we are now using enums to specify faults, it makes a lot more sense to have a delay enum and have the fault controller execute the delay fault during processing.
This will support the first keepalive vmm test that requires admin queue delay + drop functionality.
> nvme_test: Add controller delay fault

- openhcl/underhill_core/src/dispatch/mod.rs
- openhcl/underhill_core/src/worker.rs
Adding correlation id to tracing for "shutdown_mana" and "shutdown_pci_devices".
> adding correlation id to shutdown tracing statements

- Cargo.lock
- Cargo.toml
We no longer need the git dependency here.
> Deps: Update igvm to newly released version

- vm/devices/storage/nvme_resources/src/fault.rs
- vm/devices/storage/nvme_test/src/workers/admin.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/openhcl_servicing.rs
Previously the openhcl test was using the `QueueFaultBehaviour::Drop` fault in order to block `CREATE_IO_COMPLETION_QUEUE` commands. In the test failure case this relied on the test timing out and failing. In order to fail fast we can instead panic if such a command is seen.  This should reduce test run time in the failure case.
> nvme_test: Added panic fault for admin commands

- Cargo.lock
- openhcl/openhcl_boot/Cargo.toml
- openhcl/openhcl_boot/src/dt.rs
- openhcl/openhcl_boot/src/host_params/dt.rs
- openhcl/openhcl_boot/src/host_params/mod.rs
- openhcl/openhcl_boot/src/host_params/shim_params.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/openhcl_boot/src/memory.rs
- openhcl/openhcl_boot/src/sidecar.rs
- vm/loader/loader_defs/src/shim.rs
Over time, openhcl_boot has gotten more and more complicated with different components carving out different sections of the address space. In preparation for some future changes, refactor openhcl_boot to have a central module responsible for managing and allocating address space, and reporting information about the address space to the kernel. 
This greatly simplifies address space management and makes it easier to add new functionality in the future that requires new ranges.
> openhcl_boot: refactor address space management

- Cargo.lock
The previous change #1754 had a stale green PR build that was missing a Cargo.lock update. Take this change to unbreak CI.
> repo: update Cargo.lock to fix CI break

- openhcl/openhcl_boot/src/main.rs
- openhcl/openhcl_boot/src/memory.rs
#1754 had a bug where we never tracked that we allocated a pool range, which breaks enabling nvme keep alive. Fix this by correctly reporting it and updating the test.
> openhcl_boot: correctly report that the vtl2 pool has allocations

- support/sparse_mmap/src/lib.rs
Add methods on `SparseMapping` that call `try_read_volatile` and `try_write_volatile`. This makes it easy and safe to access a mapping with volatile semantics, needed to access device registers, for example.
Cherry-pick of #1499
> sparse_mmap: support safe volatile access methods (#1499)

- Cargo.lock
- vm/devices/vmbus/vmbus_client/Cargo.toml
- vm/devices/vmbus/vmbus_client/src/driver.rs
- vm/devices/vmbus/vmbus_client/src/filter.rs
- vm/devices/vmbus/vmbus_client/src/lib.rs
- vm/devices/vmbus/vmbus_client/src/saved_state.rs
- vm/devices/vmbus/vmbus_ring/src/lib.rs
Add infrastructure to `vmbus_client` for writing vmbus channel drivers. This includes a filter, which can be used to allow some offers to go to `vmbus_relay` and others to be set aside, and infrastructure to allocate a ring buffer and open the channel.
Cherry pick of #1579.
> vmbus_client: add filter and channel driver support (#1579)

- Cargo.lock
- vm/devices/storage/nvme/Cargo.toml
- vm/devices/storage/nvme/src/pci.rs
- vm/devices/storage/nvme/src/queue.rs
- vm/devices/storage/nvme/src/tests/shadow_doorbell_tests.rs
- vm/devices/storage/nvme/src/workers/admin.rs
- vm/devices/storage/nvme/src/workers/coordinator.rs
- vm/devices/storage/nvme/src/workers/io.rs
Currently, shadow doorbells are implemented in a way where there are essentially two doorbell values: the shadow one and the "real" one. Observed changes to the shadow value are reflected in the real value but not vice versa. This causes problems when guests do not use, or only inconsistently use, the shadow doorbells for a given queue.
The spec is somewhat ambiguous on this front, but it's clear from guest behavior that the expectation is that the shadow doorbells and the real doorbells remain in perfect sync, so that the actual doorbell value can be read from the shadow doorbell. To support this, use the shadow doorbell memory as the single source of truth for the doorbell register value.
In addition to these changes, simplify the EventIdx handling to match the strategy we use for …
> nvme: improve shadow doorbell support

- vm/devices/net/netvsp/src/test.rs
There have been several test failures over the last month related to a message not arriving. Change the delay strategy to wait for them longer instead of sleeping an arbitrary amount of time and then waiting.
> netvsp: test: make link_status_update test more resilient to timing differences.

- flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Update the Linux kernel to the latest available version with upstream stable patches. See
https://github.com/microsoft/OHCL-Linux-Kernel/pull/102 for more details.
The dev and main kernels are currently identical.
> kernel: update main and dev kernel to 6.12.44

- Cargo.lock
- Cargo.toml
tracing-subscriber versions <= 0.3.19 have a low impact security vulnerability if untrusted user input is traced to terminals that respect ANSI escape sequences. I don't think there's any meaningful impact to us today from this, and it is fixed in 0.3.20. As a side benefit, this finally drops the old regex version from our lockfile, though this didn't end up in openhcl anyways so there should be no binary size change from it.
Manually remade the change from #1950 instead of cherry-picking to avoid merge conflicts.
> Deps: Update tracing-subscriber to fix component governance alert

- vmm_tests/vmm_tests/tests/tests/multiarch/openhcl_servicing.rs
#1918 Accidentally removed a check in the shutdown_ic servicing test checking if servicing is supported on the host. This PR re-adds the check.
> vmm_tests: skip servicing shutdown_ic test on unsupported hosts

- openhcl/openhcl_boot/src/host_params/dt.rs
- openhcl/openhcl_boot/src/main.rs
- openhcl/openhcl_boot/src/memory.rs
An upcoming change has more range types to be reported in the init call, so make this a builder in preperation for that. This makes it cleaner as otherwise the function becomes very unwieldy.
> openhcl_boot: refactor address space init to a builder pattern

- openhcl/virt_mshv_vtl/src/processor/mod.rs
When guests are in the middle of crashing they can be in broken states and do weird things. We've seen cases where they pass some outrageously large number to this (or possibly a negative number?), which results in us attempting to alloc a giant Vec, which results in us OOMing. Limit this to a single page to match the spec, and the hypervisor.
> virt_mshv_vtl/mshv: Limit crash message size

- vm/devices/storage/nvme_resources/src/fault.rs
- vm/devices/storage/nvme_spec/src/lib.rs
This change adds infra for CompletionQueue faults. This will help enable payload based faults for the nvme_test crate where the dptr value can be changed before sending a completion.
Completion faults will still rely on command matching because `Completion` does not contain any command level information.
> nvme_test: add completion queue fault infrastructure

- openhcl/underhill_attestation/Cargo.toml
- openhcl/underhill_attestation/src/lib.rs
- vm/devices/storage/disk_get_vmgs/src/lib.rs
- vm/vmgs/vmgs/Cargo.toml
- vm/vmgs/vmgs/src/error.rs
- vm/vmgs/vmgs/src/vmgs_impl.rs
- vm/vmgs/vmgs_lib/src/lib.rs
- vm/vmgs/vmgstool/src/main.rs
Unify the logic for updating the VMGS encryption key by moving the logic into a new function in `vmgs_impl`. OpenHCL already had the logic for recovering when adding a new key and there was already two datastore keys, but this error was encountered when using VmgsTool. This can occur if the previous add key operation failed mid-way through and we did not remove the old key.
> vmgstool: recover if no space for new encryption key

- vm/devices/net/netvsp/src/lib.rs
Cherry Pick of #1939 to 2505 to unblock hibernation testing.
Transferring large files (with cross-page-boundary RNDIS headers) to a Gen-1 Linux guest VM running kernel 3.10 over the Underhill synthetic network path causes the transfer to hang. This occurs because Linux kernels prior to 3.11 have known issues with pending send size optimization, which can interfere with certain Asynchronous I/O (AIO) network operations. To address this, we disable ring size optimization on these older kernels to prevent flow control problems.
> Disable ring size optimization on linux kernels < 3.11 to avoid flow control issues

- vm/devices/pci/vpci/src/device.rs
- vm/devices/pci/vpci_protocol/src/lib.rs
- vmm_core/virt/src/aarch64/gic_software_device.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
Add support for newer protocol versions that support vector values that are wide enough for ARM64 interrupt IDs. Enable the NVMe boot test on ARM64 to get coverage.
> vpci: add support for 32-bit vectors for ARM64

- vm/devices/storage/disk_nvme/nvme_driver/src/tests.rs
- vm/devices/storage/nvme_resources/src/fault.rs
- vm/devices/storage/nvme_test/src/tests/controller_tests.rs
- vm/devices/storage/nvme_test/src/tests/shadow_doorbell_tests.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/openhcl_servicing.rs
FaultConfig now matches the rest of the code and has builder notation. Adding an empty fault config should be much cleaner now.
> nvme_test: Add builder notation for fault configuration struct to match the rest of the fault code

- Cargo.lock
- openhcl/virt_mshv_vtl/src/lib.rs
- vmm_core/virt_hvf/Cargo.toml
- vmm_core/virt_hvf/build.rs
- vmm_core/virt_hvf/src/lib.rs
- vmm_core/virt_kvm/src/arch/aarch64/mod.rs
- vmm_core/virt_kvm/src/arch/x86_64/mod.rs
- vmm_core/virt_kvm/src/gsi.rs
This PR sets all of our current virt backends to require `guest_is_native` (since they're all native backends), which then allows us to change a few `target_arch`s to `guest_arch`s and avoid the xtask comment requirement.
> virt_*: Unify handling of guest_arch in virt backends

- vm/devices/net/netvsp/src/lib.rs
Don't allow the guest to enable offloads that are not supported by the network backend.
This fixes net_tap with Windows guests.
> netvsp: mask offload request to what's supported

- support/inspect/src/initiate.rs
- support/inspect/src/lib.rs
This change makes the following improvements to the JSON output produced by inspect nodes:
- Hex and binary values are formatted as strings, for readability.
- Errors are output as a special `{"$error":"message"}` object rather than as `null`.
- Some additional tests of the JSON output format were added.
Note: this affects the JSON output, which is not the output shown by the "inspect" command in OpenVMM or ohcldiag.
> inspect: improve json output format

- build_support/windows_cross/cross_tool.py
cross_tool attempts to use the latest available SDK and assumes all SDK
versions are installed in the same directory, with folder names consisting
only of digits and dots (e.g., 10.0.26100.0).
However, there is a potential issue: the Windows Driver Kit (WDK) may also
be installed in the same location as the SDKs, leading to additional
directories like the following:
.
├── 10.0.22621.0
├── 10.0.26100.0
└── wdf
In such cases, the sorting logic may incorrectly select wdf instead of the
latest SDK version (10.0.26100.0).
This PR updates cross_tool to ignore any directories that do not follow the
expected version pattern (i.e., names containing only digits and dots),
ensuring only valid SDK version folders are considered.
> cross_tool.py: remove unrelated folder from SDK search paths

- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
Disable Hyper-V ARM VMM tests until the runners are updated. The certs expired on the pre-release builds currently being used.
> ci: disable hyperv arm tests

- openhcl/virt_mshv_vtl/src/lib.rs
- vmm_core/virt/src/aarch64/mod.rs
- vmm_core/virt/src/lib.rs
- vmm_core/virt/src/x86/mod.rs
- vmm_core/virt_kvm/src/arch/x86_64/mod.rs
- vmm_core/virt_kvm/src/lib.rs
- vmm_core/virt_mshv/src/lib.rs
- vmm_core/virt_whp/src/lib.rs
It is currently possible to easily hit these asserts through the openvmm command line, but we also had an openhcl ICM come in that hit one of these. Return a proper error instead of panicking to present the failure in a nicer manner.
> virt: Return an error if host capabilities are insufficient instead of asserting

- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
Reverts microsoft/openvmm#2017, now that we have 2 updated runners.
> Revert "ci: disable hyperv arm tests"

- vm/acpi_spec/src/lib.rs
- vm/acpi_spec/src/mcfg.rs
This change adds currently unused MCFG definitions and parsing to the `acpi_spec` crate. The MCFG table describes the memory-mapped configuration space base address for each PCIe root complex device on a system.
Future changes will actually utilize these MCFG definitions to expose enhanced configuration access mechanism (ECAM) addresses to guests. See #1976 for a preview.
> acpi_spec: add MCFG definitions and parsing

- openhcl/underhill_core/src/worker.rs
- openhcl/virt_mshv_vtl/src/processor/mod.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
- openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
- openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- tmk/tmk_vmm/src/run.rs
- vmm_core/src/partition_unit/debug.rs
- vmm_core/src/partition_unit/vp_set.rs
- vmm_core/src/vmotherboard_adapter.rs
- vmm_core/virt/src/generic.rs
- vmm_core/virt/src/io.rs
- vmm_core/virt_hvf/src/lib.rs
- vmm_core/virt_kvm/src/arch/aarch64/mod.rs
- vmm_core/virt_kvm/src/arch/x86_64/mod.rs
- vmm_core/virt_support_aarch64emu/src/emulate.rs
- vmm_core/virt_support_x86emu/src/emulate.rs
- vmm_core/virt_support_x86emu/tests/tests/common.rs
- vmm_core/virt_whp/src/vp.rs
- vmm_core/vmm_core_defs/src/lib.rs
The intention behind this change is to provide better crash stacks and dumps in crash reports. By panicking at the point of error construction, rather than after the error has bubbled up to a higher layer, we are better able to capture stack context around the cause of the failure and to provide a meaningful stack to our atomations (instead of just blaming the HaltRequest::Panic handler for all these different error sources). Essentially simulating 'unwrapping' these errors.
However the ability to keep a VM 'alive' for inspection after a failure is still useful, and we want to preserve it. Therefore this change makes this new behavior configurable.
> virt: Replace generic VpHaltReasons with new CpuIo::fatal_error, add configurable policy

- vmm_tests/vmm_tests/tests/tests/multiarch/openhcl_servicing.rs
The test `openhcl_servicing/openvmm_openhcl_uefi_x64_ubuntu_2204_server_x64_nvme_keepalive_with_device` was recently ported over from the uefi file to `openhcl_servicing.rs`. Previously in the test we would servicing with keepalive only once. However after moving it the number was increased to 3 per test in line with all the other keepalive tests.
This increase contributed to the test timing out. Reducing the number of servicing loops for only this test.
> vmm_tests: Reduce the number of servicing loops for the with_devices keepalive test

- openhcl/minimal_rt/src/arch/aarch64/intrinsics.rs
- openhcl/minimal_rt/src/arch/x86_64/intrinsics.rs
The implementation for intrinsics in minimal_rt was incorrect. For example, the inline asm block for `memcpy` correctly describes that `rdi` will be clobbered by `rep movsb`, but `memcpy`'s API requires that the return value is the _original_ destination pointer, not the incremented pointer. Fix this by removing the mut on `dest` and indicating to the compiler to discard the clobbered value. 
It seems that in most cases, the compiler ignored the return value of memcpy, except when #2031 was being added. Certain compilation options or function implementations would cause the compiler to use the inlined returned value of `memcpy` directly from the call to realloc, which would then cause a later an assertion failure due to the pointer not being what was expected and overlapping with the new …
> minimal_rt: fix intrinsics to correctly return original pointer

- vm/devices/vmbus/vmbus_channel/src/bus.rs
- vm/devices/vmbus/vmbus_proxy/src/lib.rs
- vm/devices/vmbus/vmbus_proxy/src/proxyioctl.rs
- vm/devices/vmbus/vmbus_relay/src/lib.rs
- vm/devices/vmbus/vmbus_server/src/channels.rs
- vm/devices/vmbus/vmbus_server/src/channels/tests.rs
- vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This change allows vmbusproxy to specify a device order that will be used to determine the offer order for offers provided by `proxyintegration`. This means that in combination with the `use_absolute_channel_order` option, vmbusproxy can control the order in which devices get assigned channel IDs.
This is not a breaking change; although the `VMBUS_PROXY_NEXT_ACTION_OUTPUT` structure has increased in size, older versions of vmbusproxy.sys which don't support device order will simply not write to the new field, which is therefore left at zero.
> vmbus_server: allow proxy driver to specify a device order

- openhcl/openhcl_boot/src/host_params/dt/mod.rs
Just always enable this small allocator block until the next PR is in, as otherwise release builds fail in CI.
> openhcl_boot: reference allocator in all builds

- openhcl/underhill_core/src/worker.rs
- vm/devices/get/get_protocol/src/dps_json.rs
Due to factors outside of this project, we shouldn't need two flags to control ak cert provisioning.
> tpm: only use one ak cert flag

- openhcl/underhill_attestation/src/lib.rs
This change brings a few more GSP-related logs to info level. This might have made the diagnosis for a recent outage a little easier.
> Promote a few logs to info level (#2046)

- support/local_clock/src/clock_impls.rs
Finally caught a run of this unit test failing with the new debug output: `delta: 999ms`. Allow this case, to hopefully make this flakiness finally go away.
> local_clock: Allow rounding error to hopefully fix flaky unit test

- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
This test generates IO against the translated devices. This has found a bug in in-development code, so I believe there is value here.
- Up the size of the attached disk, so that there is enough space for IO.
- Use `dd`, since that's inbox. 1MB IO matches the IO pattern seen for the bug offline.
- Also make it easier to debug, so print more output.
> vmm_tests: storvsp: generate IO to the attached devices

- openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
- vm/hv1/hvdef/src/lib.rs
- vmm_core/src/partition_unit/vp_set.rs
- vmm_core/virt/src/generic.rs
- vmm_core/virt_whp/src/vp.rs
We were hitting this unreachable occasionally in some tests, add the missing values to provide cleaner error messages.
> virt_mshv_vtl/arm: Add missing reset types

- petri/src/vm/hyperv/mod.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/mod.rs
- petri/src/vm/openvmm/runtime.rs
An attempt to mitigate https://github.com/microsoft/openvmm/issues/1684.
Reset the VM if we haven't gotten a boot event within 15 seconds (good case it usually takes less than 1s). Plumbed new VMM quirks to make this only happen for OpenVMM PCAT.
> petri: retry pcat boot

- vmm_tests/vmm_tests/tests/tests/multiarch.rs
This just boots up the VM and checks that the services correctly show up as enabled. We could look into more indepth testing of specific features too, but I expect much of that to be covered by opentmk in a more developer-friendly way.
> vmm_tests: Add a basic boot test for guest VSM support

- flowey/flowey_lib_hvlite/src/_jobs/local_build_and_run_nextest_vmm_tests.rs
Flowey insists that everything be used, and this variable isn't in build-only mode.
> xflowey: Fix local vmm test command for build-only mode

- openhcl/underhill_mem/src/init.rs
- openhcl/underhill_mem/src/lib.rs
This fixes some oversights and edge cases in underhill_mem that were pointed out during an audit of our memory protections code.
1. We need to remove permissions when unaccepting pages on SNP
2. We need to completely forbid changing permissions on individual overlay pages to avoid a potential race condition (does not apply to the default permissions case)
3. We need to be careful around changing the default permissions when pages are locked, since we don't restore default permissions when they're unlocked
4. Remove a stale comment
Fixes #1021
> uh_mem: Fix a few oversights and edge cases

- .config/nextest.toml
Let's see if this is still an issue.
> nextest.toml: Try removing the windows unit test timeout

- vmm_core/virt_mshv/src/lib.rs
To configure custom VM features during VM creation, the create and initialize steps have been broken up in mshv-ioctls, starting with:
1afa433 mshv-ioctls: Don't initialize partition after creation
So, any uses of v0.5.0 and newer versions of mshv-ioctls should explicitly initialize the vm after creation.
> virt_mshv: init vm after creation

- vmm_tests/vmm_tests/tests/tests/multiarch/vmbus_relay.rs
#2003 Introduced a change to potentially fix a flaky vmm_test related to validating mnf usage in guests. However, it looks like the test flakiness has not been resolved. I am disabling the test for now to unblock contributors while I have a proper chance to investigate the issue.
> vmm_tests: Disable flaky mnf vmm_test

- vm/devices/net/net_packet_capture/src/lib.rs
Currently, the packet capture queue implementation is not plumbing the `update_target_vp` call and thereby queues don't get retargeted while capturing packets. As soon as the packet capture is done and detaches, the queues were getting retargeted, so this is an issue only while the packet capture is attached.
> Implement update target vp call for packet capture

- .github/workflows/openvmm-pr.yaml
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
There is a bug somewhere in ARM's UEFI that is causing VMM tests to randomly fail with spurious VMBus errors. The investigation of this bug is ongoing. However, until we have a fix, we should unblock CI for others. Don't require these tests to pass for the moment to allow merges, but still run them.
> CI: Don't require ARM VMM tests to pass right now

- support/pal/pal_async/src/windows/iocp.rs
- support/pal/pal_async/src/windows/local.rs
- support/pal/pal_async/src/windows/mod.rs
- support/pal/pal_async/src/windows/overlapped.rs
- support/pal/pal_async/src/windows/socket.rs
- support/pal/pal_async/src/windows/tp.rs
- support/pal/src/windows.rs
- support/pal/src/windows/afd.rs
The Windows socket poll and completion paths have some narrow race windows that cause hangs and invalid handle use. Increase lock hold times to prevent these races.
> pal_async: fix race conditions in Windows socket completion path

- vmm_tests/vmm_tests/test_data/memstat_baseline.json
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/memstat.rs
Description:
To address additional memory overhead with the internal build conflicting with previous baseline values, GP tests will be temporarily disabled to unblock the pipeline while the baseline data is updated.
Changes:
- Tests are split up between CVM and GP memory validation
- x64 GP memory validation tests are commented out for now
- Per-process memory usage threshold is increased to 512kB
> vmm_tests: disabling GP x64 memory validation tests for data collection on internal build

- .github/workflows/openvmm-ci.yaml
- .github/workflows/openvmm-pr-release.yaml
- .github/workflows/openvmm-pr.yaml
- Cargo.lock
- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_lib_hvlite/src/_jobs/local_build_and_run_nextest_vmm_tests.rs
- flowey/flowey_lib_hvlite/src/build_vmgstool.rs
- openhcl/underhill_core/src/worker.rs
- openvmm/hvlite_core/src/worker/dispatch.rs
- openvmm/openvmm_entry/src/cli_args.rs
- openvmm/openvmm_entry/src/lib.rs
- petri/src/vm/hyperv/hyperv.psm1
- petri/src/vm/hyperv/mod.rs
- petri/src/vm/hyperv/powershell.rs
- petri/src/vm/hyperv/vm.rs
- petri/src/vm/mod.rs
- petri/src/vm/openvmm/construct.rs
- petri/src/vm/openvmm/mod.rs
- vm/devices/get/get_resources/Cargo.toml
- vm/devices/get/get_resources/src/lib.rs
- vm/devices/get/guest_emulation_device/src/lib.rs
- vm/devices/get/guest_emulation_device/src/resolver.rs
- vm/devices/get/guest_emulation_device/src/test_utilities.rs
- vm/vmgs/vmgs_resources/src/lib.rs
- vmm_tests/vmm_tests/Cargo.toml
- vmm_tests/vmm_tests/tests/tests/multiarch/vmgs.rs
Adds the necessary infrastructure and plumbing to support testing VmgsTool and OpenHCL in petri with GspById VMGS encryption. Tests all VmgsTool commands used in production.
> vmgstool: encryption tests

- vmm_tests/vmm_tests/tests/tests/multiarch/memstat.rs
https://github.com/microsoft/openvmm/commit/5441d0af80f994d814b68b4513d985b4ac1c2133 broke release CI.
> vmm_tests: fix release build by remove expect(dead_code) for memory validation tests

- flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
- flowey/flowey_lib_hvlite/src/_jobs/local_build_and_run_nextest_vmm_tests.rs
- vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs
- vmm_tests/petri_artifacts_vmm_test/src/lib.rs
- vmm_tests/vmm_test_images/src/lib.rs
- vmm_tests/vmm_test_macros/src/lib.rs
- vmm_tests/vmm_tests/tests/tests/multiarch.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/ic.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/openhcl_servicing.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/vmbus_relay.rs
- vmm_tests/vmm_tests/tests/tests/multiarch/vmgs.rs
- vmm_tests/vmm_tests/tests/tests/x86_64.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/storage.rs
- vmm_tests/vmm_tests/tests/tests/x86_64/tpm.rs
22.04 is really old now, let's see if everything works with our already existing 24.04
> vmm_tests: Update every test to use Ubuntu 24.04
