README.md
Probably should've done this yesterday, but better late than never 😅
=> readme: Update README.md to match Guide

README.md
Now that the blog post is up let's mention it! This also adds a guide link in the same sentence just so it's that much more likely to be seen.
=> Add link to the blog post (and a second guide link) to the README

CONTRIBUTE.MD, Guide/src/dev_guide/contrib/pr.md
initial content in /dev_guide/contrib/pr.html
=> repo/guide: add CONTRIBUTING guidelines

SUPPORT.md
fixed zulip mention to clarify the link is coming soom
=> fixed zulip

.github/workflows/private-vso-build.yml
Inability to test these changes in the context of a PR, compounded with a lack of JS experience, translates to this sort of hotfix...
=> github-actions: hotfix for #134

.github/workflows/private-vso-build.yml
Very frustrating indeed... Running into https://github.com/actions/checkout/issues/785
=> gh-actions: hotfix for #136

.github/workflows/private-vso-build-trampoline.yml
I only have myself to blame for this one 😅 but, to be fair, we _have_ been fire-fighting this thing all day.
=> gh-actions: hotfix for #139

vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs
Fix save state to be compatible with older versions.
=> Keep vmbus save state backward compatible

.github/workflows/openvmm-ci.yaml, .github/workflows/private-vso-build.yml, .github/workflows/refresh-vso.yml, flowey/flowey_core/src/node.rs, flowey/flowey_lib_common/src/gh_task_azure_login.rs
This change updates all instances of the Azure Login action to use the latest version (v2.2.0).
=> CI: Update to Azure/login@v2.2.0

openhcl/openhcl_boot/src/arch/aarch64/mod.rs, openhcl/openhcl_boot/src/arch/x86_64/mod.rs
slipped in with https://github.com/microsoft/openvmm/commit/6d5ad4612ef99dc80c8e64be2be40717a09e391e. The CI failed but the PR was merged anyways
=> openhcl_boot: fix lints

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_common/src/_util/extract.rs, flowey/flowey_lib_common/src/download_mdbook.rs, flowey/flowey_lib_common/src/download_protoc.rs, flowey/flowey_lib_hvlite/src/artifact_rustdoc.rs, flowey/flowey_lib_hvlite/src/download_lxutil.rs, flowey/flowey_lib_hvlite/src/download_openhcl_kernel_package.rs, flowey/flowey_lib_hvlite/src/download_openvmm_deps.rs, flowey/flowey_lib_hvlite/src/download_uefi_mu_msvm.rs, flowey/flowey_lib_hvlite/src/init_openvmm_magicpath_linux_test_kernel.rs, flowey/flowey_lib_hvlite/src/init_openvmm_magicpath_openhcl_sysroot.rs
This reverts commit 58c9cd5ed69b28a43e99f50888e100e5fe33c648.
This change caused several breaks, which were not caught due to CI misconfiguration. I'll fix these up and submit a new change.
=> Revert "flowey: unify archive extraction (#122)"

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines_shared/gh_flowey_bootstrap_template.yml, flowey/flowey_lib_common/src/install_apt_pkg.rs
Retry apt-get update and apt-get install when running in CI. Also adds some docs to the github yaml bootstrap and remove an unnecessary step.
=> flowey: Retry apt-get in CI

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, Guide/src/dev_guide/tests/vmm/azure_images.md, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_lib_hvlite/src/download_openvmm_vmm_tests_vhds.rs, xtask/src/tasks/guest_test/download_image.rs
Re-enables the VMM tests, which no longer require authentication to download the test images.
Fixes #137
=> Enable VMM Tests

openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
Cpuid values aren't going to change across VPs, so only query this once.
=> Move tsc_aux_virtualized into partition-shared snp data

openhcl/virt_mshv_vtl/src/processor/mod.rs
The code was right, but the comment was wrong
=> Fix an inverted comment on lapic construction

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, vm/hv1/hv1_emulator/src/hv.rs
Implements VTL return hypercall handling for guest vsm support.
Tested:
- SNP VM boots
- SNP + VSM returns back to VTL 0
=> [SNP Guest VSM] Implement VTL Return hypercall handling

openhcl/openhcl_boot/src/hypercall.rs, openhcl/openhcl_boot/src/main.rs
Skip some checks when running in VTL0.
=> openhcl_boot: support booting in VTL0

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This is really where it belongs, it's essentially part of the lapic's work
=> Move nmi_pending into LapicState

Guide/src/dev_guide/getting_started/suggested_dev_env.md
Admonish + code block didn't work as I expected (or claim to have seen locally). Thanks Daniel for catching it!
=> guide: don't combine admonish + code block

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_core/src/node.rs, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_lib_hvlite/src/_jobs/build_and_run_doc_tests.rs, flowey/flowey_lib_hvlite/src/_jobs/mod.rs, support/mesh/mesh_process/src/lib.rs
=> flowey: run doctests in CI

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_pools.rs, openhcl/openhcl_boot/src/main.rs
Uses baremetal arm machines to run unit tests and vmm tests on arm. Disables one problematic unit test.
=> ci: enable arm64 tests

openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
Could be useful to help debug issues between VTLs
=> virt_mshv_vtl/snp: Track stats per-VTL

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
Add registers to get/setvpregisters hypercall handling for guest vsm support.
Tested: SNP, SNP+VSM
=> [SNP Guest VSM] Add registers to get/set vp register hypercall handling

Cargo.lock, Cargo.toml
Thanks to dtolnay for fixing the two issues I found here so quickly.
=> Update linkme for Rust 2024 compatibility

.github/workflows/refresh-mirror.yml
When porting the old pipeline over I forgot to update the name of the pipeline.
=> CI: Update the name of the refresh-mirror workflow

Guide/src/dev_guide/getting_started/suggested_dev_env.md
Adds a note about exporting the environment variables for the kernel, initrd and UEFI firmware through WSL.
=> [Docs] Exporting env variables through WSL

.devcontainer/devcontainer.json, Guide/src/SUMMARY.md, Guide/src/dev_guide/getting_started/devcontainer.md, Guide/src/dev_guide/getting_started/suggested_dev_env.md
Cherry pick of #312 and #333 to release/2411.
=> repo: add devcontainer and tweaks

vm/devices/uidevices/src/keyboard/mod.rs, vm/devices/uidevices/src/mouse/mod.rs, vm/devices/vmbus/vmbus_async/src/queue.rs, vm/devices/vmbus/vmbus_server/src/hvsock.rs, vm/vmgs/vmgstool/src/main.rs
We have the async-test macro, we should be using it. Accomplished with an only mildly complicated regex. Best reviewed ignoring whitespace, since every test here lost a level of indentation.
=> Clean up some tests that were manually async

openhcl/underhill_attestation/src/key_protector.rs
This PR updates the DEK format check logic for erroring out when using AES-wrapped key when there is no DES and adds more tests to the key protector key rotation.
=> attestation: Update DEK format check logic

openhcl/underhill_core/src/worker.rs
Don't start in x2apic mode (like we do for enlightened VMs), since there are guest compatibility issues with that.
=> underhill_core: use host APIC policy for unenlightened VMs

vm/devices/user_driver/src/emulated.rs
Fixes https://github.com/microsoft/openvmm/issues/299
=> zero out memory in EmulatedDmaAllocator

openhcl/diag_client/src/lib.rs
Hyper-V has a feature where, if a serial port's configured named pipe server already exists when the VM starts, it will connect as a client to the named pipe server instead of creating a new pipe server. This makes it possible to ensure that the pipe connection is established before the VM starts running, guaranteeing that early boot output is not lost.
Unfortunately, after this initial named pipe connection is terminated, Hyper-V just gives up--it doesn't try to reconnect to another pipe server, and it doesn't start a pipe server of its own. There's no way that I can find to reconnect to the serial port after this.
Given this limitation, don't try to use this special named pipe server mode configuration. Just poll on a timer to try to catch the early boot output.
Maybe we can fix Hyper-V …
=> hypestv/ohcldiag-dev: don't attach to serial ports in server mode

CONTRIBUTE.MD, Guide/src/user_guide/openhcl/run/hyperv.md, SUPPORT.md
added zulip link now that zulip is ready, also fixed missing enter before image in hyperv guide for openhcl
=> added zulip link now that zulip is ready

hyperv/tools/hypestv/src/windows/hyperv.rs, hyperv/tools/hypestv/src/windows/mod.rs, hyperv/tools/hypestv/src/windows/vm.rs
Add command to get/set the paravisor command line.
=> hypestv: add `paravisor command-line` command

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client/src/saved_state.rs
Use per-request channels instead of pre-allocating channels for requests that may never come.
=> vmbus_client: use mesh more idiomatically

.github/CODEOWNERS
Let the vmbus maintainers sign off on vmbus changes.
=> CODEOWNERS: add vmbus team

vmm_tests/vmm_tests/tests/tests/x86_64.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
Add a simple self to self servicing test.
=> vmm_tests: add openhcl self to self servicing test

vm/devices/tpm/src/lib.rs
The current host implementation does not handle GET request dropping when servicing occurs with an GET (AK Cert) request in-flight. Block the servicing request for now until we fix the issue on the host.
Fixes #430
=> tpm: Block servicing requests when there is an outstanding AK cert request

openhcl/underhill_mem/src/lib.rs
The result is a little cleaner, and avoids some unreachable!s
=> Change a Vtl to GuestVtl in underhill_mem

openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
The behavior is fine as is, but document why.
=> Clean up two comments for ARM guest vsm

openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
Arrays don't get automatically zeroed when they're missing from save state. Fix this by wrapping the new arrays in options.
=> virt_mshv_vtl: Fix servicing with recent save state additions

vm/devices/net/gdma/src/queues.rs, vm/devices/net/mana_driver/src/queues.rs, vm/devices/storage/disk_nvme/nvme_driver/src/queues.rs, vm/devices/storage/nvme/src/queue.rs
The NVMe completion entry is a 16-byte value, and it contains a phase bit that the NVMe driver reads to determine when a completion in the queue is valid. To ensure the driver observes a consistent completion entry, the phase bit must be written by the device _after_ the rest of the entry, and it must be read by the driver _before_ the rest.
The memory access machinery in OpenVMM does not provide many ordering guarantees, especially on ARM64. Ensure accesses are performed in the right order via two atomic 8-byte accesses, plus proper fences, in the NVMe emulator and driver.
There's a similar bug in MANA. Fix this, too.
=> nvme,mana: ensure completions are read and written in order

xsync/Cargo.lock
Pull the latest version of url to address [Dependabot #1](https://github.com/microsoft/openvmm/security/dependabot/1)
=> Update url to 2.5.4 (#524)

vm/hv1/vtl_array/src/lib.rs
=> Add a default impl for VtlArray

Cargo.lock
Grab some correctness and miri fixes.
=> Update smallbox to 0.8.6

vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs
=> vmm_tests: Fix outdated reference to ci/restore.sh

Cargo.lock, support/mesh/mesh_channel/Cargo.toml, support/mesh/mesh_channel/benches/channel.rs
These are not very sophisticated but they are better than no signal at all.
=> mesh_channel: add some basic benchmarks

openhcl/underhill_core/src/worker.rs
There are some hardware configurations on ARM64 that are not yet completely described in the MMIO map. Since ARM64 is not expected to do any x86-style legacy device detection probes, pass all MMIO accesses through to the host. If the host does not recognize the address, it will handle the bad access.
---------
=> [ARM64] Pass through all unknown MMIO to the host. (#652)

openhcl/hcl/src/ioctl/tdx.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
=> Updated the controls and mask parameter location for tdcall_vp_wr

xsync/xsync/src/tasks/cargo_toml.rs
Now that edition is there too.
=> Xsync the whole workspace package table

Cargo.lock, vm/devices/storage/disk_layered/Cargo.toml, vm/devices/storage/disk_layered/src/bitmap.rs, vm/devices/storage/disk_layered/src/lib.rs, vm/vmcore/guestmem/src/lib.rs
Populate read cache layers in the read path.
=> disk_layered: populate read caches

support/mesh/mesh_protobuf/src/table/decode.rs, support/mesh/mesh_protobuf/src/table/encode.rs
The type-erased table field encoders are useful outside the context of the full `TableEncoder` implementation. Make them public.
=> mesh_protobuf: make table encoders methods pub

Cargo.toml, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Some comments had gotten stale, some are gaining extra detail, and hypestv is moved into its correct slot.
=> Update a few tdx comments and Cargo.toml sorting

openhcl/virt_mshv_vtl/src/cvm_cpuid/snp.rs, openhcl/virt_mshv_vtl/src/cvm_cpuid/tests/mod.rs, vm/x86/x86defs/src/cpuid.rs
=> x86defs: clean up some cpuid definitions

openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
Removes an unneeded heap allocation and double iteration. Part of #699
=> Cleanup TDX's TLB flush code

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This matches the HCL code, and fixes a TODO. Part of #699
=> TDX TLB: Properly handle cases of ranges with too large counts

vm/devices/user_driver/src/vfio.rs
The VFIO drivers have been getting away without setting bus master enable, probably due to Hyper-V VPCI quirks. Explicitly set the required and desired command bits to be resilient against different PCI implementations.
=> user_driver: set pci device command bits appropriately

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Per teams conversations with John
=> TDX: Tweak orderings and comments for TLB flush list active_vtl optimization

openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/dma_manager.rs, openhcl/underhill_core/src/emuplat/netvsp.rs, openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/nvme_manager.rs, openhcl/underhill_core/src/options.rs, openhcl/underhill_core/src/worker.rs, vm/devices/net/mana_driver/src/gdma_driver.rs, vm/devices/net/mana_driver/src/mana.rs, vm/devices/net/mana_driver/src/tests.rs, vm/devices/net/net_mana/src/lib.rs, vm/devices/storage/disk_nvme/nvme_driver/fuzz/fuzz_emulated_device.rs, vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs, vm/devices/storage/disk_nvme/nvme_driver/src/queue_pair.rs, vm/devices/storage/disk_nvme/nvme_driver/src/tests.rs, vm/devices/user_driver/src/emulated.rs, vm/devices/user_driver/src/lib.rs, vm/devices/user_driver/src/vfio.rs
Introduces the initial implementation of the DMA framework, providing a centralized mechanism for DMA-capable memory allocation. It establishes the foundation for managing direct memory access (DMA) operations efficiently in a unified manner. Future enhancements will include pin/unpin support and bounce buffer management.
This serves as a stepping stone toward enabling pin/unpin support for the platform, which will be introduced in an upcoming PR.
=> user_driver: introduce new DMA trait for future DMA infrastructure changes

openhcl/virt_mshv_vtl/src/lib.rs
This is needed so we can remove the code setting this register in the kernel, before user mode starts. We need to set the register before we try to initialize memory protections, which is done after the protopartition.
=> virt_mshv_vtl: Set VsmPartitionConfig earlier

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
=> TDX: Enable hypercalls that need no changes

openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Fixes #560, small part of #548
=> TDX: Fill in get_vsm_capabilities and handle dr6_shared in get_vp_registers

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
=> TDX: Implement switch_vtl_state

xsync/xsync/src/tasks/cargo_toml.rs
This file is essentially extra lint configuration, and so it should be copied over when we're syncing lint configuration. A local rust-analyzer run suggests that this won't actually change anything today in the internal repo, but it's good to stay consistent.
=> xsync: Copy .clippy.toml when xsyncing lints

Cargo.lock, hyperv/tools/hypestv/src/windows/vm.rs, openhcl/diag_client/src/lib.rs, openhcl/ohcldiag-dev/src/main.rs, petri/Cargo.toml, petri/src/openhcl_diag.rs, petri/src/tracing.rs, petri/src/vm/hyperv/hvc.rs, petri/src/vm/hyperv/hyperv.psm1, petri/src/vm/hyperv/mod.rs, petri/src/vm/hyperv/powershell.rs, petri/src/vm/hyperv/vm.rs, petri/src/vm/openvmm/construct.rs, petri/src/vm/openvmm/runtime.rs
Adds logs for openhcl, guest serial, and hyperv
=> petri: hyperv logs

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
=> Fix comment typo

openhcl/openhcl_boot/src/host_params/dt.rs
I had this at one point during my apic prs, but seem to have lost it somehow. Part of digging into #901.
=> TDX: Fix private page pool size

openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/worker.rs, openvmm/hvlite_core/src/worker/dispatch.rs, openvmm/membacking/src/memory_manager/mod.rs, openvmm/openvmm_entry/src/lib.rs, support/mesh/mesh_process/src/lib.rs, support/pal/pal_async/src/io_pool.rs, vm/devices/chipset/fuzz/fuzz_cmos_rtc.rs, vm/devices/virtio/virtio/src/common.rs, vm/vmcore/src/vm_task.rs
We use this pattern everywhere, so encapsulate it in a method.
=> pal_async: add method to spawn a pool on a thread

xsync/xsync/src/tasks/cargo_toml.rs
Not sure how this got in and didn't break CI, that's worth investigating...
=> release/2411: Fix xsync

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
=> TDX:  Enable partition and VP VTL hypercalls

vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
=> vmm_tests: disable openhcl_servicing_shutdown_ic

flowey/flowey_lib_common/src/run_cargo_build.rs
Hotfix for #950
There's an unfortunate footgun when using `fs_err`, where the wrapped `std::io::Error` doesn't preserve the base `raw_os_error()` code. As a result, the inline backport fix I landed in 950 did not work correctly, as the `e.raw_os_error() == Some(17)` line would always be `false`, since `e.raw_os_error()` would always return `None`.
I've updated my small local test program to validate that this was indeed a bug due to the behavior difference between `std::fs::` and `fs_err::`, and that this fix should work.
=> release/2411: hotfix for #950

xtask/src/tasks/verify_size.rs
When verifying size also print out the net difference, to make it easier for us humans to make a decision. The pass/failure check is unchanged and still uses the absolute total difference,
=> verify_size: Print the net difference too for easy reading

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/apic.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Per the comment on https://github.com/microsoft/openvmm/pull/924.
=> virt_mshv_vtl: Add vtl1_active:bool to CvmVpState and check it for vtl call/return

openhcl/hcl/src/ioctl.rs, support/loan_cell/src/lib.rs, support/mesh/mesh_channel_core/src/oneshot.rs, support/mesh/mesh_node/src/local_node.rs, support/mesh/mesh_remote/src/unix_node.rs, support/openssl_kdf/src/sys/params.rs, vm/devices/get/underhill_config/src/schema/v1.rs, vm/devices/support/fs/fuse/src/session.rs, vm/devices/support/fs/fuse/tests/fuse_hello.rs, vm/devices/support/fs/lxutil/src/lib.rs, vm/devices/virtio/virtiofs/src/util.rs, vmm_core/state_unit/src/lib.rs, vmm_core/virt/src/generic.rs, xtask/src/tasks/fmt/house_rules/unsafe_code_comment.rs
Slow but steady progress towards #300
=> repo: Move more allows to expects

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/aarch64.rs, openhcl/hcl/src/ioctl/snp.rs, openhcl/hcl/src/ioctl/tdx.rs, openhcl/hcl/src/ioctl/x64.rs, vm/x86/x86defs/src/vmx.rs
=> TDX: Register the VTL 1 APIC page

flowey/flowey_cli/src/pipeline_resolver/ado_yaml.rs, flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs, openhcl/underhill_core/src/loader/mod.rs, support/mesh/mesh_derive/src/lib.rs
Some temporary lifetime changes and match restrictions. Found through #988. Part of #288
=> Misc 2024 edition compatibility fixes

openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Add a for loop in TdxBacked::new to set configuration across both VTL 0 and VTL 1. Clean up comments in new and init. Fixup a few hardcoded VTLs as a drive-by. Cleanup SNP's init as a drive-by.
Fixes #698
=> TDX: Wire up initialization for guest VSM support

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/x86/x86defs/src/tdx.rs, vmm_core/virt_support_apic/src/lib.rs
=> TDX: Implement cross-vtl interrupt checking support

xsync/Cargo.toml, xsync/xsync/src/main.rs, xsync/xsync/src/tasks/cargo_lock.rs
And clean up unused qualifications
=> xsync: Sync lints with root workspace

vm/vmgs/vmgstool/src/main.rs, vm/vmgs/vmgstool/src/uefi_nvram.rs
Improves the progress messages in vmgstool to help aid debugging, especially when storage issues cause the program to hang.
=> vmgstool: improve logging

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/deferred.rs, openhcl/hcl/src/vmsa.rs
Take 2, with BackingPrivate sticking around.
=> hcl: Tweak privacy and lints

openhcl/virt_mshv_vtl/src/cvm_cpuid/mod.rs
XSAVE size and alignment calculation requires enumerating subleafs in ascending order. Previously, using a hashmap means that iteration order is not stable, so switch it to a BTreeMap.
A follow up change will remove this path entirely, but take this small fix to fix main. This is the fix being taken back to release/2411. 
#708
=> virt_mshv_vtl: use BTreeMap for cvm cpuid subleafs

vmm_tests/petri_artifacts_vmm_test/src/lib.rs, vmm_tests/vmm_tests/tests/tests/ttrpc.rs, xtask/src/tasks/fmt/house_rules/cfg_target_arch.rs
=> petri: Add NATIVE artifacts for linux direct dependencies

Guide/src/dev_guide/getting_started/suggested_dev_env.md, Guide/src/dev_guide/getting_started/windows.md
Add a link to the instructions for installing the Windows SDK, and add a link to installing the Windows Rust toolchain in the Windows deps section of the suggested dev environment.
=> Guide: Add some links to the suggested dev env

vm/devices/net/net_mana/src/lib.rs
Cherry-picking https://github.com/microsoft/openvmm/pull/968
=> Tx segment coalesce backport to 2411

Cargo.lock, tmk/simple_tmk/Cargo.toml, tmk/simple_tmk/src/main.rs, tmk/simple_tmk/src/tmk.rs, tmk/simple_tmk/src/tmk/aarch64.rs, tmk/simple_tmk/src/tmk/x86.rs, tmk/tmk_protocol/Cargo.toml, tmk/tmk_protocol/src/lib.rs, tmk/tmk_vmm/Cargo.toml, tmk/tmk_vmm/src/main.rs, tmk/tmk_vmm/src/run.rs, vmm_core/virt_kvm/src/arch/aarch64/mod.rs, vmm_core/virt_kvm/src/arch/x86_64/mod.rs
The TMK still doesn't do anything interesting, but at least more of it
is written in arch-independent Rust now.
=> tmk: add some Rust support code

openhcl/hcl/src/ioctl.rs
Don't touch the run page if the VP might be using sidecar.
=> hcl: fix sidecar boot

openhcl/openhcl_boot/src/arch/x86_64/tdx.rs
Use the trusted hardware advertised frequency in the boot shim, rather than HyperV
#432
=> tdx: use cpuid to get frequency for in boot shim

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
Per the comment on https://github.com/microsoft/openvmm/pull/1097.
=> virt_mshv_vtl: Add a raise_vtl helper

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_common/src/cache.rs, flowey/flowey_lib_common/src/run_cargo_doc.rs, flowey/flowey_lib_common/src/run_cargo_nextest_run.rs, flowey/flowey_lib_hvlite/src/_jobs/build_and_publish_openhcl_igvm_from_recipe.rs, flowey/flowey_lib_hvlite/src/build_and_test_vmgs_lib.rs, flowey/flowey_lib_hvlite/src/build_openhcl_igvm_from_recipe.rs, flowey/flowey_lib_hvlite/src/download_openvmm_vmm_tests_vhds.rs, flowey/flowey_lib_hvlite/src/run_cargo_build.rs
I missed a few in the last round.
=> flowey: mark more steps as minor

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_flowey_bootstrap_template.yml
Reduce step noise in bootstrapping flowey.
=> flowey: reduce number of bootstrap steps

Cargo.lock, petri/Cargo.toml, petri/src/vm/hyperv/hvc.rs, petri/src/vm/hyperv/mod.rs, petri/src/vm/hyperv/powershell.rs, petri/src/vm/hyperv/vm.rs, petri/src/vm/mod.rs, petri/src/vm/openvmm/construct.rs, petri/src/vm/openvmm/runtime.rs, vmm_tests/vmm_tests/tests/tests/multiarch.rs, vmm_tests/vmm_tests/tests/tests/x86_64.rs
Adds the necessary infrastructure to support no-agent (integration component only) Hyper-V tests using Petri and improves some error handling.
=> petri: hyper-v no agent + error handling improvements

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
The TDX backend tracks the next pending interruption as a kind of shadow register on the VMCS's interruption information field. It needs to clear this pending interruption on the next exit after the L2 runs to avoid reinjecting the interruption a second time.
When kernel exit offloading is enabled, some exits are handled internally, without returning to user mode. In this case, the TDX backend does not observe the exit and so does not clear the pending interruption shadow register. If the next return from kernel mode is not due to an exit but due to an EINTR return or TDX_PENDING_INTERRUPT, then it will assume the L2 did not run and will reinject the pending interruption a second time.
To avoid this, disable the kernel exit offloading when there is a pending interruption.
A future change …
=> virt_mshv_vtl: tdx: don't double inject events

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_pools.rs, vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs, vmm_tests/petri_artifacts_vmm_test/src/lib.rs, vmm_tests/vmm_test_images/src/lib.rs, vmm_tests/vmm_test_macros/src/lib.rs, vmm_tests/vmm_tests/tests/tests/main.rs, vmm_tests/vmm_tests/tests/tests/x86_64.rs
Adds basic VBS and TDX tests on Hyper-V using Petri. Currently only works with Windows Server 2025. Further investigation is needed to get Ubuntu / other versions of Windows working.
=> petri: hyper-v vbs and tdx tests

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Don't think we need anything really special from reading through HCL code.
=> TDX: Fill in new pending event handling

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
The TDX backend tracks the next pending interruption as a kind of shadow register on the VMCS's interruption information field. It needs to clear this pending interruption on the next exit after the L2 runs to avoid reinjecting the interruption a second time.
When kernel exit offloading is enabled, some exits are handled internally, without returning to user mode. In this case, the TDX backend does not observe the exit and so does not clear the pending interruption shadow register. If the next return from kernel mode is not due to an exit but due to an EINTR return or TDX_PENDING_INTERRUPT, then it will assume the L2 did not run and will reinject the pending interruption a second time.
To avoid this, disable the kernel exit offloading when there is a pending interruption.
A future change …
=> virt_mshv_vtl: tdx: don't double inject events (#1139)

petri/src/vm/hyperv/mod.rs, petri/src/vm/hyperv/powershell.rs, petri/src/vm/hyperv/vm.rs, petri/src/vm/mod.rs, petri/src/vm/openvmm/mod.rs, vmm_tests/vmm_tests/tests/tests/multiarch.rs, vmm_tests/vmm_tests/tests/tests/x86_64.rs
Enabling a few more of our existing tests on ARM.
=> ci: add more arm tests

tmk/tmk_core/src/x86_64.rs
Fix apparent register corruption in the interrupt service routine, plus an interrupt shadow bug.
=> tmk_core: fix bugs in release builds

Cargo.lock
=> Update some dependencies for internal compliance

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
After discussing with Chris we decided that this should be done in usermode, since usermode is also the one setting it, and the kernel doesn't have a good place to put this.
Part of #699
=> TDX: Clear the TLB flush flag in usermode

petri/src/vm/hyperv/hvc.rs
Improve hvc debug logs so that it is easier to see what the last command is if it hangs (which often happens with `hvc stop`
=> petri: improve hvc logs

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This allows VSM two-proc to boot!
=> TDX: Save cstar values so we can return them to the guest

vm/devices/tpm/src/tpm_helper.rs
PR 1276 fixed an issue with TPM NVRAM space allocation and removed part of a testcase. This change brings back the affected testcase after tweaking it slightly for the new NVRAM behavior.
=> Bring back some TPM NVRAM test bits

vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
If the driver revokes a channel first, and then the channel gets removed by `ServerTask` when it's released by the guest, the `ProxyTask` would never release the channel with the driver, potentially leaving a bunch of revoked channels in the driver's channel list.
This change updates the channel removal handling to release the channel if the driver has already revoked it.
I also changed a warning trace to info because it's a noisy warning that doesn't normally indicate a problem.
=> vmbus_server: release proxy channels once removed by the server.

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/aarch64.rs, openhcl/hcl/src/ioctl/x64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, vm/hv1/hvdef/src/lib.rs
Use the arm64 register page when available.
=> hcl: arm64: support for register page

vm/devices/pci/vpci/src/device.rs, vm/devices/pci/vpci/src/lib.rs, vm/devices/pci/vpci/src/test_helpers/mod.rs, vm/devices/pci/vpci_protocol/src/lib.rs
More vpci cleanup split out from upcoming vpci relay changes.
=> vpci: clean up and fixes

vm/chipset_device/src/lib.rs, vm/devices/net/net_backend/src/lib.rs
I wonder if we should have a house_rule that enforces that every crate has either forbid or expect (unsafe_code)...
=> Add two forbid(unsafe_code)s

.github/scripts/refresh_mirror/refresh-mirror.py
Update mirroring logic to mirror the 2505 release branch.
=> CI: Update release/2505 branch mirroring

flowey/flowey_lib_common/src/run_cargo_nextest_run.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
Small tweaks to large_enum_variants.
=> Repo: Fix two more clippy cases that came out of a delayed merge of 1.87

petri/logview/common.js, petri/logview/index.html, petri/logview/test.html
This makes the test names easier to match to the code.
=> petri/logview: replace __ with :: in test names

petri/logview/common.js, petri/logview/index.html, petri/logview/test.html
Avoid using `innerHTML` to avoid HTML fragments leaking into the page.
=> petri/logview: prevent some client-side xss attacks

.github/workflows/upload-petri-results.yml, petri/logview/index.html
Tests that time out don't have a `petri.failed`. Stop looking for that file.
=> petri/logview: show timed out tests as failed

petri/logview/inspect.html, petri/logview/test.html
Provide a nice tree view for examining inspect output from tests.
=> petri/logview: add support for inspect attachments

vmm_tests/vmm_tests/tests/tests/x86_64.rs
Exercise the multi-node behavior in sidecar.
=> vmm_tests: use multiple nodes in sidecar boot test

Cargo.lock, vm/vmgs/vmgs/Cargo.toml, vm/vmgs/vmgs/src/vmgs_impl.rs
Mark tracing in vm/vmgs/* as CVM_OK, and tweak a couple logs to not print keys.
https://github.com/microsoft/openvmm/issues/852
=> vmgs: cvm tracing

openhcl/underhill_core/src/worker.rs
Just a drive by cleanup while working on other things.
=> uh_core: Clean up halt_task

flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
mu_msvm release here: https://github.com/microsoft/mu_msvm/releases/tag/v25.1.3
=> deps: update mu_msvm to v25.1.3 release

vmm_core/virt_whp/src/lib.rs
When an x2apic is emulated in user mode, then ensure cpuid exits are enabled so that the x2apic feature bit can be set.
=> virt_whp: ensure cpuid exits are enabled for x2apic emulation

vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
=> vmm_tests: skip another servicing test on amd nested

openhcl/hcl/src/ioctl.rs, openhcl/underhill_mem/src/init.rs, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
Stephanie and I did an audit of all remaining TODO GUEST VSM comments, found some small cleanups, and are following up on some minor concerns.
=> Guest VSM: Cleanup some comments

openhcl/hcl/src/ioctl.rs, openhcl/underhill_mem/src/init.rs, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
Stephanie and I did an audit of all remaining TODO GUEST VSM comments, found some small cleanups, and are following up on some minor concerns.
Cherry-pick of #1548
=> Guest VSM: Cleanup some comments (#1548)

.github/workflows/openvmm-pr-release.yaml
Looking into why this isn't failing the gates, but let's unblock other PRs.
=> CI: Run an xflowey regen

Cargo.lock, vm/vmgs/vmgs/Cargo.toml, vm/vmgs/vmgs/src/vmgs_impl.rs
Mark tracing in vm/vmgs/* as CVM_OK, and tweak a couple logs to not print keys.
https://github.com/microsoft/openvmm/issues/852
=> vmgs: cvm tracing (#1482)

vm/devices/get/guest_emulation_transport/src/process_loop.rs
We're seeing this happen in an ICM right now, so let's be better in the future.
Cherry-pick of #1604
=> GET: Log the response type when we get an unexpected one (#1604)

vmm_tests/vmm_tests/tests/tests/multiarch.rs
Add some tests that tests larger VP counts.
=> vmm_tests: add 16 vp count heavy tests

vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs, vm/devices/storage/disk_nvme/nvme_driver/src/registers.rs
With the emulated devices likely it will be 0x00000000 or 0xFFFFFFFF but we need to distinguish the cases for further diagnostics.
Cherry-pick from #1401
=> Print full CSTS value when NVMe device failed to init (#1401)

vm/devices/vmbus/vmbus_server/src/channels.rs
If the VMBus server state is saved after the guest connects but before it sends `RequestOffers`, all the channels are in the `ClientReleased` state and are therefore not saved.
When the saved state is restored, all channels are treated as new. Because the guest has connected, `revoke_unclaimed_channels` would send offer messages for these channels (which the guest does not expect at this point). When the guest subsequently sends `RequestOffers`, these channels are no longer in the `ClientReleased` state causing an assert to fail and OpenVMM/OpenHCL panics.
This change fixes `revoke_unclaimed_channels` to only send offers if `RequestOffers` was received before the save, and adds tests to cover both scenarios.
=> vmbus_server: Check if RequestOffers was received before sending offers during restore

vm/devices/pci/vpci/src/device.rs
Fixes #1721 . Namely: unless `vpci` clears config space mappings upon vmbus channel close, there is a chance of conflicts upon a future boot. This also matches the Hyper-V host behavior.
Tested via a new, in-development vmm test. Will link here when I publish that test.
=> vpci: clear config space mappings upon vmbus channel disconnect

flowey/flowey/src/lib.rs, flowey/flowey_lib_common/src/download_protoc.rs, flowey/flowey_lib_hvlite/src/init_openvmm_magicpath_protoc.rs, flowey/flowey_lib_hvlite/src/init_vmm_tests_env.rs
Reduces some duplicated code. Also a small driveby cleanup in magicpath_protoc.
=> flowey: Add a small helper for making files executable on unix platforms

openhcl/underhill_core/src/nvme_manager.rs
Otherwise, the span exit message is never logged.
=> nvme_manager: Instrument nvme_get_namespace span on call, not handler

vm/devices/chipset_legacy/src/i440bx_host_pci_bridge.rs
Managed to find a data sheet for this old chipset. Updated the register names to their actual datasheet names, added comments clarifying their ranges, and added more of them that we can ignore warnings for. Quiets a bunch of logspam on gen1.
=> i440bx: Update and ignore more config space registers

vm/devices/hyperv_ic_guest/src/shutdown.rs
The other end of the shutdown device can send a negotiation packet at any time, which should reset the state of the device and start fresh.
Port of #1616
=> shutdown_ic: version negotiation packet should trigger state reset

vm/devices/chipset_legacy/src/i440bx_host_pci_bridge.rs
Managed to find a data sheet for this old chipset. Updated the register names to their actual datasheet names, added comments clarifying their ranges, and added more of them that we can ignore warnings for. Quiets a bunch of logspam on gen1.
Cherry-pick of #1740
=> i440bx: Update and ignore more config space registers (#1740)

openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/options.rs, openhcl/underhill_core/src/worker.rs, openvmm/hvlite_core/src/worker/dispatch.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
This change cherry-picks #1829, and its dependent change #1815.
=> vmbus_server: cherry-pick #1815 and #1829

openhcl/underhill_mem/src/mapping.rs, support/sparse_mmap/src/unix.rs
If two ranges in a guest's memory layout share a bitmap backing page, then during bitmap initialization one of the range's bitmap state will be incorrectly zeroed. This causes bitmap checks to unexpectedly fail.
Fix this by not re-zeroing bitmap pages during initialization.
=> underhill_mem: fix bitmap initialization

support/sparse_mmap/src/lib.rs
MemoryError::new expects a byte length, but these functions were passing an element count. Fix this, and also fix some small typos in OsAccessError.
Bugs found by GPT-5
=> sparse_mmap: Fix functions passing count to MemoryError::new instead of len

petri/src/vm/hyperv/mod.rs, petri/src/vm/mod.rs, petri/src/vm/openvmm/construct.rs, petri/src/vm/openvmm/mod.rs, petri/src/vm/openvmm/start.rs, vmm_tests/vmm_tests/tests/tests/multiarch.rs
Add a couple of boot tests as well.
=> petri: add support for nvme boot

petri/logview/inspect.html
Fixes parsing gdma and consomme nodes, among other things.
=> petri/logview: fix inspect parsing for unevaluated nodes

vm/devices/net/net_consomme/consomme/src/lib.rs, vm/devices/net/net_consomme/src/lib.rs
Make inspect a little clearer/more useful for inspect.
=> net_consomme: inspect improvements

petri/src/vm/mod.rs
fix bad merge due to https://github.com/microsoft/openvmm/pull/1943 and https://github.com/microsoft/openvmm/pull/2016. Refactors common code for taking the inspect output and saving it to a petri attachment into `save_inspect`.
=> repo: fix bad merge

openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, vm/aarch64/aarch64defs/src/lib.rs
As described in the Arm Power State Coordination Interface version 1.3 issue F.b.
=> virt_mshv_vtl/arm64: Add handling for reset codes
