Guide/src/user_guide/openhcl/run/hyperv.md
The backquote is redundant because ```powershell .. ``` is already used. Therefore remove it, otherwise when copied, the backquote '`' is also copied in the command, which gives the error:
Out-Null` : The term 'Out-Null`' is not recognized as the name of a cmdlet...
=> Guide: openhcl: Remove the redundant backquote of powershell command

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_core/src/node.rs, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_flowey_bootstrap_template.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_flowey_bootstrap_template.yml, flowey/flowey_hvlite/src/pipelines_shared/gh_pools.rs, flowey/flowey_lib_hvlite/src/_jobs/cfg_common.rs, flowey/flowey_lib_hvlite/src/_jobs/test_local_flowey_build_igvm.rs
This has been a lot of fun to figure out...
When we marked the repo as public the 1ES hosted pools that we were previously using lost their linkage to this repository. This meant that PR tasks were not being picked up. The fix for this was to re-create new pools that are scoped to our repo.
The other issue this change resolves is removing the Azure Login task from stages that do not need it. There are still some tasks that do need access to the key vault (to download test VHD's) but this will get the CI in a much better state.
=> Fix CI issues due to disconnected 1ES pools and unneeded AzureLogin tasks

.github/workflows/private-vso-build.yml, .github/workflows/unsafe-reviewers.yml
Now that the repo is public, the pull request workflows are not able to access repository secrets. There is a separate event called `pull_request_target` that allows this, but you must be very careful when using this. Our repo is already locked down so that it requires a maintainer to kick of CI runs, so we should be OK here.
I believe this change needs to be merged to main first before this behavior can be tested. This makes sense because if you were able to change this type in a fork, you could make the change to the pipeline and the change to snoop secrets at the same time.
=> Switch private-vso-build.yml and unsafe-reviewers.yml from pull_request to pull_request_target

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_cli/src/pipeline_resolver/github_yaml/github_yaml_defs.rs, flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs, flowey/flowey_core/src/node.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_flowey_bootstrap_template.rs
flowey equivalent to the fix in #112
Also fixes GITHUB_TOKEN secret value (which is more of a guard rail than an actual info-leak issue)
=> flowey/gh: use `pull_request_trigger` instead of `pull_request`

.github/workflows/private-vso-build.yml
This change should ensure that the private VSO pipeline runs on the content of the pull request instead of the main branch.
=> Switch private-vso-build.yml to use GITHUB_REF instead of GITHUB_SHA

.github/workflows/private-vso-build-trampoline.yml, .github/workflows/private-vso-build.yml
Work around the fact that `pull_request` triggers don't have access to repo secrets, which we need in order to auth with azure and kick off a CI run.
=> gh-actions: trigger PrivateVsoBuild via a `workflow_run`

.github/workflows/private-vso-build.yml
Ah, yes, of course - the quintessential "checking out the repo deletes the entire working directory" footgun.
That's one of those things flowey just takes care of for you, but when you're writing flows manually... gotta keep your guard up. _sigh_.
Hopefully the last hotfix for now?
=> gh-actions: hotfix for #138

Guide/src/dev_guide/getting_started/build_openvmm.md
Many Linux distros package a version of Rust that is too old to support use of unstable library feature `absolute_path` in `flowey_cli`, resulting in a build error. This PR adds guidance on how to obtain the most recent stable version of Rust using rustup.
=> Add advice on using most recent stable version of Rust

Cargo.toml
Start of what is needed to activate the unused self lint - did not touch public functions yet or incomplete functions (where this would have been largely meaningless). Turns many methods into associated functions
=> Delete unwanted lints in future additions

Guide/src/index.md, Guide/src/user_guide/openhcl.md, README.md
The OpenVMM project is currently focused on building a VMM for running in the OpenHCL paravisor. Clarify this in the documentation to avoid confusion with other Rust-based VMM projects.
=> Guide: clarify project goals

flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
This cleanup change moves these three secret variables closer to where they are used by the pipeline.
=> Flowey: Move secret variables closer to where they are used

vm/devices/firmware/firmware_uefi/src/service/nvram/mod.rs
Older versions of OpenHCL (and Hyper-V, closed-source HCL, etc. ) may have created SecureBoot variable with  NV attribute, which doesn't match the UEFI spec.  If this  variable already exists, use its existing attributes.
=> Handle existing attributes for SecureBoot variable in legacy NVRAM stores

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_hvlite/src/_jobs/cfg_common.rs
This change removes the last usage of `GitHub-CLI-PAT` which was a temporary PAT for accessing various GitHub repos before they were marked as public.
=> Flowey: Remove last usage of GitHub-CLI-PAT from cfg_common.rs

openhcl/openhcl_boot/src/arch/aarch64/entry.S, openhcl/openhcl_boot/src/arch/aarch64/mod.rs, openhcl/openhcl_boot/src/arch/x86_64/entry.S, openhcl/openhcl_boot/src/arch/x86_64/mod.rs, openhcl/openhcl_boot/src/rt.rs
The entry.S files use few hardcoded constansts. As of Rust 1.82, there's a new feature allowing to pass constants into the inline assembly. Use that to improve the code structure.
=> openhcl_boot: pass the constants into the asm!() statements.

vm/loader/igvmfilegen/src/file_loader.rs, vm/loader/src/paravisor.rs, vmm_core/vm_loader/src/lib.rs
If the sidecar kernel is not already 2MB aligned, then the offset is miscomputed due to variable shadowing. Fix this.
In the future, we should get rid of this 2MB requirement, since sidecar can use 4KB pages relatively easily and has a small enough working set that the page size will not affect TLB pressure.
Also, fix some error strings to be more concise and useful.
=> loader: fix sidecar offset

.github/workflows/openvmm-ci.yaml, .github/workflows/refresh-vso.yml, flowey/flowey_core/src/node.rs, flowey/flowey_lib_common/src/gh_task_azure_login.rs
This change switches the version requirement of Azure/login to use @v2 instead of a hard-coded full version number. This means we will automatically pick up new v2.x versions of the action when they are tagged by the maintainer.
=> CI: Switch from explicitly using Azure/login@v2.2.0 to Azure/login@v2

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_common/src/_util/extract.rs, flowey/flowey_lib_common/src/download_mdbook.rs, flowey/flowey_lib_common/src/download_protoc.rs, flowey/flowey_lib_hvlite/src/artifact_rustdoc.rs, flowey/flowey_lib_hvlite/src/download_lxutil.rs, flowey/flowey_lib_hvlite/src/download_openhcl_kernel_package.rs, flowey/flowey_lib_hvlite/src/download_openvmm_deps.rs, flowey/flowey_lib_hvlite/src/download_uefi_mu_msvm.rs, flowey/flowey_lib_hvlite/src/init_openvmm_magicpath_linux_test_kernel.rs, flowey/flowey_lib_hvlite/src/init_openvmm_magicpath_openhcl_sysroot.rs
`bsdtar` can extract just about everything. Don't have separate entry paths and tools for zip vs. tar.bz2 vs. some other thing in the future.
Also, ensure extraction verifies the target directory is still there, since users (like me) might delete it when it's in a bad state hoping that subsequent flowey invocations will re-extract it.
Finally, use the extract helpers for extracting (and thus caching) sysroot.tar.gz. This speeds repeated invocations of build-igvm.
This eliminates another weird apt package dependency.
=> flowey: unify archive extraction

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Avoid having code that conditionally builds based on feature configuration by moving the gdb-related code to runtime checks instead of compile-time `cfg` attributes. These will still get compiled out at compile time, but the compiler will ensure the code actually builds.
=> virt_mshv_vtl: move gdb feature checks to runtime checks

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/snp.rs, openhcl/hcl/src/ioctl/tdx.rs, openhcl/hcl/src/lib.rs, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/apic.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs, openhcl/virt_mshv_vtl/src/processor/vp_state.rs, vm/hv1/vtl_array/src/lib.rs
When we know statically that we're referring to VTL0/VTL1 and not VTL2, use the new enum `GuestVtl` instead of `Vtl`. This allows the compiler to generate better code, it allows the reader to better understand the invariants, and it provides more safeguards that the guest is not able to manipulate VTL2 state.
As part of this, fix a few bugs.
=> virt_mshv_vtl: use GuestVtl instead of Vtl

openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
TSC Aux is not shared across VTLs and should not be copied during VTL switches.
Tested: SNP boots, and SNP + VSM runs the SK debugger
=> [SNP Guest VSM] Don't copy tsc aux state during vtl switches

.github/workflows/openvmm-ci.yaml, flowey/flowey_lib_hvlite/src/_jobs/build_and_publish_guide.rs
I noticed this warning in the CI build logs which is a little confusing because it doesn't look like we are using versions of the actions that are being deprecated. However I did notice we are using old versions of upload-pages-artifact and deploy-pages.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> CI: Update upload-pages-artifact and deploy-pages actions to latest

openhcl/openhcl_boot/src/main.rs
By default on x86, Linux probes for a PCI bus via the usual 0xcf8 method. For OpenHCL, this is unnecessary--there is no PCI bus there with a Hyper-V host, and for non-Hyper-V hosts we would expect the PCI bus to be explicitly enumerated.
This reduces exits to the host during boot and it removes another possible CVM attack vector.
=> openhcl_boot: tell Linux not to probe for a PCI bus

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/apic.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Supersedes https://github.com/microsoft/openvmm/pull/111. Since WHP is the only case in which we can hit this path, make it a bit clearer with a new per-backing method. Open for bikeshedding of course
=> Move usermode halt logic into backing-specific logic

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This removes a number of unwraps, and makes some things cleaner. I expect that more stuff will move like this over time.
=> Move cvm state into backing shared state for snp and tdx

Guide/src/dev_guide/tests/vmm.md
=> Reference to cross-compiling section is not properly linked in vmm test section of the guide

support/inspect/src/lib.rs, vm/devices/storage/disk_nvme/nvme_driver/src/queue_pair.rs
Due to its use of a slab for tracking pending commands, the NVMe driver aggressively reuses cids. This sometimes makes debugging difficult, especially when correlating logs across multiple sources. It also increases the chance that a NVMe device or driver bug will cause us to incorrectly complete an in-flight IO.
To resolve this, use the high bits of the CID as a sequence number. There are six unused bits, which is enough to at least get some variability.
=> nvme_driver: add a sequence number to high cid bits

Cargo.lock, openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/snp.rs, openhcl/underhill_mem/Cargo.toml, openhcl/underhill_mem/src/init.rs, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, vm/hv1/hv1_emulator/src/hv.rs, vm/hv1/vtl_array/src/lib.rs, vmm_core/virt_whp/src/lib.rs
Implements ModifyVtlProtectionMask hypercall handling for SNP VMs with guest VSM.
Tested with:
SNP without guest vsm
TDX-isolated VMs
Non-isolated with and without guest vsm
VBS-isolated with and without guest vsm
=> [SNP Guest VSM] ModifyVtlProtectionMask hypercall handling 

Cargo.lock, openhcl/underhill_attestation/Cargo.toml, openhcl/underhill_attestation/src/hardware_key_sealing.rs, openhcl/underhill_attestation/src/igvm_attest/ak_cert.rs, openhcl/underhill_attestation/src/igvm_attest/mod.rs, openhcl/underhill_attestation/src/key_protector.rs, openhcl/underhill_attestation/src/lib.rs, openhcl/underhill_attestation/src/secure_key_release.rs
1. Moved AkCert errors to akcert.rs.
2. Updated CVM attestation traces to include CVM_ALLOWED or CVM_CONFIDENTIAL.
3. Additional info traces during CVM initialization.
=> CVM log updates

flowey/flowey_hvlite/src/pipelines/build_igvm.rs, flowey/flowey_lib_hvlite/src/artifact_openhcl_igvm_from_recipe.rs, vmm_tests/petri_artifact_resolver_openvmm_known_paths/src/lib.rs, xtask/src/tasks/build_igvm.rs
This should make it possible to once again run vmm tests locally without manually renaming folders. Let's see what breaks...
=> Remove references to "-msft" in CI and tests

openhcl/hcl/src/ioctl.rs, openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/loader/vtl2_config/mod.rs, openhcl/underhill_core/src/vp.rs, openhcl/underhill_core/src/worker.rs, openhcl/underhill_mem/src/init.rs, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openvmm/hvlite_core/src/worker/dispatch.rs, vm/hv1/hv1_emulator/src/cpuid.rs, vmm_core/virt/src/generic.rs, vmm_core/virt_kvm/src/arch/aarch64/mod.rs, vmm_core/virt_kvm/src/arch/x86_64/mod.rs, vmm_core/virt_mshv/src/lib.rs, vmm_core/virt_whp/src/lib.rs, vmm_core/virt_whp/src/vp.rs
Instead of awkwardly passing around Option<IsolationType> everywhere, include the `None` case in `IsolationType`.
There is just one place, in `underhill_mem`, where this weakens the compile-time type checking. It doesn't seem worth adding the extra `Option` everywhere just to maintain this. `underhill_mem` can redefine a more limited enum if it really wants to avoid a few `unreachable!`s.
=> hcl: add IsolationType::None

openhcl/hcl/src/ioctl/x64.rs, openhcl/hcl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Remove hardcoding of last vtl to VTL 0. Retrieve the actual last vtl that was running from the intercept message.
Tested booting of ARM, SNP, TDX, and Trusted Launch VMs
=> Fix last_vtl usage to apply only to intercept handling, and populate it for ARM 64

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
These helpers really don't add much, and in fact can't even be used everywhere we access hv due to adding a function call boundary. Just get rid of them.
=> Remove not-really-helpful hv getters

openhcl/bootloader_fdt_parser/src/lib.rs, openhcl/hcl/src/ioctl.rs, openhcl/openhcl_boot/src/arch/aarch64/memory.rs, openhcl/openhcl_boot/src/dt.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/host_params/mod.rs, openhcl/openhcl_boot/src/main.rs, openhcl/underhill_core/src/loader/vtl2_config/mod.rs, openhcl/underhill_core/src/worker.rs
Instead of querying the hypervisor (!) to determine the partition's isolation type from inside openvmm, reuse the decision already made by the boot loader. The boot loader gets this from the measured shim parameters, so this is the most correct and secure option.
This also eliminates an mshv_vtl dependency from the startup path, which will be necessary for supporting non-mshv_vtl-based scenarios.
=> openhcl: propagate isolation type from boot loader

Cargo.lock, openhcl/hcl/Cargo.toml, openhcl/hcl/src/ioctl.rs
The existing errors are inaccurate due to changes to the file names.
=> hcl: report file paths in errors

openhcl/bootloader_fdt_parser/src/lib.rs, openhcl/hcl/src/ioctl.rs, openhcl/openhcl_boot/src/hypercall.rs, openhcl/openhcl_boot/src/main.rs, openhcl/underhill_core/src/worker.rs
Code in various places assumes that the hypervisor VP index is the same as the devicetree CPU index. Validate this early, in the boot loader, and then remove code elsewhere that half-heartedly tries to support alternative mappings. The host already guarantees this in practice, so let's take an explicit dependency.
If we ever weaken this requirement, we can just update the boot loader to reorder the CPU nodes to match the actual configuration before passing them on.
=> openhcl_boot: verify hv VP index matches dt CPU index

Guide/src/dev_guide/tests/vmm.md
The nextest command line requires a `-p` to specify which package to test, which was missing in the guide.
=> Add missing argument in nextest docs

Cargo.lock, openhcl/hcl/Cargo.toml, openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Defines the roles of the various lower-vtl usages for guest vsm support in CVMs. With this change, the exit handling code is in charge of deciding what VTL to exit to and which VTL was entered from. VtlCall/Return hypercall handling stores the intended exit VTL as a hint to exit VTL 2 code.
Tested: SNP and TDX VMs boot, SNP with guest VSM runs VTL 1
=> [SNP Guest VSM] Clarify the role of the exit vtl

vmm_core/virt_support_x86emu/src/emulate.rs
It's not an error for the instruction emulator to need to inject an exception, e.g., due to single stepping in the debugger.
Reported by @neerajsi-msft.
=> virt_support_x86emu: downgrade expected trace to debug

vm/devices/storage/nvme/src/pci.rs, vm/devices/storage/nvme/src/workers/coordinator.rs
Before `reset` was an async function, it was not possible to implement reset for NVMe (which use some external tasks). `reset` was made async a while back, so finish the NVMe implementation.
This fixes the use of NVMe after guest-initiated reset.
=> nvme: complete the reset implementation

Guide/src/dev_guide/contrib/pr.md, Guide/src/dev_guide/getting_started/build_openvmm.md, Guide/src/dev_guide/getting_started/linux.md
This is a collection of several small changes to the OpenVMM developer guide. I am setting up a new clone of this environment and following the instructions in linear order. What prompted me to first make this change is that I encountered an error running `cargo xflowey restore-packages`: it seemed to need a linker. I found going "out of order" a bit jarring. Since the same core dependencies are required to build OpenVMM and OpenHCL (I think), and we expect contributors to set up their environment first, I moved this up. And, I noticed a broken link.
* Fix broken link to the contributing guide.
* Move the Linux compiler / linker prereqs to the Linux / WSL2 setup page. These are necessary before the xflowey restore.
* Use the fancy new admonish plugin for the cross compile tip.
=> Updates to the getting started sections of the openvmm developer guide

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This removes some expects, and removes one more field from UhProcessor that isn't used globally. The option also isn't needed, since we can just leave this at Vtl0.
=> Move exit_vtl to vp cvm state and remove the option

openhcl/openhcl_boot/src/hypercall.rs, vmm_core/virt_whp/src/hypercalls.rs
The hypervisor fails VP index queries for VTLs that are not enabled for the target VP. Since VTL2 is not enabled for the APs at boot, this causes failures on multi-VP VMs.
Just query VTL0 instead. The hardware IDs will always match since we don't support changing APIC IDs at runtime.
To catch this in the future, update the virt_whp hypervisor emulator to match this behavior.
=> openhcl_boot: query VP indexes for VTL0

vm/devices/net/net_consomme/consomme/src/lib.rs, vm/devices/net/net_consomme/consomme/src/tcp.rs, vm/devices/net/net_consomme/consomme/src/udp.rs, vm/devices/net/net_consomme/src/lib.rs
Network connections that were established before guest reset are left in a bad state after reset because their old IO driver is no longer functional.
Add a method to reset the IO driver for all connections, and call it in net_consomme when the consomme queue moves into the active state.
In particular, this fixes kdnet after a guest reset.
Thanks @neerajsi-msft for the report.
=> consomme: fix connections across guest reset

Cargo.lock, openvmm/hvlite_entry/src/cli_args.rs, openvmm/hvlite_entry/src/lib.rs, vm/devices/net/net_backend_resources/src/lib.rs, vm/devices/net/net_consomme/Cargo.toml, vm/devices/net/net_consomme/consomme/src/lib.rs, vm/devices/net/net_consomme/src/resolver.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
Now you can say:
```
cargo run -- --net consomme:192.168.0.0/24
```
to set the network used by the consomme NAT. This is useful when the default network (10.0.0.0/24) conflicts with your host.
=> net_consomme: support setting the NAT network from the command line

openvmm/hvlite_core/src/worker/vm_loaders/igvm.rs, openvmm/hvlite_core/src/worker/vm_loaders/linux.rs, vm/loader/igvmfilegen/src/file_loader.rs, vm/loader/igvmfilegen/src/main.rs, vm/loader/igvmfilegen/src/vp_context_builder/mod.rs, vm/loader/igvmfilegen/src/vp_context_builder/snp.rs, vm/loader/igvmfilegen/src/vp_context_builder/tdx.rs, vm/loader/igvmfilegen/src/vp_context_builder/vbs.rs, vm/loader/src/common.rs, vm/loader/src/importer.rs, vm/loader/src/linux.rs, vm/loader/src/paravisor.rs, vm/loader/src/pcat.rs, vm/loader/src/uefi/mod.rs, vmm_core/vm_loader/src/lib.rs
The individual firmware loaders generally do not need to be VTL aware. Remove VTL awareness from most of the code. This will soon allow OpenHCL to be loaded into VTL0.
The remaining exception is the VTL0 VP context. Simplify the handling of this, so that the CVM-specific code doesn't have to know about this.
A future change should consider whether we really need this at all: it seems that it's just so that OpenVMM in OpenHCL doesn't have to replay the UEFI register state. But OpenVMM already knows so much about how to load UEFI, so it seems kind of silly to pretend that it doesn't know how to set the register state appropriately.
=> loader: simplify handling of multiple VTLs

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs
This is only used for CVM, so now it's in CVM only state.
=> Move tlb_lock_info to CvmPartitionState

openhcl/openhcl_boot/src/main.rs, openhcl/openhcl_boot/src/sidecar.rs
If sidecar is enabled, then pass `boot_cpus=a,b,c` to the Linux kernel, which tells it to boot only the base VP of each sidecar node.
This will be ignored by the current included Linux kernel. A concurrent patch to add support for the boot_cpus option is pending.
=> openhcl_boot: specify boot CPUs when sidecar is enabled

flowey/flowey_lib_hvlite/src/download_openvmm_vmm_tests_vhds.rs
This is just another possible failure path.
=> flowey: pass --skip-version-check to azcopy

flowey/flowey_lib_hvlite/src/download_openvmm_vmm_tests_vhds.rs
We can't diagnose what we can't see.
=> flowey: include all azcopy log output

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_pools.rs, flowey/flowey_lib_common/src/download_azcopy.rs, flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Upgrade azcopy to version 10.27.0 and use large disk linux test runners so that the downloaded VHDs fit. Also makes the flowey download azcopy node arm64 native capable.
=> Upgrade azcopy and use large disk linux test runners

.github/workflows/openvmm-ci.json, .github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.json, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_common/src/download_gh_release.rs, flowey/flowey_lib_common/src/download_mdbook.rs, flowey/flowey_lib_common/src/download_mdbook_admonish.rs, flowey/flowey_lib_common/src/download_mdbook_mermaid.rs, flowey/flowey_lib_common/src/download_protoc.rs, flowey/flowey_lib_hvlite/src/_jobs/cfg_common.rs, flowey/flowey_lib_hvlite/src/download_lxutil.rs, flowey/flowey_lib_hvlite/src/download_openhcl_kernel_package.rs, flowey/flowey_lib_hvlite/src/download_openvmm_deps.rs, flowey/flowey_lib_hvlite/src/download_uefi_mu_msvm.rs
Closes #151 
In the brief window where OpenVMM was on github, but was still closed-source, we used the `gh` CLI in order to properly authenticate with private repos in order to download various artifacts (e.g: the mu_msvm UEFI package, via `xflowey restore-packages` and `xflowey build-igvm`).
Now that we are open-source, we can sidestep the `gh` CLI entirely, and pull public github releases down using `curl`.
This is nice, as it avoids needing uses to log-in to the `gh` CLI tool, making `cargo xflowey restore-packages` a truly "hands off" dev-ex.
=> flowey: use `curl` download public GitHub artifacts (instead of `gh` CLI)

Cargo.lock
This change updates the versions of openssl to the latest available versions.
=> Update openssl to 0.10.68 and openssl-sys to 0.9.104

Cargo.lock, support/inspect/src/defer.rs, support/inspect/src/initiate.rs, support/inspect/src/lib.rs, vm/devices/net/net_consomme/consomme/Cargo.toml, vm/devices/net/net_consomme/consomme/src/lib.rs, vm/devices/net/net_consomme/consomme/src/udp.rs, vm/devices/net/net_consomme/src/lib.rs
Also add in a way to manually recycle a connection via inspect, and add per-connection stats.
As part of this, remove the `std` requirement for failing in `InspectMut` implementations. This is now possible since `Error` is in `core`.
=> consomme: recycle UDP connections on receive error

openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
At some point we'll probably want to do an audit of all hardcoded VTLs to ensure we haven't missed any on our VSM work. Get rid of a few of them now.
=> Remove some hardcoded vtls

openvmm/hvlite_core/src/worker/vm_loaders/igvm.rs, vm/loader/src/paravisor.rs
This is useful for non-VSM-based paravisor configurations.
=> loader: support loading openhcl into VTL0

openvmm/hvlite_entry/src/cli_args.rs, openvmm/hvlite_entry/src/lib.rs
This is useful for testing openvmm boot with non-VSM configurations.
=> openvmm: support adding openhcl devices to VTL0

.github/scripts/add_unsafe_reviewers/requirements.txt
This change updates pyopenssl to the latest available version.
NOTE: the pipeline that currently uses this is currently disabled.
=> Update pyopenssl to version 24.2.1

vm/devices/get/guest_emulation_device/src/lib.rs
The `time` crate refuses to return the current timezone in Linux due to some soundness concerns with calling `localtime_r` concurrently with `std::env::set_var`.
Switching to `jiff` would resolve this, since `jiff` doesn't use `localtime_r` to get the current timezone (and it's just generally better than `time`). But for now, just fall back to UTC when we can't get the timezone (which I suppose could happen for any number of other reasons, anyway).
=> ged: don't panic if the local timezone can't be discovered

openhcl/underhill_attestation/src/lib.rs, openhcl/underhill_attestation/src/secure_key_release.rs
The PR sends the GET event to the host for corresponding errors, which include
- Data-encryption Key (DEK) failures
- VMGS decryption key release failures
=> attestation: Send GET event logs for corresponding errors

openvmm/hvlite_entry/src/cli_args.rs, openvmm/hvlite_entry/src/lib.rs, openvmm/hvlite_entry/src/storage_builder.rs
Offer vmbus serial ports to VTL0 when VTL2 is disabled. Support paravisor storage and networking configuration without VTL2. Allow the UEFI console mode to be set when booting via IGVM.
=> openvmm: support more devices with a VTL0 paravisor

openhcl/underhill_attestation/src/lib.rs, openhcl/underhill_attestation/src/secure_key_release.rs, openhcl/underhill_core/src/emuplat/watchdog.rs, openhcl/underhill_core/src/worker.rs, vm/devices/get/guest_emulation_transport/src/client.rs
This PR adds ` event_log_fatal()` that simplifies the two-call (`event_log()` + `event_log_flush()`) pattern. The PR still retains the two APIs for firmware code that does the log and flush separately.
=> get: add event_log_fatal()

Cargo.lock, vm/devices/net/netvsp/Cargo.toml, vm/devices/net/netvsp/src/lib.rs, vm/devices/net/netvsp/src/rndisprot.rs
Windows guests running isolated expect at least a rev3 response to the hardware offload capabilities query.
Make the constant size derivations easier to understand via offset_of and size_of.
=> netvsp: Use NDIS Offload rev3 to support Windows CVM.

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This removes two more options from UhProcessor, replacing them with getters on Backing. This results in the removal of unwraps in backing-specific code. While it also results in slightly wordier backing-agnostic code, it should optimize better, as each backing can now specialize on whether certain variables are guaranteed to be present or not.
This does not move the equivalent state from UhPartition to BackingShared types, as since UhPartition is not generic I'd expect there to be no meaningful optimization gains from doing so. We could still do so for the sake of organization and self-documentation if we wanted to though.
=> virt_mshv_vtl: Move hv and untrusted_synic into backings

openhcl/hcl/src/protocol.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Implement WBINVD exits by signalling to the kernel to issue the corresponding flush before calling VP.ENTER.
=> openhcl/tdx: implement wbinvd exits

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines_shared/gh_flowey_bootstrap_template.yml, flowey/flowey_lib_common/src/download_azcopy.rs, flowey/flowey_lib_common/src/download_gh_cli.rs, flowey/flowey_lib_common/src/download_gh_release.rs, flowey/flowey_lib_common/src/download_nuget_exe.rs, flowey/flowey_lib_common/src/install_azure_cli.rs, flowey/flowey_lib_common/src/install_rust.rs
While updating to the latest version of the OHCL kernel I noticed that the invocations of curl are currently returning a zero status code when http errors occur. This change adds the [--fail](https://curl.se/docs/manpage.html#-f) flag to all invocations of curl so the curl command itself will fail instead of some future command that relies on the output.
=> CI: Add --fail flag to invocations of curl to make http errors more obvious

openhcl/hcl/src/ioctl.rs, openhcl/underhill_mem/src/lib.rs, openhcl/underhill_mem/src/registrar.rs
At some point, we stopped passing the shared bit down when registering kernel memory. Fix this.
This fixes kernel-mode DMA from TDX VMs.
Note that there are still problems with the overall scenario: the kernel will double buffer through the swiotlb even when the target pages are already shared, and swiotlb is sized by openhcl_boot such that there's not enough memory for all the IO that we may have in flight concurrently.
=> underhill_mem: register memory with proper private/shared bit

openhcl/underhill_attestation/src/key_protector.rs, openhcl/underhill_attestation/src/lib.rs, openhcl/underhill_attestation/src/secure_key_release.rs, vm/devices/get/get_protocol/src/lib.rs, vm/devices/get/guest_emulation_transport/src/error.rs, vm/devices/get/guest_emulation_transport/src/process_loop.rs
Additional error logs during platform initialization.
Example output from a failure.
```
{"VmId":"70970671-31e9-4b7a-b0c8-4de489492d8b","VmName":"fc5daf76-04f4-4fc3-b377-9dcd78b3f4ba","CorrelationId":"00000000-0000-0000-0000-000000000000","Name":"","Target":"underhill_core::worker","Fields":"{\"message\":\"failed to start VM\",\"error\":[\"failed to initialize platform security\",\"failed to request vmgs encryption keys\",\"failed to make an IgvmAttest KEY_RELEASE GET request\",\"IGVM agent returned an error\"]}","Message":"{\"timestamp\":\"13.348678604s\",\"level\":\"ERROR\",\"target\":\"underhill_core::worker\",\"related_activity_id\":\"0829af09-0000-003e-0100-000040000000\",\"fields\":{\"message\":\"failed to start VM\",\"error\":[\"failed to initialize platform security\",\"failed to …
```
=> Additional error logs during platform initialization.

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_hvlite/src/pipelines_shared/gh_pools.rs
Upgrade to ubuntu 22.04 for CI runners and always use a 256GB disk.
=> ci: use bigger linux ci image

openhcl/underhill_core/src/loader/vtl0_config.rs, openhcl/underhill_core/src/loader/vtl2_config/mod.rs, vm/loader/loader_defs/src/paravisor.rs, vm/loader/src/paravisor.rs
Add a magic header to measured information that should be loaded by the host. Additionally, zero out the VTL2 boot data range, to validate that on servicing operations, the host actually deposits new data. 
This fixes the issue on ARM64 where this data was not actually written. Thus, on a cold boot where memory is zeroed, the correct value of vtom = 0 was read, but during a servicing operation because this memory was not part of the launch context, the value could be garbage and cause failures later during initialization. 
In the future, we should just have the bootloader parse the information here, but getting the SLIT and PPTT info reconstructed is a bit trickier. Tracked by #263
=> openhcl: add magic field to measured header in loader info and validate

vm/devices/vmbus/vmbus_client/src/lib.rs
Before:
```
interface_name: "host relay channel - vpci",
```
After:
```
interface_name: "vpci",
```
This is not ambiguous, so I'm not sure why we had the extra text to begin with.
=> vmbus_client: eliminate extra text in inspect output

Guide/src/dev_guide/getting_started/suggested_dev_env.md, Guide/src/dev_guide/tests/vmm.md
Minor updates to the dev guide to provide "quick mode" integration tests + vscode setup. I had ambitions of further refactoring the dev environment docs, but think this incremental update is still useful.
=> Doc updates: vmm tests, vscode settings

Guide/src/reference/openhcl/diag/ohcldiag_dev/perf.md, vm/loader/igvmfilegen/src/file_loader.rs, vm/loader/igvmfilegen/src/main.rs, vm/loader/igvmfilegen/src/vp_context_builder/vbs.rs, vm/loader/igvmfilegen_config/src/lib.rs, vm/loader/manifests/openhcl-aarch64-dev.json, vm/loader/manifests/openhcl-aarch64-release.json, vm/loader/manifests/openhcl-x64-cvm-dev.json, vm/loader/manifests/openhcl-x64-cvm-release.json, vm/loader/manifests/openhcl-x64-dev.json, vm/loader/manifests/openhcl-x64-direct-dev.json, vm/loader/manifests/openhcl-x64-direct-release.json, vm/loader/manifests/openhcl-x64-release.json, vm/loader/manifests/uefi-aarch64.json, vm/loader/manifests/uefi-x64.json, vm/loader/src/importer.rs, vm/loader/src/paravisor.rs, vmm_core/vm_loader/src/lib.rs
Instead of having separate VTL0 and VTL2 fields in the igvmfilegen configuration, have a single "image" field specifying the actual boot image to load. Then, for the case of embedding UEFI firmware or a Linux kernel for OpenHCL to load, have explicit fields within the "openhcl" type of image.
This has a few advantages:
1. It allows a UEFI firmware to be provided even if OpenHCL is being loaded into VTL0 (i.e., for the nested virtualization configuration).
2. It acknowledges that the paravisor needs to understand the nested image type--it's not enough that igvmfilegen knows how to load something into VTL0, because (except for the UEFI case), the paravisor is still quite involved in the load process.
3. It is more flexible for the future. With this model, we can experiment with different, …
=> igvmfilegen: refactor VTL0 image configuration

openhcl/shared_pool_alloc/src/lib.rs, vm/devices/user_driver/src/vfio.rs
DMA buffers are expected to be zeroed out upon allocation
MSFT#53036590
=> shared_pool_alloc: zero out allocated DMA buffers

openhcl/underhill_core/src/worker.rs, vm/devices/storage/disk_blockdevice/src/lib.rs
Work around kernel limitations for ARM64 OpenHCL: always bounce external data in the block device. This prevents the need from the kernel to have visibility into the pages used for VTL0 memory.
=> disk_blockdevice: always bounce block device IO for arm64

openvmm/hvlite_entry/src/tracing_init.rs, vm/devices/get/guest_emulation_log/src/lib.rs
Rename the trace target `underhill_log` to `paravisor_log` to be more generic.
=> guest_emulation_log: rename tracing target to paravisor_log

Cargo.lock, Cargo.toml, openvmm/hvlite_entry/Cargo.toml, openvmm/hvlite_entry/src/cli_args.rs, openvmm/hvlite_entry/src/lib.rs, openvmm/openvmm_resources/Cargo.toml, openvmm/openvmm_resources/src/lib.rs, vm/devices/serial/serial_debugcon/Cargo.toml, vm/devices/serial/serial_debugcon/src/lib.rs, vm/devices/serial/serial_debugcon/src/resolver.rs, vm/devices/serial/serial_debugcon_resources/Cargo.toml, vm/devices/serial/serial_debugcon_resources/src/lib.rs, vmm_core/vm_manifest_builder/src/lib.rs
Ahh, the joys of open-source!
I can finally work on fun openvmm stuff on the weekend from my personal PC 😄
This PR adds simple `debugcon` serial device, originally implemented in bochs, but now widely supported in other VMMs such as QEMU, crosvm, cloud-hypervisor, etc...
It is a no-frills, relocatable, single IO-port mechanism for a Guest to write a steam of bytes to the host. It can be instantiated by passing `--debugcon=port:serialmode` to the CLI (e.g: `--debugcon=0x402,stderr`).
For context: I am playing around with standing up SeaBIOS support in OpenVMM (on the weekends, just for kicks), and SeaBIOS writes a lot of useful debug info to a debugcon at port 0x402. Also, IIUC, OVMF can also be configured to use a debugcon for early-boot debugging, so this device might come in handy later …
=> serial: add debugcon device

Cargo.lock, Guide/src/reference/openvmm/management/cli.md, openvmm/hvlite_entry/src/cli_args.rs, openvmm/hvlite_entry/src/lib.rs, openvmm/hvlite_entry/src/serial_io.rs, openvmm/openvmm_resources/src/lib.rs, petri/src/vm/construct.rs, support/mesh/mesh_protobuf/src/encoding.rs, vm/devices/serial/serial_socket/Cargo.toml, vm/devices/serial/serial_socket/src/lib.rs, vm/devices/serial/serial_socket/src/net.rs
Add support for serial ports listening on TCP sockets instead of just Unix sockets and Windows named pipes.
This is useful for interacting with tools that only support TCP. For example, windbg's EXDI support (used to debug the UEFI firmware) currently only supports TCP. This eliminates the need to use a separate tool to relay Unix sockets/named pipes to TCP sockets.
To use, append something like `--com1 listen=tcp:127.0.0.1:4000` to the command line.
=> openvmm: support TCP listener for serial ports

openhcl/openhcl_boot/src/main.rs, support/mesh/mesh_remote/src/unix_node.rs
See #261 for the reasoning behind this change. This removes two more sources of logs that we don't feel are useful.
=> misc: Reduce mesh and kernel logging on crashes

vm/devices/net/netvsp/src/lib.rs
The `send_indirection_msg` struct is not following Rust conventions. Rename it to make rust-analyzer stop emitting a warning at random times.
(It seems like rustc itself doesn't warn because the struct is `repr(C)`. This is weird.)
=> netvsp: rename internal struct

.github/scripts/add_unsafe_reviewers/add-unsafe-reviewers.py, Cargo.toml, openhcl/build_info/src/lib.rs, openhcl/minimal_rt/src/arch/aarch64/intrinsics.rs, openhcl/minimal_rt/src/arch/x86_64/hypercall.rs, openhcl/minimal_rt/src/arch/x86_64/intrinsics.rs, openhcl/minimal_rt/src/rt.rs, openhcl/openhcl_boot/src/main.rs, openhcl/sidecar/src/arch/x86_64/init.rs, openhcl/sidecar/src/arch/x86_64/mod.rs, support/openssl_crypto_only/src/lib.rs, support/openssl_kdf/src/sys/evp.rs, support/openssl_kdf/src/sys/params.rs, support/pal/src/windows/alpc.rs, support/pal/src/windows/security.rs, support/sparse_mmap/src/lib.rs, support/win_prng_support/src/lib.rs, vm/devices/net/linux_net_bindings/src/gen_if.rs, vm/devices/serial/vmbus_serial_guest/src/lib.rs, vm/devices/storage/disk_vhdmp/src/lib.rs, vm/devices/storage/nvme/src/namespace/reservations.rs, vm/devices/storage/nvme_common/src/lib.rs, vm/devices/storage/nvme_spec/src/nvm.rs, vm/devices/support/fs/plan9/src/protocol.rs, vm/vmgs/vmgs_lib/src/lib.rs, vm/whp/src/api.rs, vmm_core/virt_hvf/src/abi.rs, vmm_tests/vmm_test_macros/src/lib.rs
This PR fixes up the easy issues with Rust 2024 compatibility and enables the lint for it. However it also scopes out some allows for the things that need some more work and focus. #288 is tracking them.
Changes in this PR:
- extern blocks are now unsafe
- `gen` is becoming a reserved keyword, rename variables
- mark unsafe attributes other than linkme's
- resolve the ambiguity of `fn poll` in VmbusSerialDriver
=> Begin working towards Rust 2024 compatibility

.github/workflows/refresh-vso.yml
This change adds a new parameter to the GitHub action responsible for keeping the mirror repo in-sync to allow specifying a branch to sync. This will be useful in the future when we care about mirroring branches other than main.
=> CI: Update refresh-vso.yml to pass the branch to mirror

vmm_core/virt_support_aarch64emu/src/translate.rs
This was ported over from other code but never tested. Fix some bugs.
This is necessary for working gdbstub support.
=> virt_support_aarch64emu: fix page table walking

azure-pipelines/mirror-branch.yaml, codeql3000.yml
This change disables these unneeded checks that that are auto-injected by our ADO organization policy. This saves about 7 minutes of runtime on the mirror-branch pipeline.
=> CI: Disable component governance and codeql3000 on the mirror-branch pipeline

petri/guest-bootstrap/network-config, petri/src/disk_image.rs
speed up ubuntu 24.04 boot in vmm tests by skipping network wait (since there is no network) to workaround https://github.com/canonical/cloud-init/issues/5511
=> ci: speed up ubuntu 24.04 boot in vmm tests

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
This change updates the default branches we run CI and PR on to include `release/*`. This will ensure that future forks of main will inherit the correct PR and CI policy.
=> CI: Add release/* to default CI and PR triggers

.github/workflows/refresh-mirror.yml
This change updates the branch trigger of the refresh-mirror pipeline to the correct branch.
=> CI: Update trigger of refresh-mirror workflow to release/2411

openhcl/rootfs.config, openhcl/underhill_init/src/lib.rs, vmm_tests/vmm_tests/tests/tests/x86_64.rs
The underhill binary was renamed to openvmm_hcl, but its name was not updated in the initrd. As a result, crash dumps reference /bin/underhill, but the symbols are published as openvmm_hcl.dbg. This makes it hard for the debugger to find the appropriate symbols.
Rename the binary within the initrd to be consistent.
=> initrd: rename /bin/underhill to /bin/openvmm_hcl

vm/devices/chipset_resources/Cargo.toml
This one missing feature dep allows the following command to complete successfully on WSL:
`cargo hack --workspace --at-least-one-of grpc,ttrpc --feature-powerset --skip encryption_win check`
We may want to consider fixing the grpc,ttrpc issue (hvlite_entry breaks if --no-default-features is specified), and maybe checking something like this in CI.
=> Add a missing feature dependency

.devcontainer/devcontainer.json, Guide/src/SUMMARY.md, Guide/src/dev_guide/getting_started/devcontainer.md, Guide/src/dev_guide/getting_started/suggested_dev_env.md
This lets you get a codespace up and running, or use the devcontainer vscode extension locally. You probably want to make any codespace have at least 8 VPs, if you plan on actually building anything.  
For local devcontainers, you'll want to clone the repo inside the container volume for filesystem performance reasons. It might also be useful to figure out how to mount the flowey-out directory for running igvm files locally. 
Individual customization (like installing other shells, dotfiles, etc) can be done via the dotfiles repo and install script under your personal codespaces settings, or in the devcontainer extensions settings.
=> repo: add ubuntu devcontainer.json

.devcontainer/devcontainer.json
Turns out that having ssh is useful for gh cli, and use `updateContentCommand` instead for restore-packages, so that rust-analyzer actually works when you connect, instead of you having to restart it because the command hasn't finished.
Also actually restrict codespaces to 8 CPUs or greater, because anything less than that and you might as well just use the vscode web editor, not a codespace.
=> repo: tweak some dev container settings

vmm_core/virt_support_apic/src/lib.rs
When an interrupt is delivered locally (for self IPIs and timers), we don't notify the partition to wake the processor, and so we never scan IRR to find and deliver these interrupts.
Fix this.
=> virt_support_apic: scan IRR for self IPIs and timers

openhcl/bootloader_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/dt.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/host_params/mod.rs, openhcl/openhcl_boot/src/host_params/shim_params.rs, openhcl/openhcl_boot/src/main.rs, openhcl/underhill_core/src/loader/vtl2_config/mod.rs, vm/loader/loader_defs/src/paravisor.rs, vm/loader/loader_defs/src/shim.rs, vm/loader/src/paravisor.rs
Cherry pick of #304 to release/2411
Previously, we put some SNP specific pages into the same VTL2 config region. #265 broke SNP, because this region contains pages that _cannot be_ zeroed, like the VMSA, CPUID pages and secrets pages.
Move those to a new region, that is marked as persisted to both kernelmode and usermode. It is unclear to me if the kernel requires that the CPUID page and secrets page are persisted, but treat them like the VMSA for now.
Fixes #295
=> openhcl/loader: move snp specific pages to new vtl2 reserved region

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vmm_core/virt_mshv/src/lib.rs, vmm_core/virt_support_apic/src/lib.rs, vmm_core/virt_support_x86emu/src/emulate.rs, vmm_core/virt_support_x86emu/tests/tests/checkvtlaccess.rs, vmm_core/virt_support_x86emu/tests/tests/emulate.rs, vmm_core/virt_support_x86emu/tests/tests/translate.rs
When running unenlightened, VMs may try to use XAPIC mode. Wire it up, and fix the instruction emulator code to look at the correct APIC base.
=> virt_mshv_vtl: support XAPIC mode for TDX VMs

Cargo.lock, openhcl/underhill_core/src/worker.rs, vm/aarch64/aarch64defs/src/gic.rs, vm/aarch64/aarch64defs/src/lib.rs, vm/aarch64/aarch64defs/src/psci.rs, vmm_core/src/acpi_builder.rs, vmm_core/virt_hvf/Cargo.toml, vmm_core/virt_hvf/src/lib.rs, vmm_core/virt_support_gic/Cargo.toml, vmm_core/virt_support_gic/src/lib.rs, vmm_tests/petri_artifacts_vmm_test/src/lib.rs
This fixes guest-initiated power off, and it gets us closer to multi-proc support.
The GIC code is still very much prototype quality.
The `aarch64::uefi_aarch64_frontpage` test now passes with virt_hvf.
=> virt_hvf: Add PSCI support and extend GIC

vm/devices/firmware/firmware_uefi/src/service/nvram/mod.rs
Don't change the attributes on SECURE_BOOT until all deployed images have the ability to rewrite variable attributes.
=> Support older OpenVMM logic for SECURE_BOOT

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/hv1/hv1_emulator/src/hv.rs, vm/hv1/hv1_emulator/src/synic.rs, vm/hv1/hvdef/src/lib.rs, vmm_core/virt_support_apic/src/lib.rs
When VTL 1 has an interrupt pending, and we're planning on running VTL 0, check to see if we should preempt that and run VTL 1 to deliver the interrupt instead. Also, sets VINA when VTL 0 has a high enough priority interrupt and we're running VTL 1. Also resets VINA if auto reset is asked for. 
Note that since we don't have a way for the guest to set its VINA configuration yet that portion of the code is functionally dead (enabled will never be true). That's coming soon.
=> virt_mshv_vtl: Add VTL 1 interrupt preemption and VINA support

openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/options.rs, openhcl/underhill_core/src/worker.rs, openhcl/underhill_mem/src/init.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs, vm/hv1/hv1_emulator/src/cpuid.rs, vmm_core/virt_whp/src/lib.rs
Add `OPENHCL_HIDE_ISOLATION=1` command line option to hide the isolation type from the guest and to disable support for isolation-related enlightenments such as changing host memory protections on pages.
This allows a VM to run without any shared memory, using normal architectural and Hyper-V interfaces to interact with devices.
This does not work with the vmbus relay, since the relay relies on the guest knowing to put the ring buffer in shared memory. Similarly, this doesn't work with VTL0 assigned PCI devices. Nor does it work with the net_mana backend, since the MANA driver relies on directly DMAing to shared memory.
With this, we can boot modern and old guests alike, without enlightenments, on TDX. SNP is not tested and is unlikely to work without similar fixups.
=> openvmm_hcl: add option to hide isolation from the guest

Guide/src/dev_guide/getting_started/build_ohcl_kernel.md
L1 kernels fail to boot when the host hypervisor enforces isolation features for confidential VMs. The reason of the failed boot is not obvious and debugging tools may provide no hits (e.g., WinDBG does not show any kernel boot logs).
The kernel fails to boot because the necessary isolation features are not enabled in the default hcl-*.config files. The script merge-cvm-config.sh selects this features.
Document this extra step.
=> guide: document the use of CVM kernel config fragments

openhcl/hcl/src/ioctl.rs
#125 introduced using a generic, VTL-aware hypercall to get and set VTL-private registers. Unfortunately, it introduced multiple sources of truth about how certain registers (in particular, Xfem) should be handled. This change modifies ProcessorRunner::set_reg and get_reg to route any VTL-shared register through the special kernel ioctl, and use the generic hypercall only for registers that are definitely VTL-private. This ensures that the decision made by get_reg and set_reg matches the assert in, e.g., get_vp_register_for_vtl.
=> Use kernel ioctl for getting/setting all VTL-shared registers

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/hv1/hv1_emulator/src/hv.rs, vm/hv1/hv1_emulator/src/synic.rs, vm/hv1/hvdef/src/lib.rs, vmm_core/virt/src/x86/mod.rs
We do this by just converting the register index to an msr index and calling the existing read/write msr functions. This comes along with a refactor to the timer MSRs to move their control inside the synic, making read/write_msr more complete.
A follow up PR will tackle the apic base register.
=> Support get/set_vp_register for synic registers

.github/labeler.yml, .github/workflows/labeler.yml
Apply the `release_2411` label to PRs targeting the `release/2411` branch.
Apply the `Guide` label to PRs modifying the developer guide.
See <https://github.com/actions/labeler>.
=> github: add labeler action

rust-toolchain.toml
This helps ensure that we don't accidentally take rust version updates to the release branch, or write code that depends on a newer version to begin with.
=> Lock the release branch to the current Rust version

openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs
There may be pending deferred actions (i.e., synic events to signal) on the VP at time of servicing. Ordinarily, these are flushed the next time we run the VP, but there is no next time when saving for servicing. These actions must be flushed to the actual partition state to ensure we don't drop a signal, which would cause a guest hang.
This fixes a regression from a previous change. Previously, the `ProcessorRunner` was dropped before a servicing operation, and the `Drop` implementation would flush deferred actions. Now, the runner never gets dropped until the partition is torn down. Add a path to explicitly flush deferred actions before saving.
=> virt_mshv_vtl: flush deferred actions during servicing

vm/whp/src/abi.rs, vmm_core/virt_whp/src/lib.rs
New builds of WHP on aarch64 require that the VMM configure the PMU interrupt ID. This PR configures it using the same value that Hyper-V uses. Tested by booting a Linux image on aarch64 using a recent Windows build.
=> Adding WHV_ARM64_IC_GIC_V3_PARAMETERS::GicPpiPerformanceMonitorsInterrupt to aarch64 unstable_whp

vm/devices/firmware/firmware_uefi/src/service/nvram/mod.rs
Don't change the attributes on SECURE_BOOT until all deployed images have the ability to rewrite variable attributes.
=> Support older OpenVMM logic for SECURE_BOOT (#209)

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Add support for calling get/set_vp_register on the ApicBase register for CVMs. This required moving the lapics into cvm state, which necessitated a lot of churn, but ultimately this is a pretty small change.
=> virt_mshv_vtl: Add cvm support for get/set ApicBase register

petri/src/vm/start.rs
This is useful for tests where the first boot attempt is expected to not succeed, but pipette functionality is still desired. This will be used by upcoming TPM tests that are encountering a first-time-setup-reboot in GRUB and/or UEFI-shim.
=> Add functionality for lazy pipette connections

Cargo.lock, Cargo.toml, Guide/src/dev_guide/dev_tools/hypestv.md, hyperv/tools/hypestv/Cargo.toml, hyperv/tools/hypestv/src/windows/mod.rs, hyperv/tools/hypestv/src/windows/vm.rs, openvmm/openvmm_entry/Cargo.toml, openvmm/openvmm_entry/src/lib.rs, support/console_relay/Cargo.toml, support/console_relay/src/lib.rs, support/console_relay/src/unix.rs, support/console_relay/src/windows.rs
Lift the console relay support from OpenVMM and use it to launch serial ports in separate windows. This replaces the need to separately use `hvc` for interactive serial ports.
To use:
```
serial 1 term
```
Also, add support for `quit`, and rename the `output` serial mode to `log`.
=> hypestv: support relaying serial ports to new windows

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs
Adds support for VsmVpSecureConfigVtl0 register as part of hypercall get/setvpregister handling.
Tested:
SNP
SNP + Guest VSM
=> SNP guest VSM: support VsmVpSecureConfigVtl0 register

vm/devices/vmbus/vmbus_server/src/lib.rs
This PR addresses an issue where the synic event was lost during the save process. To mitigate this issue during the restore process, we have introduced a new field lost_synic_bug_fixed in the SavedState structure. The lost_synic_bug_fixed field will indicate whether the issue was fixed in save code path. During the restore process, we check if the field is not set then unstick_channels() function is called to mitigate the issue.
In below kmsg traces, yellow line shows we check the field to see if need call unstick_channels and green line shows we did hit the issue where the rings were not empty and need signal the guest:
=> vmbus_server: call unstick_channels to mitigate the lost synic issue

Cargo.lock, support/ucs2/Cargo.toml, support/ucs2/src/lib.rs, vm/devices/firmware/firmware_uefi/Cargo.toml
No one actually relies on this, and the mesh encoding for it is kind of sus.
=> ucs2: remove optional mesh derive

Cargo.lock, hyperv/tools/hypestv/Cargo.toml, hyperv/tools/hypestv/src/windows/hyperv.rs, hyperv/tools/hypestv/src/windows/mod.rs, hyperv/tools/hypestv/src/windows/vm.rs
Normally, `kill` will power off the VM using `hvc.exe`, which uses the VMMS WMI API internally. In some cases, the VMMS thinks the VM is not in a state where it can be powered off even though it can be, e.g. if there is a pending shutdown request.
Add a `force` flag that uses the HCS API instead (via `hcsdiag.exe`), which skips the VMMS state machine evaluation and just stops the worker process.
=> hypestv: add force flag to `kill` command

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, .github/workflows/unsafe-reviewers.yml, flowey/flowey_cli/src/pipeline_resolver/github_yaml/github_yaml_defs.rs, flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs, flowey/flowey_core/src/pipeline.rs, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs
This changes our CI to not run on draft pull requests and marks CI as "skipped." When the PR is marked as ready for review CI should run. 
To do so, we add an `if` conditional to every job that checks for draft status. In addition, if an override exists (currently only one job uses the override), we'll concatenate the conditionals. The brackets in the conditional have been removed as they're unnecessary ([github actions automatically treat if blocks as being enclosed in brackets](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif)) which makes the concatenation much easier.
=> Don't run CI for draft PRs

openhcl/underhill_core/src/worker.rs, vm/devices/get/guest_emulation_device/src/lib.rs
We know how large it is, but log it so it's discoverable. 
In the future, we are probably moving to a model where we do not send the saved state to the host. This will help us decide how large to size a reserved memory range inside OpenHCL.
=> openhcl: log how large the saved state buffer is for servicing

support/mesh/mesh_channel/Cargo.toml, support/mesh/mesh_protobuf/Cargo.toml, support/mesh/mesh_protobuf/src/buffer.rs, support/mesh/mesh_protobuf/src/encode_with.rs, support/mesh/mesh_protobuf/src/encoding.rs, support/mesh/mesh_protobuf/src/inplace.rs, support/mesh/mesh_protobuf/src/lib.rs, support/mesh/mesh_protobuf/src/message.rs, support/mesh/mesh_protobuf/src/prost.rs, support/mesh/mesh_protobuf/src/protobuf.rs, support/mesh/mesh_protobuf/src/protofile/mod.rs, support/mesh/mesh_protobuf/src/protofile/writer.rs, support/mesh/mesh_protobuf/src/table/decode.rs, support/mesh/mesh_protobuf/src/table/encode.rs, support/mesh/mesh_protobuf/src/time.rs
Support encoding/decoding protobuf messages from `no_std` environments.
We don't have an immediate use case for this, but there is some talk of using this within the boot loader (which would need a global allocator).
=> mesh_protobuf: support building with no_std

Cargo.lock, Guide/src/dev_guide/dev_tools/hypestv.md, hyperv/tools/hypestv/Cargo.toml, hyperv/tools/hypestv/src/windows/completions.rs, hyperv/tools/hypestv/src/windows/mod.rs, hyperv/tools/hypestv/src/windows/vm.rs
Add kmsg output options for seeing paravisor logs in real time.
Also move existing paravisor commands (including paravisor modes for `inspect` and `start`) under a new `paravisor` subcommand (alias `pv`). This is just as short as using `-p`, and it's easier to understand and extend.
=> hypestv: add paravisor kmsg output

build_support/setup_windows_cross.sh
This resolves the error handling in the setup_windows_cross.sh script which was referencing a deleted file.
=> CI: Fix error handling in build_support/setup_windows_cross.sh

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/aarch64.rs, openhcl/hcl/src/ioctl/snp.rs, openhcl/hcl/src/ioctl/tdx.rs, openhcl/hcl/src/ioctl/x64.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Cherry-pick PRs 125 and 360 to release/2411.
Modify ProcessorRunner::get_reg and ProcessorRunner::set_reg to use a
direct hypercall when possible, instead of our dedicated
get/set-register ioctl. Certain registers have special handling in the
kernel ioctl handler. Those are left as-is. Get/set for other registers
is now made with a direct hypercall.
This has the benefit of being VTL-aware, so this change also adds a VTL
parameter.
This change also removes some proliferation of
(g|s)et_vp_registers?(_inner)?, hopefully making it simpler and cleaner.
The singular (g|s)et_vp_register is left as an ergonomic convenience.
One unaddressed capability is making ioctls/hypercalls on a batch of
registers. This is not strictly a regression, because
MSHV_VP_MAX_REGISTERS was previously 1.
This change …
=> Use VTL-aware direct hypercall to get/set registers when possible

openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs
Cherry-pick save path fix of lost synic issue.
There may be pending deferred actions (i.e., synic events to signal) on
the VP at time of servicing. Ordinarily, these are flushed the next time
we run the VP, but there is no next time when saving for servicing.
These actions must be flushed to the actual partition state to ensure we
don't drop a signal, which would cause a guest hang.
This fixes a regression from a previous change. Previously, the
`ProcessorRunner` was dropped before a servicing operation, and the
`Drop` implementation would flush deferred actions. Now, the runner
never gets dropped until the partition is torn down. Add a path to
explicitly flush deferred actions before saving.
=> Cherry-pick: virt_mshv_vtl: flush deferred actions during servicing

openhcl/underhill_core/src/dispatch/vtl2_settings_worker.rs, vm/devices/storage/disk_backend/src/lib.rs, vm/devices/storage/disk_blockdevice/src/lib.rs, vm/devices/storage/disk_crypt/src/lib.rs, vm/devices/storage/disk_nvme/src/lib.rs, vm/devices/storage/disk_prwrap/src/lib.rs, vm/devices/storage/disk_striped/src/lib.rs, vm/devices/storage/scsidisk/src/getlbastatus.rs, vm/devices/storage/scsidisk/src/lib.rs, vm/devices/storage/scsidisk_resources/src/lib.rs
There is no support in any backend for querying LBA status, and the trait for querying it is not really suitable for use with async disks. All devices that opt into supporting LBA status queries just end up using the default implementation, which reports that all blocks are fully mapped.
Perhaps a future change will actually support these queries properly. For now, move this functionality entirely into the SCSI emulator.
=> disk_backend: remove GetLbaStatus

Guide/src/reference/openvmm/management/cli.md, openvmm/openvmm_entry/src/cli_args.rs, openvmm/openvmm_entry/src/lib.rs, openvmm/openvmm_entry/src/ttrpc/mod.rs, vm/devices/virtio/virtio_resources/src/lib.rs, vm/devices/virtio/virtiofs/src/resolver.rs
Add mount options to the virtiofs resource.
Allow the virtiofs mount options to be provided on the command line. To make this work cleanly, change the `:` separator to `,`.
=> virtiofs: add mount options to resource

vm/devices/storage/disk_backend/src/lib.rs, vm/devices/storage/disk_blob/src/lib.rs, vm/devices/storage/disk_blockdevice/src/lib.rs, vm/devices/storage/disk_crypt/src/lib.rs, vm/devices/storage/disk_file/src/lib.rs, vm/devices/storage/disk_get_vmgs/src/lib.rs, vm/devices/storage/disk_layered/src/lib.rs, vm/devices/storage/disk_nvme/src/lib.rs, vm/devices/storage/disk_prwrap/src/lib.rs, vm/devices/storage/disk_ramdisk/src/lib.rs, vm/devices/storage/disk_striped/src/lib.rs, vm/devices/storage/disk_vhd1/src/lib.rs, vm/devices/storage/disk_vhdmp/src/lib.rs, vm/devices/storage/nvme/src/namespace.rs, vm/devices/storage/scsidisk/src/lib.rs, vm/devices/storage/scsidisk/src/scsidvd/mod.rs, vm/devices/storage/scsidisk/src/tests/test_helpers.rs, vm/devices/storage/scsidisk/src/unmap.rs
Instead of using an IDET to model the unmap behavior of the disk, just use plain methods. Unmap is pretty fundamental to disks these days, so it's not really optional to think about it. And the no-op implementation is a legal implementation, so the IDET doesn't buy us much.
=> disk_backend: unify unmap handling between DiskIo and LayerIo

support/mesh/mesh_derive/src/lib.rs, support/mesh/mesh_protobuf/src/lib.rs, support/mesh/mesh_protobuf/src/table/mod.rs
Make it clearer what the user must do when they try to derive `MeshPayload` with fields that are incompatible (either because they do not have a mesh encoding or because they do not have a _stable_ mesh encoding).
=> mesh_derive: improve compile-time diagnostics

Cargo.lock, openhcl/underhill_core/src/worker.rs, openvmm/hvlite_core/Cargo.toml, openvmm/hvlite_core/src/worker/dispatch.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
Enabling new VmBus feature flags can lead to issues when rolling back to an older version of OpenHCL. For this reason, this change disables the client ID feature flag until a better solution is available.
Isolated guests are excluded from this as they do not currently support servicing.
=> VmBus: disable client ID support in OpenHCL when not isolated

openhcl/underhill_core/src/worker.rs, vm/devices/get/guest_emulation_device/src/lib.rs
We know how large it is, but log it so it's discoverable. 
In the future, we are probably moving to a model where we do not send the saved state to the host. This will help us decide how large to size a reserved memory range inside OpenHCL.
Cherry pick of #400
=> openhcl: log how large the saved state buffer is for servicing (#400)

Cargo.lock, Cargo.toml, openhcl/underhill_core/Cargo.toml, openhcl/underhill_core/src/worker.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client_hcl/Cargo.toml, vm/devices/vmbus/vmbus_client_hcl/src/lib.rs, vm/devices/vmbus/vmbus_relay/Cargo.toml, vm/devices/vmbus/vmbus_relay/src/lib.rs, vm/devices/vmbus/vmbus_relay_intercept_device/Cargo.toml, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
Instead of hard-coding the interactions with the Linux HCL driver, go through a trait object. Extend the same `SynicClient` trait that we already use.
After additional changes, this trait will be consumed only by `vmbus_client` and won't be used in `vmbus_relay` or `vmbus_relay_intercept_device` at all.
=> vmbus_relay: split HCL driver interactions to new crate

Cargo.lock, openhcl/page_pool_alloc/Cargo.toml, openhcl/page_pool_alloc/src/lib.rs, openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/servicing.rs, openhcl/underhill_core/src/worker.rs
Support save restore for the page_pool_alloc crate. This allows save restore of the shared visibility pool.
A future PR will add support for a private page pool to be used by AK cert renewal and other usages.
=> openhcl/page_pool_alloc: support save restore

openhcl/openhcl_boot/src/arch/x86_64/tdx.rs, openhcl/openhcl_boot/src/main.rs, vm/x86/tdcall/src/lib.rs
In the current implementation, boot times are reported in the device tree only for non-hw-isolated vms by calling tsc refcount. 
On TDX-based VMs, tsc ref time is calculated by:
1. Reading tsc 
2. Getting the tsc frequency using TDCALL to read HV_X64_MSR_TSC_FREQUENCY
Cherry pick of #346
=> Added code to get the tsc time on HW-isolated VMs (TDX) - Issue 345

openhcl/hcl/src/lib.rs
This ensures that GuestVtl always matches Vtl.
=> Assign hardcoded values to GuestVtl

openhcl/host_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/cmdline.rs, openhcl/openhcl_boot/src/dt.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/host_params/mod.rs, openhcl/openhcl_boot/src/main.rs, openhcl/openhcl_boot/src/sidecar.rs, openhcl/underhill_core/src/dispatch/mod.rs, vm/devices/get/get_protocol/src/lib.rs, vm/devices/get/guest_emulation_device/src/lib.rs, vm/devices/get/guest_emulation_transport/src/process_loop.rs
Some additional cleanup of the private pool and fixes with keep alive on openvmm, and enable using the private pool via cmdline.
Do not save the pool state if we are not doing keep alive, as no device should have allocations that need persisting. Fix advertising keep alive support on openvmm because it doesn't work yet.
=> openhcl: cleanup private page pool changes 

openhcl/minimal_rt/src/arch/x86_64/hypercall.rs, openhcl/sidecar/src/arch/x86_64/init.rs, openhcl/sidecar/src/arch/x86_64/vp.rs
Fix new warnings in sidecar from Rust 1.83 getting stricter around the handling of mutable statics. The methods previously being called would automatically create references. We shouldn't do that.
=> Fix incidental references to static muts in sidecar

openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/options.rs, openhcl/underhill_core/src/worker.rs, vm/devices/get/get_protocol/src/lib.rs, vm/devices/get/guest_emulation_device/src/lib.rs
NVMe keep alive requires host changes. Make this experimental feature opt in only via environment arg. 
Additionally revert the get protocol changes. The protocol was specified incorrectly and we cannot have a flag that must be set to 1 to get the old behavior. This fixes servicing on older hosts that do not know how to report this flag.
=> openhcl: make nvme keep alive enabled only via environment arg

Cargo.lock, openhcl/page_pool_alloc/Cargo.toml, openhcl/page_pool_alloc/src/lib.rs
Support save restore for the page_pool_alloc crate. This allows save restore of the shared visibility pool.
A future PR will add support for a private page pool to be used by AK cert renewal and other usages.
NOTE: This is a backport of #418 that does not include the underhill_core changes. This is to allow future cherry-picks to apply cleanly, but we do not want to actually support save restore of the pool in underhill_core, as it's unneeded in release/2411.
=> openhcl/page_pool_alloc: support save restore (#418)

openhcl/bootloader_fdt_parser/src/lib.rs, openhcl/page_pool_alloc/src/lib.rs, openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/loader/vtl2_config/mod.rs, openhcl/underhill_core/src/worker.rs, vm/loader/loader_defs/src/shim.rs
Remove the fixed pool alloc that was temporarily added for the POC NVMe keep alive PR.
Cleanup a few other things as well.
Fixes #443
Backport of #450
=> openhcl: remove fixed_pool_alloc, replace with page_pool_alloc (#450)

openhcl/host_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/cmdline.rs, openhcl/openhcl_boot/src/dt.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/host_params/mod.rs, openhcl/openhcl_boot/src/main.rs, openhcl/openhcl_boot/src/sidecar.rs, openhcl/underhill_core/src/dispatch/mod.rs, vm/devices/get/get_protocol/src/lib.rs, vm/devices/get/guest_emulation_device/src/lib.rs, vm/devices/get/guest_emulation_transport/src/process_loop.rs
Some additional cleanup of the private pool and fixes with keep alive on openvmm, and enable using the private pool via cmdline.
Do not save the pool state if we are not doing keep alive, as no device should have allocations that need persisting. Fix advertising keep alive support on openvmm because it doesn't work yet.
NOTE: Backport commit from main that has dropped changes that do not matter for release/2411.
Backport of #461
=> openhcl: cleanup private page pool changes  (#461)

openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
We were previously missing the crash control registers and MTRRs, but we believe both of these to be non-critical, so this shouldn't be too big a deal.
I'm planning a follow-up change to move PAT out of CacheControl and into its own thing, the cases where we touch it are too separate from when we touch the MTRRs.
=> Cleanup comments and add missing fields to UhProcessor's SaveRestore impl

vm/devices/get/vtl2_settings_proto/src/lib.rs
"Fixes" some more 1.83 warnings.
=> Allow a clippy warning in pbjson generated code

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This avoids doing some unnecessary work in ARM instruction emulation, moves some emulation-only state to actually only exist during emulation, and lays some groundwork for a similar mechanism to exist in the future in x86 backings (eg TDX).
=> virt_mshv_vtl: add a new emulation register cache mechanism, and cleanup ARM to use it

openhcl/underhill_core/src/loader/mod.rs, vm/devices/get/get_protocol/src/dps_json.rs, vm/devices/get/guest_emulation_transport/src/api.rs, vm/devices/get/guest_emulation_transport/src/client.rs, vm/loader/src/uefi/config.rs
Add generic ACPI tables from DevicePlatformSettings to the UEFI config blob. UEFI currently only supports specific tables, so this is limited to HMAT, IORT, MCFG, and SSDT for now.
=> Add generic ACPI tables from DPS to UEFI config

openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs
Cherry pick of #479
The behavior is fine as is, but document why.
=> 2411: Clean up two comments for ARM guest vsm

Cargo.lock, Cargo.toml, openhcl/lower_vtl_permissions_guard/Cargo.toml, openhcl/lower_vtl_permissions_guard/src/device_dma.rs, openhcl/lower_vtl_permissions_guard/src/lib.rs, openhcl/underhill_core/Cargo.toml, openhcl/underhill_core/src/worker.rs, vm/devices/user_driver/src/memory.rs, vm/devices/vmbus/vmbus_relay_intercept_device/Cargo.toml, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
Move the vmbus_relay_intercept_device VTL permissions guard to its own crate. It will be used for the GET in the AK cert PR, because the protocol requires the pages to have no VTL protections. Provide a wrapped interface so the caller just needs a memory block and otherwise the lowering of VTL permissions is invisible to the device.
Note that we change the error trace to a panic, as any failure to rollback should be fatal to the system.
Backport of #488.
=> devices: move vtl permissions guard to its own crate (#488)

openhcl/openhcl_boot/src/host_params/dt.rs
This is a release/2411 only change.
Set the private pool to 1 page on non isolated VMs to support AK cert renewal. This is safe to do, because we do not support live DMA on these ranges across servicing, removing the need save restoring these allocations, as we do not allow this request to be in flight while servicing.
=> openhcl_boot: set private pool size to 1 page for ak cert

petri/src/vm/start.rs
This is useful for tests where the first boot attempt is expected to not succeed, but pipette functionality is still desired. This will be used by upcoming TPM tests that are encountering a first-time-setup-reboot in GRUB and/or UEFI-shim.
Cherry pick of #381
=> Add functionality for lazy pipette connections (#381)

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, vm/hv1/vtl_array/src/lib.rs
It seems that we will be unable to make these go away completely, though we may be able to shrink them, so save them going forward.
=> virt_mshv_vtl: Save the vmbus message queues during SaveRestore

.github/workflows/unsafe-reviewers-clone.yml, .github/workflows/unsafe-reviewers.yml
This change enables a workflow that automatically requests a review from `openvmm-unsafe-approvers` if any unsafe code is introduced as part of a change.
=> Re-enable unsafe reviewers check

flowey/flowey_cli/src/cli/mod.rs, support/ci_logger/src/lib.rs
=> flowey: Avoid calling env::set_var

Cargo.lock, vm/devices/pci/pci_core/Cargo.toml, vm/devices/pci/pci_core/src/bar_mapping.rs, vm/devices/pci/pci_core/src/cfg_space_emu.rs, vm/devices/pci/pci_core/src/spec.rs, vm/devices/pci/vpci/src/device.rs, vm/devices/storage/ide/src/lib.rs, vm/devices/user_driver/src/emulated.rs, vm/devices/virtio/virtio/src/common.rs, vmm_core/virt_whp/src/device.rs
Part of moving all of our bitfield types to bitfield-struct. Only IDE is left I think. There could definitely be more cleanup here to make things more idiomatic, but I'm just trying to do a minimum viable change here for now.
=> Move PCI from bitflags to bitfield-struct

openhcl/underhill_core/src/worker.rs, openhcl/underhill_init/src/lib.rs
Part of https://github.com/microsoft/openvmm/issues/288
=> uh_init: Handle safety around set_var

support/serde_helpers/src/lib.rs, vm/devices/get/get_protocol/src/dps_json.rs
Adds a new vec_base64_vec module for deserializing a Vec of Vec's. Used for the ACPI tables.
=> Properly serialize ACPI tables

openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/options.rs
Instead, just make our own environment clone. With additional parameters! And annoying type conversions!
Part of #288
=> uh_core: Don't modify the environment for start requests

xsync/Cargo.lock
Pull the latest version of url to address [Dependabot #1](https://github.com/microsoft/openvmm/security/dependabot/1)
=> Update url to 2.5.4

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This cleans up some weirdness around things like "can you be idle and halted at the same time?". This needs some very careful review, as it does change some state transitions slightly.
=> Replace LapicState's three bools with the enum they represent

.github/scripts/add_unsafe_reviewers/add-unsafe-reviewers.py, .github/workflows/unsafe-reviewers.yml
#503 tried to re-enable the unsafe reviewers script but had it had a few issues:
1. It was diffing with `origin/main`, which meant that if a PR hadn't merged main the diff could contain changes that weren't introduced in the PR.
2. When assigning the review, it was unable to find the `openvmm-unsafe-approvers` team.
To try and fix those issues this change does the following:
1. It computes the merge base of the PR using `git merge-base` to more accurately replicate the GitHub diff
2. The team has been changed from `openvmm-unsafe-approvers` to `@microsoft/openvmm-unsafe-approvers`
I tested this on my fork by pushing a change to my main with unsafe changes and running the action without merging main on a PR on my fork. I verified that the unsafe change on main wasn't triggering the unsafe …
=> ci: fixes for issues with unsafe reviewers script

Cargo.lock, Cargo.toml, vm/devices/storage/ide/Cargo.toml, vm/devices/storage/ide/src/drive/atapi_drive.rs, vm/devices/storage/ide/src/drive/hard_drive.rs, vm/devices/storage/ide/src/lib.rs, vm/devices/storage/ide/src/protocol.rs
The last bit of making our code fully bitflags-free and unified.
=> Convert IDE from bitflags to bitfield-struct, and remove bitflags entirely

vm/loader/manifests/openhcl-aarch64-dev.json, vm/loader/manifests/openhcl-aarch64-release.json
Use the Shared Visibility pool on aarch64. For reasons that we do not yet fully understand, we think the kernel running in OpenHCL is moving the physical pages that the locked memory allocator queried at boot.
This shows up in two ways:
* the nvme_driver reads completed `cid`s that it did not send, and
* the nvme device thinks that the driver sent it invalid prp lists. IO fails with `PRP_OFFSET_INVALID`.
This change makes the symptoms go away, and we will continue to investigate to get root cause.
By passing `OPENHCL_ENABLE_SHARED_VISIBILITY_POOL=1` in the openhcl command line, a shared
visibility pool will exist and consequently dma devices will use it.
=> openhcl: use shared visibility pool for aarch64 dma

openhcl/underhill_core/src/worker.rs
Previously, device_dma was hard-coded to 10MB, which is insufficient for larger VM sizes.
This change accounts for the correct (currently) DMA size per device, but still doesn't have context on the number of required devices.
=> Modify the shared memory DMA heuristic to allow larger VM sizes, until we can get better information from the host 

vm/devices/net/gdma/src/queues.rs, vm/devices/net/mana_driver/src/queues.rs, vm/devices/storage/disk_nvme/nvme_driver/src/queues.rs, vm/devices/storage/nvme/src/queue.rs
The NVMe completion entry is a 16-byte value, and it contains a phase bit that the NVMe driver reads to determine when a completion in the queue is valid. To ensure the driver observes a consistent completion entry, the phase bit must be written by the device _after_ the rest of the entry, and it must be read by the driver _before_ the rest.
The memory access machinery in OpenVMM does not provide many ordering guarantees, especially on ARM64. Ensure accesses are performed in the right order via two atomic 8-byte accesses, plus proper fences, in the NVMe emulator and driver.
There's a similar bug in MANA. Fix this, too.
Cherry picked from #506
=> nvme,mana: ensure completions are read and written in order (#506)

openhcl/underhill_core/src/worker.rs
CP from (#542)
Previously, device_dma was hard-coded to 10MB, which is insufficient for larger VM sizes.
This change accounts for the correct (currently) DMA size per device, but still doesn't have context on the number of required devices.
=> Modify the shared memory DMA heuristic to allow larger VM sizes, until we can get better information from the host

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs, flowey/flowey_lib_hvlite/src/download_openhcl_kernel_package.rs
This change updates the Linux kernel to the latest release which contains upstream latest stable fixes.
=> Update OHCL kernel to 6.6.63.1

openvmm/hvlite_core/src/partition.rs, vmm_core/virt_hvf/src/lib.rs, vmm_core/virt_kvm/src/arch/x86_64/mod.rs, vmm_core/virt_mshv/src/lib.rs, vmm_core/virt_whp/src/lib.rs
Taking suggestions from running `cargo xtask fmt --fix`. I'm a little surprised that others aren't running into this (and I thought our CI required `cargo xtask fmt` to be clean); please let me know if you suspect some non-determinism.
=> automatic cargo xtask fmt fixups

vmm_tests/vmm_tests/tests/tests/x86_64.rs
The first one is fixed, the comment is no longer needed. The second was referencing an issue in our old staging repo, not the ported version in this repo.
=> Fixup some vmm test comments

vm/vmcore/guestmem/src/lib.rs
When running tests under miri, the `sparse_mmap` try-copy functionality can't work. However, some tests allocate `GuestMemory` objects and then never access the memory. Allow these tests to run under miri by skipping `sparse_mmap` initialization.
=> guestmem: skip sparse_mmap init under miri

support/pal/pal_async/src/unix/epoll.rs
The epoll backend for `pal_async` registers an eventfd for waking up due to a waker, but it neglects to pass the `EPOLLET` (edge triggered) flag when registering it. Miri, it turns out, supports epoll, but it only supports `EPOLLET` registrations.
Pass `EPOLLET` for the wake event. This works fine--we are already handling the wake event in an edge-triggered compatible way.
This allows `#[async_test]` tests to run under miri on Linux.
=> pal_async: support running under miri

support/mesh/mesh_channel/src/lib.rs, support/mesh/mesh_process/src/lib.rs
Instead of deriving a protobuf message encoding for oneshot and SPSC channels, use the port field encoding.
This makes messages smaller and reduces codegen size. There's reason to believe it should improve compile times and runtime performance as well.
MPSC channels still require a message encoding. This could be fixed, but soon we will just replace the implementation entirely.
=> mesh_channel: use port encoding for channels

support/mesh/mesh_channel/src/bidir.rs, support/mesh/mesh_channel/src/cell.rs, support/mesh/mesh_channel/src/pipe.rs, support/mesh/mesh_node/src/local_node.rs, support/mesh_tracing/src/bounded.rs
When a message arrives on a port, the port handler processes it synchronously. Allow the handler to report back an error, failing the port. This allows us to stop port processing immediately rather than risk that an important message be silently dropped.
=> mesh: propagate errors back from port handlers

support/mesh/mesh_node/src/local_node.rs
`Port` is embedded in lots of objects. Save 8 bytes per `Port` at the cost of a little bit of unsafe code, needed to destructure `Port` without calling `drop` in some paths.
=> mesh_node: remove extra bools on `Port`

support/mesh/mesh_remote/Cargo.toml, support/mesh/mesh_remote/src/alpc_node.rs, support/mesh/mesh_remote/src/unix_node.rs
When a mesh connection is established, an initial port pair is registered in the leader and follower processes. This port pair is used to exchange an initial message and is then reused as the user port, by bridging the initial port and the user port.
This reuse of a port for a different purpose is dangerous, because it assumes that no extraneous messages are still in a queue somewhere. This is true with today's `mesh_channel` implementation but is hard to guarantee in general.
Instead of reusing the initial port via bridging, just send the user port as part of the initial message. This is simpler to reason about and is probably roughly as efficient.
=> mesh_remote: don't bridge initial port with user port

Cargo.toml, xtask/src/tasks/fmt/unused_deps.rs
Let's make sure we don't end up updating this accidentally.
=> Pin our tracing-core dep due to binary size concerns

openhcl/build_info/src/lib.rs, openhcl/minimal_rt/src/arch/aarch64/intrinsics.rs, openhcl/minimal_rt/src/arch/x86_64/intrinsics.rs, openhcl/minimal_rt/src/rt.rs, support/openssl_crypto_only/src/lib.rs, support/win_prng_support/src/lib.rs, vm/vmgs/vmgs_lib/src/lib.rs
Part of #288. This is not yet enforced by clippy (https://github.com/rust-lang/rust-clippy/issues/13316), but we should be doing it anyways.
=> Add safety comments to unsafe attributes

support/pal/pal_async/src/windows/iocp.rs, support/pal/pal_async/src/windows/local.rs, support/pal/pal_async/src/windows/overlapped.rs, support/pal/pal_async/src/windows/tp.rs
The `pal_async` crate's handling of overlapped IO on Windows would always use the `NTSTATUS` value stored in the `OVERLAPPED` structure to see if the operation completed (the value is not `STATUS_PENDING`). However, if an IO function completes synchronously, and returned an error, the value in the `OVERLAPPED` structure does not actually get updated by the kernel.
When doing some testing using `--kernel-vmnic`, in some cases the value stored in the `OVERLAPPED` structure would be `STATUS_PENDING` even though the IO had completed with an error (so the state is `IoState::None`), leading to a panic on `self.try_complete().unwrap()`.
This change modifies the `pal_async` crate to store the returned error in case of a synchronous error return, and use that in `try_complete` instead of checking …
=> pal_async: fix handling of synchronous errors on Windows.

openhcl/underhill_core/src/dispatch/mod.rs, openvmm/openvmm_entry/src/ttrpc/mod.rs, support/mesh/mesh_channel/src/bidir.rs, support/mesh/mesh_channel/src/cell.rs, support/mesh/mesh_channel/src/lazy.rs, support/mesh/mesh_channel/src/lib.rs, support/mesh/mesh_channel/src/rpc.rs, support/mesh/mesh_node/src/local_node.rs, support/mesh/mesh_node/src/message.rs, support/mesh/mesh_process/src/lib.rs, support/mesh/mesh_rpc/src/client.rs, support/mesh/mesh_worker/src/worker.rs, support/mesh_tracing/src/bounded.rs, vm/devices/input_core/src/mesh_input.rs, vm/vmcore/vm_resource/src/lib.rs, workers/vnc_worker/src/lib.rs
Mesh values need to be `'static` and `Send` because of implementation details in the current channel and `LocalNode` implementations. This is conceptually unnecessary since if we are dealing with a message at the "mesh" level, we are going to serialize it to protobuf. So, we should not have to constrain the lifetime or cross-thread safety requirements of such a value.
Upcoming improvements will make these bounds unnecessary. Remove them from the `MeshField` and `MeshPayload` traits now in anticipation of these changes.  Update existing code to make these bounds explicit where required; most are harmless, others some can be removed later as necessary.
=> mesh_node: remove 'static+Send bounds from MeshField and MeshPayload

Cargo.lock, Cargo.toml, support/mesh/mesh_channel/Cargo.toml, support/mesh/mesh_channel/src/lib.rs, support/mesh/mesh_channel/src/rpc.rs, support/mesh/mesh_channel_core/Cargo.toml, support/mesh/mesh_channel_core/src/deque.rs, support/mesh/mesh_channel_core/src/error.rs, support/mesh/mesh_channel_core/src/lib.rs, support/mesh/mesh_channel_core/src/mpsc.rs, support/mesh/mesh_node/src/local_node.rs
This change adds a new crate, `mesh_channel_core`, with a new MPSC (multi-producer, single-consumer) channel implementation. It replaces the existing SPSC and MPSC channels in `mesh_channel` with this single implementation. This has several advantages:
* The new channel supports MPSC semantics without any downsides, so we can offer just a single (non-oneshot) channel type instead of requiring users to choose between SPSC and MPSC.
* The generated code size is slightly smaller than the old SPSC channel.
* The new channel is much more efficient for in-process use, since the messages no longer have to flow through the `mesh_node` machinery.
* The new channel is more efficient and has better fairness for multi-process MPSC use, since there is a single queue on the receiver side instead of a …
=> mesh_channel: new channel implementation

support/mesh/mesh_channel/Cargo.toml, support/mesh/mesh_channel/src/lib.rs, support/mesh/mesh_channel_core/src/lib.rs, support/mesh/mesh_channel_core/src/mpsc.rs, support/mesh/mesh_channel_core/src/oneshot.rs, support/mesh/mesh_node/src/local_node.rs
Take a similar approach to #594 but for oneshot channels.
This reduces openvmm_hcl binary size by a few hundred KB, and it improves oneshot channel overhead by an unmeasured amount.
=> mesh_channel: new oneshot channel implementation

openhcl/underhill_core/src/get_tracing.rs, openvmm/openvmm_entry/src/tracing_init.rs, petri/pipette/src/trace.rs, petri/src/tracing.rs, petri/src/vm/construct.rs, support/test_with_tracing/src/lib.rs, xtask/xtask_fuzz/src/lib.rs
Feels like kind of a footgun that tracing has these completely disabled by default. I went through everywhere we're creating a tracing_subscriber::fmt::layer and enabled them where I thought it made sense. Along with some small cleanups.
=> Enable the output of tracing span events across the codebase

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/protocol.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vmm_core/virt_support_apic/src/lib.rs
The user<-> kernel transitions during IPI handling incur a significant amount of overhead on both the send and receive sides. These changes support handling IPIs entirely in-kernel, eliminating these transitions.
=> TDX: Add support for kernel interrupt offloading

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_hvlite/src/download_openhcl_kernel_package.rs
Remove the kernel version from the step name, so kernel updates no longer require YAML regeneration.
=> flowey: Remove kernel version from step name

Cargo.lock, openvmm/hvlite_core/src/worker/dispatch.rs, support/pal/pal_async/src/windows/overlapped.rs, vm/devices/vmbus/vmbus_proxy/Cargo.toml, vm/devices/vmbus/vmbus_proxy/src/lib.rs, vm/devices/vmbus/vmbus_server/Cargo.toml, vm/devices/vmbus/vmbus_server/src/lib.rs, vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
When the vmbusproxy driver is being used (e.g. using the `--kernel-vmnic` parameter, only available on Windows), OpenVMM would either panic or hang during exit, because the thread that issues ioctls to the proxy driver is never terminated.
This change adds a `CancelContext` to the `proxyintegration` module so that any outstanding IO can be cancelled, and the thread can exit cleanly when OpenVMM is terminated.
=> VmBus: cleanly exit when vmbusproxy is in use.

support/mesh/mesh_rpc/src/client.rs, support/mesh/mesh_rpc/src/server.rs, support/mesh/mesh_rpc/src/service.rs
Fix the mesh message format for client-initiated failure paths, and fix the timeout deadline check. Use a helper function everywhere to construct `Status` values. Add some basic test coverage of the client failure paths.
This fixes the client code handling of deadlines and connection failures.
=> mesh_rpc: fix client failure paths

.config/nextest.toml, petri/src/vm/start.rs
The ubuntu + tpm test is bumping right up against our timeouts. Increase them. If we can bring the test time back down we may revert this in the future.
=> Increase the vmm test timeouts

.config/nextest.toml, petri/src/vm/start.rs
The ubuntu + tpm test is bumping right up against our timeouts. Increase them. If we can bring the test time back down we may revert this in the future.
=> Increase the vmm test timeouts (#623)

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs, flowey/flowey_lib_hvlite/src/download_openhcl_kernel_package.rs, openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/protocol.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vmm_core/virt_support_apic/src/lib.rs
flowey: Remove kernel version from step name
CP from (#617)
No changes.
Update OHCL kernel to 6.6.63.1
CP from (#568)
YAML change in original commit ignored. No other changes.
TDX: Add support for kernel interrupt offloading
CP from (#124)
Changed to use `LapicState`'s `halted`, `idle`, `startup_suspend` fields instead of the `MpState` enum, as (#470) is not present in this branch.
=> Update OHCL kernel to 6.6.63.1 & TDX: Add support for kernel interrupt offloading

vm/vmcore/vm_topology/src/processor/x86.rs
Implements issue: [TDX VMs with hyperthreading getting incorrect thread count #481](https://github.com/microsoft/openvmm/issues/481)
=> Updated topology builder with correct vps_per_socket calculation

support/mesh/mesh_channel/src/lib.rs, support/mesh/mesh_channel_core/src/mpsc.rs, support/mesh/mesh_remote/src/unix_node.rs
Make the future returned by `recv` `!Unpin` and fix the one place in the codebase that cares.
This gives us flexibility to optimize the implementation in the future.
=> mesh_channel: remove `Unpin` from `Receiver::recv`

vm/vmcore/vm_topology/src/processor/x86.rs
Implements issue: [TDX VMs with hyperthreading getting incorrect thread count #481](https://github.com/microsoft/openvmm/issues/481)
=> cherry-pick: Updated topology builder with correct vps_per_socket calculation (#532)

openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs, vm/hv1/vtl_array/src/lib.rs
This is just most of the inner wiring, replacing hardcoded VTLs with the actual ones. Should introduce no functional changes just yet.
=> Add much of the basic wiring for TDX Guest VSM support.

support/mesh/mesh_channel_core/src/mpsc.rs
Improve the mesh encoding of channel messages with `#[mesh(transparent)]`. This improves perf for in-proc encoded send/recv by about 15%.
=> mesh_channel_core: use transparent enum variant encodings

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_cli/src/pipeline_resolver/ado_yaml.rs, flowey/flowey_cli/src/pipeline_resolver/direct_run.rs, flowey/flowey_cli/src/pipeline_resolver/generic.rs, flowey/flowey_cli/src/pipeline_resolver/github_yaml/mod.rs, flowey/flowey_core/src/pipeline.rs, flowey/flowey_hvlite/src/pipelines_shared/cfg_common_params.rs
This change moves from auto-generated parameter names to requiring the caller to specify a variable name. This makes for easier to read generated pipeline files and allows for better behavior if another pipeline wants to use queue-time variables to control pipeline behavior.
=> Flowey: Use explicit parameter names instead of auto generated.

Cargo.lock, vm/devices/vmbus/vmbus_client/src/hvsock.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_relay/Cargo.toml, vm/devices/vmbus/vmbus_relay/src/lib.rs, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
Track hvsock connect requests inside `vmbus_client` so that we can return the response (either an offer or a failure message) to the specific user that made the hvsock request. This is necessary to support multiple concurrent users of vmbus_client.
Also, separate connection-related APIs into `VmbusClientAccess`, leaving state machine (start/stop/save/restore) in `VmbusClient`. Ultimately, users of the vmbus client driver will just get `VmbusClientAccess` (plus `OfferInfo`(s) for the channels they are using).
=> vmbus_client: track hvsock requests and simplify RPC contract

vm/devices/net/netvsp/src/lib.rs, vm/devices/net/netvsp/src/test.rs, vm/devices/storage/storvsp/src/lib.rs, vm/devices/vmbus/vmbus_async/src/queue.rs
Don't `panic` when a GpaDirect packet contains a pointer to empty GPA ranges. This data is guest controlled and not a programmer error, so `panic` is not correct. Consumers of `read_external_ranges` already handle errors gracefully, so this is not a significant change for them.
As a drive-by code improvement, also change some cases of `#[from]` to `#[source]` in error definitions, and add the requisite `.map_err` changes.
=> vmbus_async: don't panic on empty external data

vm/devices/vmbus/vmbus_client/src/hvsock.rs, vm/devices/vmbus/vmbus_client/src/lib.rs
https://github.com/microsoft/openvmm/pull/440 broke main. This PR fixes up vmbus_client to take those changes.
=> vmbus_client: Fix bad merge and unbreak main

Cargo.lock, openhcl/underhill_attestation/Cargo.toml, openhcl/underhill_attestation/src/vmgs.rs
This PR:
* Adds unit tests to the `underhill_attestation` crate's `vmgs` module
* Covers all functions in the `vmgs` module
=> Increase `underhill_attestation` `vmgs` unit test coverage

openhcl/underhill_core/src/loader/mod.rs, support/serde_helpers/src/lib.rs, vm/devices/get/get_protocol/src/dps_json.rs, vm/devices/get/guest_emulation_transport/src/api.rs, vm/devices/get/guest_emulation_transport/src/client.rs, vm/loader/src/uefi/config.rs
Backport for 2411. 
Add generic ACPI tables from DevicePlatformSettings to the UEFI config
blob. UEFI currently only supports specific tables, so this is limited
to HMAT, IORT, MCFG, and SSDT for now.
=> [2411] Add generic ACPI tables from DPS to UEFI config

Cargo.lock, Cargo.toml, vm/devices/storage/scsi_defs/Cargo.toml, vm/devices/storage/scsi_defs/src/lib.rs, vm/devices/storage/scsi_defs/src/srb.rs, vm/devices/storage/storvsp/Cargo.toml, vm/devices/storage/storvsp/fuzz/Cargo.toml, vm/devices/storage/storvsp/fuzz/fuzz_storvsp.rs, vm/devices/storage/storvsp/src/ioperf.rs, vm/devices/storage/storvsp/src/lib.rs, vm/devices/storage/storvsp/src/protocol.rs, vm/devices/storage/storvsp/src/test_helpers.rs, vm/devices/storage/storvsp_resources/Cargo.toml, vm/devices/storage/storvsp_resources/src/lib.rs
First commit of a storvsp fuzzer. This begs, borrows, and steals from other test code to get something that compiles and runs.
Coverage shows that the fuzzer (at this point) does hit much of the core storvsp packet processing, _except_ for the IO path. That remains a work in progress.
=> RFC: storvsp: new fuzzer

openhcl/underhill_core/src/worker.rs
There are some hardware configurations on ARM64 that are not yet completely described in the MMIO map. Since ARM64 is not expected to do any x86-style legacy device detection probes, pass all MMIO accesses through to the host. If the host does not recognize the address, it will handle the bad access.
=> [ARM64] Pass through all unknown MMIO to the host.

vm/devices/net/netvsp/src/test.rs, vm/devices/vmbus/vmbus_channel/src/bus.rs, vm/devices/vmbus/vmbus_channel/src/channel.rs, vm/devices/vmbus/vmbus_channel/src/offer.rs, vm/devices/vmbus/vmbus_relay/src/lib.rs, vm/devices/vmbus/vmbus_server/src/lib.rs, vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
Don't require the guest-to-host interrupt be provided at channel offer time. Wait until open time. This is more flexible, and in the future will allow us to remove some extra synchronziation in `vmbus_relay`.
=> vmbus: delay interrupt creation until open response

openhcl/underhill_core/src/loader/mod.rs
Prefer the MADT/SRAT tables offered by the host through DevicePlatformSettings over self-built tables, when the host is trusted.
This allows OpenHCL to support scenarios in which the VMM builds these tables in a device- or scenario-specific way.
=> Accept MADT and SRAT from the host via DevicePlatformSettings

openhcl/underhill_core/src/loader/mod.rs
Prefer the MADT/SRAT tables offered by the host through DevicePlatformSettings over self-built tables, when the host is trusted.
This allows OpenHCL to support scenarios in which the VMM builds these tables in a device- or scenario-specific way.
=> [2411] Accept MADT and SRAT from the host via DevicePlatformSettings (#656)

openhcl/underhill_attestation/src/igvm_attest/ak_cert.rs
This PR:
* Adds `size` and `expected size to `AkCertError::SizeTooSmall` to enrich the error message when failing to parse an AkCert response
* Replaces the `test_empty_response` test with `test_undersized_response`, where an empty response is tested as a special case of an undersized response
=> Include found and expected response size in `AkCertError::SizeTooSmall`

openhcl/minimal_rt/src/arch/aarch64/intrinsics.rs
This is needed for internal 1.84 compatibility.
=> minimal_rt: Add ARM64 stack guard intrinsics

.cargo/config.toml, flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_lib_hvlite/src/build_rustdoc.rs
This allows us to set arbitrary custom rustdocflags. Because the rustdoc job already depends on install_openvmm_rust_build_essential, which depends on init_openvmm_cargo_config_deny_warnings, no code changes are needed to enable this.
=> flowey: Remove rustdocflags override, set -Dwarnings in config.toml

openhcl/underhill_attestation/src/key_protector.rs
This PR reverts #279 (with proper fix on the expected key length) and enforces strict check against the DEK format. More specifically, the check expects the DEK to be 40-byte (AES-wrapped AES key) and errors out if there is non-zero bytes exceeding the expected length.
=> attestation: Enforce strict DEK format check for 3-blob VMGS

Cargo.toml, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/host_params/mod.rs, openhcl/openhcl_boot/src/main.rs, openvmm/openvmm_entry/src/ttrpc/mod.rs, support/fdt/src/parser.rs, support/mesh/mesh_protobuf/src/protobuf.rs, vm/devices/pci/pci_core/src/capabilities/msix.rs, vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client_hcl/src/lib.rs, vm/devices/vmbus/vmbus_server/src/hvsock.rs, vmm_core/state_unit/src/lib.rs, vmm_core/virt_whp/src/lib.rs, vmm_core/virt_whp/src/vtl2.rs
The Rust 2024 edition will be changing how `impl Trait` in return position functions. Namely it will be changing the rules from capturing no lifetimes, to capturing all lifetimes. The reasons for this are documented in [RFC 3498](https://github.com/rust-lang/rfcs/blob/master/text/3498-lifetime-capture-rules-2024.md) and [the migration guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/rpit-lifetime-capture.html). A new 'precise capturing' syntax has been added to allow cases that don't need everything captured to scope down what they take. This PR updates all such cases to use the new syntax.
Note that currently this new syntax requires all type parameters in scope to be listed. This currently results in overcapturing of type parameters. This will be relaxed in the future, …
=> Fixup return position impl trait overcapturing for the 2024 edition

flowey/flowey_lib_common/src/download_azcopy.rs
Use the current target of https://aka.ms/downloadazcopy-v10-linux to fix up CI.
=> ci: workaround for azcopy path change

Cargo.toml, support/mesh/mesh_process/src/lib.rs
This will prevent any new uses of set/remove_env from coming into the codebase. This one case in mesh requires nontrivial work to remove. Tracked by #288.
=> Remove the global allow for deprecated_safe_2024, add an exclusion in mesh

Cargo.lock, vm/devices/storage/storvsp/fuzz/Cargo.toml, vm/devices/storage/storvsp/fuzz/fuzz_storvsp.rs, vm/devices/storage/storvsp/src/test_helpers.rs
Refactor the storvsp fuzzer to allow for forward progress: split the fuzzing loop into its own async function, and have the fuzz executor wait for either the fuzzing loop to run out of arbitrary data, or for the thread parsing storvsp packets (the test worker's task) to finish.
This is necessary because storvsp stops packet processing if the guest sends storvsp a corrupted or invalid packet. This is correct behavior, and the fuzzer must accommodate.
Tested by running running the fuzzer for some time and inspecting code coverage. There is a noticeable increase in code coverage on the paths that process IOs (where these were previously not hit). Also ran `cargo xtask fuzz run fuzz_storvsp -- -- -timeout=1` to catch when this likely hangs, with no hangs seen.
=> fuzz_storvsp: forward progress with invalid packets

openhcl/host_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/host_params/mod.rs, openhcl/openhcl_boot/src/main.rs, openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/worker.rs, vm/devices/get/get_protocol/src/lib.rs
Inform OpenHCL that Host is compatible with NVMe keep-alive feature by adding a new device tree entry
`/openhcl/vf-keepalive=nvme`
where vf-keepalive is a list of strings which may be expanded in future to include other device types such as `vf-keepalive=nvme,mana`
During servicing operation the host must now explicitly indicate that NVMe data should be saved (if VM supports it), this change flips the definition of keepalive bit in capabilities_flags bitmask (it used to be an emergency shut-off, not it is an "allow" indication). This flipping resolves compatibility issues with older host OSes after Live Migration.
=> Configure NVMe keep-alive ability from host

flowey/flowey_lib_common/src/download_azcopy.rs, flowey/flowey_lib_hvlite/src/_jobs/cfg_versions.rs
Bring release/2411 to the latest azcopy version. Cherry picked from #663 and #667
=> ci: update azcopy target and version

vm/devices/net/mana_driver/src/gdma_driver.rs, vm/devices/net/mana_driver/src/mana.rs, vm/devices/net/mana_driver/src/queues.rs, vm/devices/user_driver/src/emulated.rs, vm/devices/user_driver/src/lib.rs, vm/devices/user_driver/src/vfio.rs
Make it easier to diagnose missized device BARs by validating the size and returning an error, rather than waiting for a BAR access method to panic.
=> mana_driver: verify BAR0 size during startup

Cargo.lock, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_relay/src/lib.rs, vm/devices/vmbus/vmbus_relay_intercept_device/Cargo.toml, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
In the vmbus client, instead of sending a revoke over the general notify channel (which is hard to multiplex between multiple users of the vmbus client), notify a user of a revoke by closing the per-channel notification channel.
This is the last non-offer use of the notify channel. Change the notify channel to just an offer channel.
=> vmbus_client: use existing mesh channels to send revoke

vm/devices/get/guest_emulation_transport/src/process_loop.rs
During servicing, the host does not send a response for failure
notifications sent by OpenHCL. However, OpenHCL
waits indefinitely for a host response, causing an infinite wait loop.
Updated the error handling path to avoid expecting and waiting for a
host response.
Cherry pick from #677
=> Fix infinite wait loop in OpenHCL error handling path

Cargo.lock, openhcl/underhill_attestation/Cargo.toml, openhcl/underhill_attestation/src/lib.rs, vm/vmgs/vmgs/src/vmgs_impl.rs
This PR:
* Adds unit tests to the `underhill_attestation` crate's `lib`
* Covers all functions in `lib` that don't expect a `GuestEmulationTransportClient` parameter (any guidance on how to construct this in a test would be appreciated)
=> Increase `underhill_attestation` `lib` unit test coverage

vm/loader/igvmfilegen/src/file_loader.rs
In 2411 branch, disable host debugging independent of enable_debug to enable PMK release for public preview.
=> Disable hardware debug for TDX VMs in 2411

openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/underhill_core/src/worker.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs, vm/hv1/hv1_emulator/src/cpuid.rs
Now that we have the private pool we can finally fully wire this up.
This will not be backported, both because it's only needed for TDX Guest VSM support, and to give us enough time to assess the performance impact.
=> TDX: Enable TLB flush hypercall support

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Registering the intercept handler with OHCL instead of allowing the hypervisor to register the handler for the guest. Addresses issue #558.
=> virt_mshv_vtl: Added debug exception intercept handler for TDX.

openhcl/hcl/src/ioctl.rs, openhcl/underhill_core/src/worker.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/mshv/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
Instead of panicking when failing to get a register, propagate the failure up the stack.
This fixes OpenHCL running on older hypervisors, which do not support VTL2 accessing the `InternalActivityState` register. It also improves diagnosability when there are unexpected failures.
=> hcl: propagate failure to get a register

Cargo.lock, openvmm/openvmm_entry/src/cli_args.rs, openvmm/openvmm_entry/src/lib.rs, vm/devices/storage/disk_backend_resources/src/layer.rs, vm/devices/storage/disk_layered/src/lib.rs, vm/devices/storage/disk_layered/src/resolver.rs, vm/devices/storage/disklayer_ram/src/lib.rs, vm/devices/storage/disklayer_sqlite/Cargo.toml, vm/devices/storage/disklayer_sqlite/src/auto_cache.rs, vm/devices/storage/disklayer_sqlite/src/lib.rs, vm/devices/storage/disklayer_sqlite/src/resolver.rs
Add a new sqlite disk type that chooses a cache dbhd file based on the next layer's disk ID (or an optional key). This makes it easy to use a dbhd file as a cache over an HTTP-backed blob.
Also fix a few related issues with `LayeredDisk`, and make `openvmm_entry` better at constructing layered disks.
Note that `LayeredDisk` doesn't actually populate the read cache yet. That will be a separate change.
Example usage:
```bash
export OPENVMM_AUTO_CACHE_PATH=$HOME/.cache/openvmm/dbhd
openvmm --disk memdiff:autocache::blob:vhd1:https://url/to/my/vhd
```
=> disklayer_sqlite: add auto-cache resource

hyperv/tools/hypestv/src/windows/vm.rs
For kmsg, reconnect after a failure, and silently ignore connection reset.
For both serial and kmsg, respawn the underlying task during a configuration change if the task has failed.
This fixes some issues where serial/kmsg connections get into bad states across VM restarts.
=> hypestv: fix kmsg and serial failure paths

support/pal/pal_async/src/windows/pipe.rs
In Windows `PolledPipe`, treat `ERROR_PIPE_NOT_CONNECTED` the same as `ERROR_BROKEN_PIPE` on reads, and return EOF. This error code is returned if the server forces the pipe closed via `DisconnectedNamedPipe`, without closing its handle. Hyper-V does this for serial port pipes.
This fixes `hypestv`'s serial handling across VM reboots.
=> pal_async: handle ERROR_PIPE_NOT_CONNECTED as EOF

vm/loader/manifests/openhcl-x64-cvm-release.json
Shrink the minimum memory required to 64 MB, which matches non-confidential builds. 
Leave VBS and SNP alone for now.
=> openhcl/tdx: shrink minimum release memory size to 64 MB

vm/loader/manifests/openhcl-x64-cvm-release.json
Shrink the minimum memory required to 64 MB, which matches non-confidential builds.
Leave VBS and SNP alone for now.
Cherry pick of #711
=> openhcl/tdx: shrink minimum release memory size to 64 MB (#711)

vm/devices/vmbus/vmbus_server/src/lib.rs
#662 moved the creation of the guest event port (or rather, enabling it by setting its parameters) to the `complete_open` method, to simplify error handling. This caused some issues with the IC channels for some guests, as those devices can trigger an interrupt during open which is now lost.
This change moves the creation of the guest event port back to the `open_channel` method, and makes the necessary changes to deal with `open_channel` now being able to fail as well.
Fixes #715.
=> VmBus: move guest event port creation back to open_channel.

openhcl/underhill_core/src/loader/mod.rs, openhcl/underhill_core/src/worker.rs, vm/devices/get/get_protocol/src/dps_json.rs, vm/devices/get/guest_emulation_device/src/lib.rs, vm/devices/get/guest_emulation_transport/src/api.rs, vm/devices/get/guest_emulation_transport/src/client.rs
Adds a new boolean cxl_memory_enabled that gets passed to mu_msvm via config flags and indicates that the CXL root device ACPI0017 should be exposed in the DSDT ACPI table.
=> Add a new boolean cxl_memory_enabled to the platform config json.

vm/hv1/hv1_emulator/src/cpuid.rs
Our implementation of the hypercall supports it, so just leave it on.
=> Always support extended ranges for TLB flushing

.github/scripts/refresh_mirror/refresh-mirror.py
This change updates the script that invokes the mirror refresh pipeline to use the new staging branch for the upcoming 2411 OpenHCL release. This branch will be used to validate 2411 payload before being pulled into the release branch.
=> CI: Update mirror refresh script to update submodule in new staging branch

xtask/src/tasks/fuzz/cargo_fuzz.rs, xtask/src/tasks/fuzz/mod.rs
The nested cargo invocation limitation is unfortunate, but unavoidable according to Wesley. At least we can tell people about it.
Also refactor all the argument handling here to be more robust.
=> xtask: Add support for running fuzzers on a stable toolchain

openhcl/diag_client/src/lib.rs, petri/src/vm/hyperv/powershell.rs
For our use of PowerShell, we should not need user profile customizations (which are sometimes quite expensive and/or chatty). Pass `-NoProfile` to disable loading of the user profile.
=> petri, diag_client: pass -NoProfile to powershell invocations

openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
This fixes vmbus relaying with SNP.
=> virt_mshv_vtl/snp: fix untrusted sint readiness

vm/loader/manifests/openhcl-aarch64-dev.json, vm/loader/manifests/openhcl-aarch64-release.json
Revert "Use the Shared Visibilty pool on aarch64. For reasons that we do not yet"
This reverts commit a7c59b759e65aeac94f87dec8edc47a756400141.
=> openhcl: revert #539 (use shared visibility pool for aarch64 dma)

vm/loader/manifests/openhcl-aarch64-dev.json, vm/loader/manifests/openhcl-aarch64-release.json
Revert "Use the Shared Visibilty pool on aarch64. For reasons that we do not yet"
This reverts commit 94e1d09516ebbe1073b0413a2d1a54cef3f7a91c.
=> openhcl: revert #540 (use shared visibility pool for aarch64 dma)

openhcl/page_pool_alloc/Cargo.toml, openhcl/page_pool_alloc/src/lib.rs, openhcl/virt_mshv_vtl/Cargo.toml
Add a new feature that correctly gates `alloc_with_mapping` so `cargo check` with no features on linux works correctly again.
=> page_pool_alloc: fix features so cargo check works correctly

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/apic.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This PR pulls out the common ordering and processing needed for poll_apic across TDX and SNP. While there are similarities between this code and the poll_apic implementation in mshv, this PR does not change anything in mshv, as the lapic emulation code there is going to be deleted soon. This also allows this code to live off of HardwareIsolatedBacking, making it much cleaner than the first iteration.
Also cleanup SNP's weird register conversions.
=> virt_mshv_vtl: Share common processing between poll_apic implementations

openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/options.rs, openhcl/underhill_core/src/worker.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openvmm/hvlite_core/src/worker/dispatch.rs, openvmm/hvlite_defs/src/config.rs, openvmm/openvmm_entry/src/cli_args.rs, openvmm/openvmm_entry/src/lib.rs, petri/src/vm/openvmm/construct.rs, vm/hv1/hv1_emulator/src/cpuid.rs, vmm_core/virt/src/generic.rs, vmm_core/virt_whp/src/apic.rs, vmm_core/virt_whp/src/hypercalls.rs, vmm_core/virt_whp/src/lib.rs
This operating mode was originally added so that we could get automated CI test coverage of our APIC emulation without needing to run a full CVM. However, CVM CI tests are now just around the corner. And, as it turns out, we accidentally weren't using this in our current tests at all, and it's now broken. Seeing as we haven't been hit with any APIC bugs in a very long time, and that proper coverage will be coming soon, just remove it.
More cleanup is definitely possible here, such as removing support for certain hypercalls that are no longer needed, or moving trait functions off of Backing and onto HardwareIsolatedBacking. That can all come as follow ups.
=> virt_mshv_vtl/mshv_x64: Remove support for emulating APIC

Cargo.lock, Cargo.toml, openhcl/underhill_core/src/vp.rs, openhcl/underhill_mem/src/init.rs, openhcl/underhill_threadpool/Cargo.toml, openhcl/underhill_threadpool/src/lib.rs, support/loan_cell/Cargo.toml, support/loan_cell/src/lib.rs, support/pal/pal_async/Cargo.toml, support/pal/pal_async/src/executor_tests.rs, support/pal/pal_async/src/task.rs, support/pal/pal_async/src/windows/tp.rs, support/pal/pal_uring/Cargo.toml, support/pal/pal_uring/src/threadpool.rs
Add a safe abstraction for temporarily lending on-stack data into thread local storage. Use it in various places across the stack.
This fixes a use-after-free in `pal_async`, and it reduces the overhead of TLS in `pal_async` and `underhill_threadpool`.
=> loan_cell: add primitive for lending thread-local data

petri/src/vm/hyperv/hvc.rs, petri/src/vm/hyperv/mod.rs, petri/src/vm/hyperv/vm.rs
Attempts to mitigate an issue where on non-ephemeral ARM test runners, if the previous job orphaned a running VM, all subsequent jobs would fail. This is accomplished by stopping and then removing the VM both in the destructor and before creation (if one exists).
=> Petri: Stop and remove Hyper-V VMs on failure and before creation

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/deferred.rs
Don't remove the deferred action list from TLS until the `ProcessorRunner` is actually dropped.
This fixes crashes after a failed servicing operation.
=> hcl: fix multiple calls to `flush_deferred_actions`

openhcl/hcl/src/ioctl.rs, openhcl/openhcl_boot/src/hypercall.rs, openhcl/sidecar/src/arch/x86_64/mod.rs, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/hv1/hv1_hypercall/src/imp.rs, vm/hv1/hv1_hypercall/src/lib.rs, vm/hv1/hv1_hypercall/src/support.rs, vm/hv1/hv1_hypercall/src/tests.rs, vm/hv1/hvdef/src/lib.rs, vmm_core/virt_hvf/src/hypercall.rs, vmm_core/virt_whp/src/hypercalls.rs
Get rid of the weird sidecar `elements_processed` field and have the hypercall infra code construct the hypercall output directly.
=> hv1_hypercall: simplify hypercall output handling

openhcl/underhill_core/src/dispatch/mod.rs, openhcl/underhill_core/src/lib.rs, openhcl/underhill_core/src/options.rs, openhcl/underhill_core/src/worker.rs, vm/devices/get/guest_emulation_transport/src/process_loop.rs
Add infrastructure to simulate OpenHCL test failures
- Introduced a OpenHCL command-line argument to define test scenarios.
- Implemented custom actions based on the specified test scenario string.
This enables better debugging and validation of OpenHCL failure scenarios.
CP: https://github.com/microsoft/openvmm/pull/742
=> Add infrastructure to simulate the OpenHCL test failures

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/hv1/hv1_emulator/src/cpuid.rs
Refactoring work so that the startvp hypercall is not handled by OpenHCL for non-CVMs. Will help to keep future CVM-only work isolated to the CVM backings.
Tested:
- SNP VMs boot
- x86 and aarch64 TVMs boot
- TDX VMs boot
=> virt_mshv_vtl: Scope startvp handling to CVMs

openhcl/hcl/src/ioctl.rs, openhcl/sidecar/src/arch/x86_64/vp.rs, openhcl/sidecar_client/src/lib.rs, openhcl/sidecar_defs/src/lib.rs, vm/hv1/hv1_hypercall/src/support.rs, vm/hv1/hv1_hypercall/src/tests.rs, vm/hv1/hvdef/src/lib.rs, vm/whp/src/lib.rs, vmm_core/virt_whp/src/hypercalls.rs, vmm_core/virt_whp/src/synic.rs, vmm_core/virt_whp/src/vp.rs
`HvError` is supposed to represent a non-success status code, but it's also used for a possibly-successful status code in some places. Fix this by adding a new `HvStatus` type and making `HvError` a wrapper around `NonZeroU16`.
This also gives us a nice niche optimization, so that `HvResult<(), HvError>` is equivalent to `HvStatus`.
=> hvdef: make `HvStatus` type distinct from `HvError`

.github/workflows/openvmm-ci.yaml, .github/workflows/openvmm-pr.yaml, flowey/flowey_lib_hvlite/src/_jobs/cfg_hvlite_reposource.rs, flowey/flowey_lib_hvlite/src/build_guide.rs, openvmm/hvlite_core/src/worker/dispatch.rs, openvmm/hvlite_core/src/worker/vm_loaders/linux.rs, openvmm/openvmm_entry/src/meshworker.rs, openvmm/openvmm_entry/src/storage_builder.rs, petri/src/vm/openvmm/construct.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
I noticed "hvlite" was in a few user-facing strings where we it should not be. Fix the places where this is not a breaking change: in openvmm, flowey, and petri.
=> Rename hvlite to openvmm in more user-facing strings

openhcl/host_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/main.rs, openvmm/hvlite_core/src/worker/vm_loaders/igvm.rs
Get the physical address width via device tree to determine the alias map on systems that don't reliably report the physical address width architecturally (ARM).
=> openhcl_boot: Get alias map from device tree

openhcl/gen_init_ramfs.py
When `create_cpio_from_config` was updated to accept a list, the command line usage didn't get updated. I've had a chance to notice that as I use the this in other repo's.
Update the type annotations and fix the command line usage.
=> openhcl: Fix the direct invocation of `gen_init_ramfs`

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This feels like a potentially premature perf optimization, but it does match the code in the HCL. That being said, neither us nor the HCL have actually run TDX with VTL 1 since the hypervisor isn't ready for it yet, so who knows. Part of #699.
=> TDX: Check active VTL before waking for TLB lock flushing

openhcl/Set-OpenHCL-HyperV-VM.ps1, openhcl/gen_init_ramfs.py, openhcl/perftoolsfs.config, openhcl/rootfs.config, openhcl/update-rootfs.py
The tooling didn't flag these files for missing these lines, fixing manually this time.
=> openhcl: Add the license and copyright notes to few files

openhcl/host_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/openhcl_boot/src/main.rs
Get the alias map via device tree since some ARM systems don't reliably report the physical address width architecturally.
Cherry pick from #733
=> [2411] openhcl_boot: Get alias map from device tree

vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
Continuing adding NVMe keepalive and private pool testing. The new one adds necessary config to fully test the feature, even NVMe queue memory is preserved after servicing.
=> More NVMe keepalive VMM test coverage

Cargo.lock
This change updates the openssl and openssl-sys crates to the latest available verisons.
Resolves https://github.com/microsoft/openvmm/security/dependabot/2
=> Update openssl create to latest version (0.10.70)

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
TDX supports flushing ranges with the full size of `count` that our HvGvaSimpleRange supports. It does not support flushing large page ranges. These two cases are indistinguishable at flush time, as they have the same binary representation, but we can tell them apart when we add entries to the list, thanks to the flag parameter in the hypercall. 
The original HCL code this was based on was used in multiple locations and so needed to support storing large page ranges. We do not. Invert the check for them to make things simpler.
Note that this is the first time this code is meaningfully differing from the original HCL code.
=> TDX TLB: Don't add extended ranges to the list

openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This was the only hypercall left with these old duplicated handlers. The rest have meaningful architectural differences.
=> virt_mshv_vtl: Deduplicate RetargetDeviceInterrupt hypercall handlers

openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs, vm/hv1/hv1_emulator/src/cpuid.rs
Small miscellaneous drive-by cleanups noticed while doing other work. Just trying to make things easier to follow, and using zerocopy in one new spot that should've. Should introduce no functional changes.
=> Small cleanups to hv1 and tdx tlb flush code

vm/devices/net/gdma/src/hwc.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_linux_direct.rs
Currently, testing servicing with MANA results in the following error:
```
47.426762200s  WARN gdma::hwc:  req error msg_type=0x5 dev_id=GdmaDevId { ty: GDMA_DEVICE_MANA, instance: 1 } error=unsupported message type: GDMA_DEREGISTER_DEVICE
...
vtl0 start failed: guest reported VTL0 start error: failed to create mana device: failed to initialize mana device: establish failed: 1
```
This change handles the message and adds a test for servicing with basic validation.
=> mana: Handle deregister message in emulator

openhcl/hcl/src/ioctl/tdx.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/x86/x86defs/src/tdx.rs
Introduce a new TdxPrivateRegs struct that is stored per-vtl. This allows userspace operations to operate on arbitrary VTLs, despite the kernel only holding one set of registers. Copy these registers in and out of the shared kernel page on every entry and exit. Remove `pub` from accessors that directly touch private registers in the kernel and add new accessors that allow vtl-shared state to still be accessed.
Together with #775 fixes #746.
=> TDX: Copy vtl-private registers to/from userspace per-vtl

vmm_tests/vmm_test_macros/src/lib.rs
This functionality is currently only used in the closed-source tests.
=> vmm_test_macros: fix test with extra params

vm/hv1/hv1_hypercall/src/support.rs, vmm_core/virt_kvm/src/arch/x86_64/mod.rs
This stops them from appearing as suggestions in autocomplete on completely unrelated types.
=> hv1_hypercall: Remove blanket implementations of AsHandler

repo_support/relabel_backported.py
This relabels `backport_<release>` to `backported_<release>` if it finds a matching PR.
=> relabel_backported.py: add script to relabel PRs that were backported

openhcl/openhcl_boot/src/main.rs
Some time after originally capping the SWIOTLB at 1 MiB, the SWIOTLB was split into per-CPU areas. This increased the memory usage considerably. Clamp the number of areas at 1 to reduce the memory usage again. This impacts ARM64 and TDX. On a 64 VP ARM machine, this change saves ~22MiB. (Need to test TDX still)
=> Recap SWIOTLB to the minimum.

Cargo.lock, vm/whp/Cargo.toml, vm/whp/src/abi.rs, vm/whp/src/abi/x64.rs, vm/whp/src/lib.rs, vm/whp/src/partition_prop.rs
Fixes an issue in the WHP code that caused the WHV_ARM64_IC_PARAMETERS struct to get trampled on when using a release build. This was caused by the use of an unsafe block to return a reference to a struct that went out of scope. In debug builds, the compiler didn't reuse this memory right away, but in the release build it did. Now the original struct outlives the function that uses it.
=> whp: Refactor get/set property to improve safety and fix a UB

openhcl/underhill_mem/src/init.rs, openhcl/underhill_mem/src/lib.rs, openhcl/underhill_mem/src/mapping.rs
It didn't make sense to me have everything in the root of underhill_mem immediately be inside another module. Separate out what needs to be in the unsafe module, and what doesn't.
Only change beyond copying/pasting and fixing up paths is the new zero_range function, since the field it needs is private.
=> underhill_mem: Separate out modules

openhcl/lower_vtl_permissions_guard/Cargo.toml, openhcl/lower_vtl_permissions_guard/src/lib.rs, openhcl/underhill_core/Cargo.toml, openhcl/underhill_core/src/dma_manager.rs, openhcl/underhill_core/src/worker.rs, vm/devices/get/guest_emulation_transport/src/client.rs, vm/devices/get/guest_emulation_transport/src/process_loop.rs, vm/devices/storage/disk_nvme/nvme_driver/fuzz/fuzz_emulated_device.rs, vm/devices/storage/disk_nvme/nvme_driver/src/tests.rs, vm/devices/user_driver/src/emulated.rs, vm/devices/user_driver/src/lib.rs, vm/devices/user_driver/src/lockmem.rs, vm/devices/user_driver/src/vfio.rs, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs, vm/page_pool_alloc/Cargo.toml, vm/page_pool_alloc/src/lib.rs
Remove the vfio dma trait and replace all implementations with `DmaClient`. Cleanup an orphaned trait that did not get removed in a previous PR. 
There is still more cleanup to be done, namely it's not clear to me that `PagePool` should implement `DmaClient` and the logic of choosing which page pool for which device should be implemented as policy in `GlobalDmaManager`, but that change requires further thought. 
#786
=> user_driver: remove vfio dma trait

vm/whp/src/abi.rs, vmm_core/virt_whp/src/lib.rs
New builds of WHP on aarch64 require that the VMM configure the PMU interrupt ID. This PR configures it using the same value that Hyper-V uses. 
Backporting #356 to fix ARM OpenVMM tests.
=> Adding WHV_ARM64_IC_GIC_V3_PARAMETERS::GicPpiPerformanceMonitorsInterrupt to aarch64 unstable_whp (#356)

Cargo.lock, vm/whp/Cargo.toml, vm/whp/src/abi.rs, vm/whp/src/lib.rs, vm/whp/src/partition_prop.rs
Fixes an issue in the WHP code that caused the WHV_ARM64_IC_PARAMETERS struct to get trampled on when using a release build. This was caused by the use of an unsafe block to return a reference to a struct that went out of scope. In debug builds, the compiler didn't reuse this memory right away, but in the release build it did. Now the original struct outlives the function that uses it. Includes a refactoring of whp get/set property to improve type safety.
=> whp: Refactor get/set property to improve safety and fix a UB (#801)

flowey/flowey_hvlite/src/pipelines/checkin_gates.rs, flowey/flowey_lib_hvlite/src/build_openvmm.rs
Enables the ARM OpenHCL Hyper-V test now that we have a capable test runner. Builds OpenVMM with the unstable_whp feature for compatibility with the pre-release OS now installed on the runners so that they can support OpenHCL.
=> ci: enable arm openhcl test (#782)

vm/devices/storage/disk_nvme/nvme_driver/src/tests.rs
Reported-By: @mattkur
nvme driver unit tests were taking upwards of 2.5s to execute. Upon inspection we found that some of the tests were allocating 4GB (4 << 30) for payload memory. This much memory should not be required since the only use case for this memory is dma buffers used by the NvmeDriver.
After this change all tests should be running in < 0.1s
=> nvme_driver: tests: Reducing payload amount to 4MB instead of 4GB for the unit tests

Cargo.lock, support/guid/Cargo.toml, support/guid/src/lib.rs, support/pal/Cargo.toml, support/pal/src/windows.rs, vm/devices/net/vmswitch/src/kernel.rs, vm/devices/vmbus/vmbus_proxy/Cargo.toml, vm/devices/vmbus/vmbus_proxy/src/lib.rs, vm/devices/vmbus/vmbus_proxy/src/proxyioctl.rs, vm/devices/vmbus/vmbus_proxy/src/vmbusioctl.rs, vm/devices/vmbus/vmbus_server/Cargo.toml, vm/devices/vmbus/vmbus_server/src/lib.rs, vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This change modifies the `vmbus_proxy` crate to allow `VmbusProxy` to be created from an externally-provided handle, and to allow `ProxyIntegration` to be used without needing to provide a fully-mapped `GuestMemory`.
I also took the opportunity to move `vmbus_proxy` over to using `windows` instead of `winapi`.
=> vmbus_proxy: allow using an existing handle and make GuestMemory optional

Cargo.lock
This change updates the openssl and openssl-sys crates to the latest available verisons.
Resolves https://github.com/microsoft/openvmm/security/dependabot/2
=> Update openssl create to latest version (0.10.70) (#776)

openhcl/hcl/src/ioctl/tdx.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs
Part of cleaning up our kernel-shared state to be harder to use incorrectly for #746. Alternate take on #784.
Part of #699 too.
=> TDX: Move vp entry flags into private regs

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_core/src/protocol.rs, vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
In unit tests, `TargetInfo` can be unaligned, causing a panic when converting from `&[u8]` to `u64` by reference. Since `TargetInfo` contained `u8`s and a `u32`, the only guarantee was 4-byte alignment. `u64` requires 8 byte alignment.
Fix this by converting `TargetInfo` to a `bitfield`, since that is the semantic reason of this struct anyways (a bit-by-bit representation of 64-bit data type).
```
0x00005555556a213f in vmbus_core::protocol::TargetInfo::as_u64 (self=**0x7ffff768408c**) at vm/devices/vmbus/vmbus_core/src/protocol.rs:320
```
Reported-By: @tjones60
Fix Suggested-By: @jstarks
=> vmbus_core: fix TargetInfo alignment

Cargo.lock, openhcl/underhill_core/src/worker.rs, openvmm/hvlite_core/Cargo.toml, openvmm/hvlite_core/src/worker/dispatch.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
Enabling new VmBus feature flags can lead to issues when rolling back to an older version of OpenHCL. For this reason, this change disables the client ID feature flag until a better solution is available.
Isolated guests are excluded from this as they do not currently support servicing.
Cherry-picked from #428.
=> VmBus: disable client ID support in OpenHCL when not isolated (#428)

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_core/src/protocol.rs, vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
In unit tests, `TargetInfo` can be unaligned, causing a panic when converting from `&[u8]` to `u64` by reference. Since `TargetInfo` contained `u8`s and a `u32`, the only guarantee was 4-byte alignment. `u64` requires 8 byte alignment.
Fix this by converting `TargetInfo` to a `bitfield`, since that is the semantic reason of this struct anyways (a bit-by-bit representation of 64-bit data type).
```
0x00005555556a213f in vmbus_core::protocol::TargetInfo::as_u64 (self=**0x7ffff768408c**) at vm/devices/vmbus/vmbus_core/src/protocol.rs:320
```
Reported-By: @tjones60
Fix Suggested-By: @jstarks
=> vmbus_core: fix TargetInfo alignment (#807)

support/mesh/mesh_node/src/local_node.rs
When a node sends a port failure event, it runs out of space and panics.
This is bad. Fix the size calculation to avoid this. Add a test.
Backport-of: #603
=> mesh_node: fix size calculation for port failure events (#603)

Cargo.lock, Cargo.toml
This contains some important bug fixes, most notably
rust-lang/futures-rs#2884, which affects some of our tools.
Backport-of: #398
=> Update `futures` to 0.3.31 (#398)

vmm_core/virt_support_apic/src/lib.rs
When an interrupt is delivered locally (for self IPIs and timers), we
don't notify the partition to wake the processor, and so we never scan
IRR to find and deliver these interrupts.
Fix this.
Backport-of: #331
=> virt_support_apic: scan IRR for self IPIs and timers (#331)

openhcl/rootfs.config, openhcl/underhill_init/src/lib.rs, vmm_tests/vmm_tests/tests/tests/x86_64.rs
The underhill binary was renamed to openvmm_hcl, but its name was not
updated in the initrd. As a result, crash dumps reference
/bin/underhill, but the symbols are published as openvmm_hcl.dbg. This
makes it hard for the debugger to find the appropriate symbols.
Rename the binary within the initrd to be consistent.
Backport-of: #326
=> initrd: rename /bin/underhill to /bin/openvmm_hcl (#326)

openhcl/hcl/src/ioctl.rs, openhcl/underhill_core/src/worker.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/mshv/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs
Instead of panicking when failing to get a register, propagate the
failure up the stack.
This fixes OpenHCL running on older hypervisors, which do not support
VTL2 accessing the `InternalActivityState` register. It also improves
diagnosability when there are unexpected failures.
Backport-of: #707
=> hcl: propagate failure to get a register (#707)

openhcl/hcl/src/ioctl.rs, openhcl/hcl/src/ioctl/deferred.rs
Don't remove the deferred action list from TLS until the
`ProcessorRunner` is actually dropped.
This fixes crashes after a failed servicing operation.
Backport-of: #739
=> hcl: fix multiple calls to `flush_deferred_actions` (#739)

Guide/src/SUMMARY.md, Guide/src/dev_guide/contrib/release.md
Add documentation for a few things:
1. How we managed (and manage) code flow for the `release/2411` branch,
2. The general concept of releases and our release phases,
3. Guarantees that external parties can make based on the existence of those branches
=> guide: add release & code flow page

openhcl/openhcl_boot/src/main.rs
Some time after originally capping the SWIOTLB at 1 MiB, the SWIOTLB was split into per-CPU areas. This increased the memory usage considerably. Clamp the number of areas at 1 to reduce the memory usage again. This impacts ARM64 and TDX. On a 64 VP ARM machine, this change saves ~22MiB, ~18 MiB on TDX.
=> Recap SWIOTLB to the minimum. (#794)

Cargo.lock, Cargo.toml, support/pal/Cargo.toml, vm/devices/vmbus/vmbus_proxy/src/lib.rs
#774 and #799 used conflicting versions of the `windows` crate. This change upversions `windows` and fixes `vmbus_proxy` for this `windows` version.
=> Upversion windows crate to 0.59.0

xsync/xsync/src/tasks/cargo_toml.rs, xsync/xsync/src/tasks/mod.rs, xsync/xsync/src/tasks/rust_toolchain_toml.rs
This might break the mirror pipeline until the corresponding addition of these values is merged internally.
=> xsync: Add 'inherit' and 'channel_prefix' options to control toolchain syncing

vm/devices/net/mana_driver/src/gdma_driver.rs
- Use wait and poll cycles to allow HWC command to succeed when new EQE is found regardless of interrupt wait success.
- Detect missed interrupt condition and report in logging and in shmem command for soc logging.
=> mana: poll HWC EQE after interrupt wait

vm/devices/storage/disk_nvme/nvme_driver/src/driver.rs
Currently the IoQueueSavedState struct is only being used to save the state of the IoQueue struct. However, the same variable is named differently between the two structs (msix vs iv). Changing the variable name in the SavedState struct to match that of IoQueue. 
Note: this will not be changing the size of msix. I believe that might cause some breakage when saving the values.
=> nvme_driver: renamed the variable `msix` in IoQueueSavedState to `iv` to match the IoQueue

xsync/xsync/src/tasks/cargo_toml.rs, xsync/xsync/src/tasks/mod.rs, xsync/xsync/src/tasks/rust_toolchain_toml.rs
This might break the mirror pipeline until the corresponding addition of these values is merged internally.
=> xsync: Add 'inherit' and 'channel_prefix' options to control toolchain syncing (#837)

.clippy.toml
These are now the default (the "future version of rust" was a while ago) so we don't need to restate them.
=> clippy.toml: Remove outdated configs

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/apic.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Moves some CVM-specific state off of UhVpInner into a cvm-specific struct.
Tested by booting a non-isolated VM and an SNP VM.
=> cvm guest vsm: move vtl1_enabled from UhVpInner to a new UhCvmVpInner

Cargo.lock, openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/hv1/hv1_hypercall/Cargo.toml, vm/hv1/hv1_hypercall/src/imp.rs, vm/hv1/hv1_structs/src/lib.rs, vm/hv1/hv1_structs/src/proc_mask.rs, vmm_core/virt_whp/src/device.rs, vmm_core/virt_whp/src/hypercalls.rs
This allows us to avoid some heap allocations in the TLB flush hypercalls.
=> Implement lazy parsing of hypercall processor sets

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Not sure if any validation is needed on these values, but I couldn't find any being done in the HCL or in SNP.
Fixes #797, part of #547
=> TDX: Fill in get/set_tsc_aux and set_xss

xtask/src/tasks/fmt/house_rules/copyright.rs
Remove support for files ending in .config, which do not always use `#` comments (e.g., nuget config files).
Improve behavior around non-OSS checks and fixes.
=> xtask: fix copyright house rule

xsync/xsync/src/tasks/cargo_lock.rs
When using `cargo update` to update the generated `Cargo.lock` file, pass `--offline` to avoid connecting to crates.io. Since we pass `--workspace`, there should be no reason to fetch anything from the network in this step.
This saves several seconds when calling `cargo xtask fmt`.
=> xsync: speed up cargo-lock regen

petri/src/test.rs
Right now, a test result on failure (the panic text or the anyhow error) only gets written to stdout, not to the split text logs or to the JSON log. This makes it hard to diagnose test failures by just looking at the log files.
Trace the test result to the other logs, too. Also, add a file to make it easy to find the tests that passed and failed in the test result artifact directory tree without having to parse the junit XML (which is enormous).
=> petri: trace the test result

openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This creates a new trait, TlbFlushLockAccess, that is used to allow memory protections management code to access the VP's TLB flush and lock machinery. It then adds a new parameter of this type to certain methods on ProtectIsolatedMemory, and adds calls to it where appropriate.
This also adds a small hack to avoid an ongoing layering discussion. We're unsure of the right approach to fix it, but the rest of the code should be fine as-is.
Open question: Do we have the right calls everywhere needed? I tried to match up our code with the legacy HCL's, but our design and flow are very different, so I'm not 100% confident I got them all correct.
Part 1 of #849
=> underhill_mem: Wire up TLB access for flushing and locking

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
These were error but ratelimited, but downgrade them to warn. We still want to know if a guest does something strange, but it doesn't need to be error level. 
Closes #651
=> openhcl/tdx: downgrade unknown msr accesses to warn

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This TODO is not applicable, and was really only something noticed early in bringup.
=> openhcl/tdx: cleanup useless todo comment

xsync/xsync/src/main.rs, xsync/xsync/src/tasks/cargo_lock.rs
After improving xsync performance in #857, xsync's internal `cargo update` command now (silently) fails in CI, causing one of the overlay deps files to be computed incorrectly. This occurs because in CI, the registry index is not always populated at the point of xsync, and `cargo update` cannot download it due to the use of `--offline`.
To preserve most of the performance benefits while fixing the issue, try `cargo update --offline` first and, if that fails, try it again without `--offline`. Probably `cargo update --workspace` should be fixed to not touch the network unless needed.
Also, report the errors from these commands so that this will be caught next time. Like, come on.
=> xsync: fix cargo-lock regen

Cargo.lock, openhcl/hcl_mapper/Cargo.toml, openhcl/hcl_mapper/src/lib.rs, openhcl/underhill_core/src/worker.rs, openhcl/virt_mshv_vtl/Cargo.toml, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/tlb_flush.rs, vm/page_pool_alloc/Cargo.toml, vm/page_pool_alloc/src/device_dma.rs, vm/page_pool_alloc/src/lib.rs
Save a bunch of kernel memory and speed things up by creating one mapping per pool instead of one per allocation. Move knowledge about the pool's use out to the backing memory sources. Remove support for unmapped pools (no use case).
We could simplify things further by moving all the mapping code to the individual mappers, but this would complicate computing the mapping address for a given slot, so skip this for now.
=> page_pool_alloc: clean up mapping handling

support/guid/src/lib.rs
Now that all callers are using the macro, hide the method so that it is not accidentally called directly.
=> guid: rename `from_static_str` to hide it

xtask/src/tasks/fmt/house_rules/copyright.rs
The permissions are lost for the executable files otherwise.
=> xtask: Replicate file permissions when in the fixing mode

Cargo.toml, openhcl/hcl/src/ioctl/tdx.rs, openvmm/openvmm_entry/src/storage_builder.rs, vm/devices/user_driver/src/interrupt.rs, vm/vmcore/guestmem/src/lib.rs, vm/vmcore/src/vmtime.rs, vmm_core/state_unit/src/lib.rs, xtask/src/tasks/fmt/unused_deps.rs
Mostly cleaning up some more map_ors, but the one big change of note is temporarily allowing the clippy:precedence lint. Previously this lint only applied to arithmetic operations, however a change in 1.85 causes it to apply to bitwise operations as well. This is overly noisy, and unnecessary. And the clippy maintainers agree, as they've since split out this change into a separate lint, precedence_bits, that is allow-by-default. However that split will not be present until 1.86. See https://github.com/rust-lang/rust-clippy/pull/14115 for details on that.
=> Fix lints for Rust 1.85

Cargo.lock, vm/devices/vmbus/vmbus_client/Cargo.toml, vm/devices/vmbus/vmbus_client/src/lib.rs
Don't spawn extra threads, and don't use `std::thread::sleep`.
=> vmbus_client: clean up tests

vm/devices/net/mana_driver/src/gdma_driver.rs
- Use wait and poll cycles to allow HWC command to succeed when new EQE is found regardless of interrupt wait success.
- Detect missed interrupt condition and report in logging and in shmem command for soc logging.
- Always wait instead of polling first to increase chances of detecting missed interrupt condition.
- Vary wait from min 20 ms to max at 500 ms, increasing on each wait, so that non-fixed socmana with no interrupts for HWC works with negligible delay.
---------
Cherry pick of #814
=> mana: poll HWC EQE after interrupt wait (#814)

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
housekeeping PR: discussion is in #550, we are in agreement that CS should not be cached into the last exit
=> TDX: remove todo about caching CS into exit

Cargo.lock, openhcl/underhill_mem/Cargo.toml, openhcl/underhill_mem/src/lib.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs, vm/hv1/hv1_emulator/src/hv.rs, vmm_core/virt_whp/src/lib.rs, vmm_core/virt_whp/src/vp.rs
=> hv1_emulator: Support flushing the TLB when writing to the hypercall page MSR

vm/vmgs/vmgstool/src/main.rs
Improve the query-encryption subcommand to detect whether the Vmgs file is encrypted using GspKey or GspById
=> vmgstool: encryption scheme detection

petri/src/vm/openvmm/construct.rs, petri/src/vm/openvmm/mod.rs, petri/src/vm/openvmm/runtime.rs
Mistakenly removed this function that is used by internal tests. Brought it back in a way that doesn't require storing an extra copy of the path in the uhdiag handler.
=> petri: restore vtl2_vsock_path getter

Cargo.lock, vm/devices/vmbus/vmbus_server/Cargo.toml, vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs, vm/devices/vmbus/vmbus_server/src/lib.rs, vm/vmcore/src/synic.rs, vmm_core/src/synic.rs
This change adds a mechanism for the `GuestMessagePort` trait to apply backpressure when VmBus tries to send a message. If a message cannot be immediately sent, VmBus will queue it to retry later. While messages are pending, the server will not process incoming messages from the guest to limit the amount of resources used.
In order to support this properly for reserved channels, including across save/restore, how sending messages to closed reserved channels is handled is changed slightly. This means that the reserved channel's message port is now always destroyed and recreated (to send the closed response) when closing the channel. This way, the message port doesn't need to stay open if the message is not sent immediately, and doesn't need to be reconstructed on save/restore.
Because the …
=> vmbus_server: support backpressure for posting messages

Cargo.lock, petri/src/tracing.rs, petri/src/vm/hyperv/mod.rs, petri/src/vm/openvmm/construct.rs, petri/src/vm/openvmm/mod.rs, petri/src/vm/openvmm/runtime.rs, petri/src/vm/openvmm/start.rs, support/pal/pal_async/src/windows/pipe.rs, support/pal/src/windows/pipe.rs, vmm_tests/vmm_tests/Cargo.toml, vmm_tests/vmm_tests/tests/tests/ttrpc.rs
Consistently use `serial_log_task`, renamed to `log_stream`, to log line-based log output from other processes. The other adhoc implementations of this have various problems, mostly around error handling.
This fixes a bug where the ttrpc test writes 60K lines saying COM1 has been closed.
=> petri: use a single method to parse a stream of lines

Guide/src/dev_guide/getting_started/linux.md, Guide/src/dev_guide/getting_started/suggested_dev_env.md, build_support/setup_windows_cross.sh
Tweaks some language in the `setup_windows_cross.sh` script and the Guide, to clarify the pitfalls associated with cloning the repo on a Windows partition and then using it from WSL2, as well as offering a more specific suggestion on how to resolve the issue.
Also include a minor drive-by chance in `suggested_dev_env.md`, that's been bugging me for a while, ha
=> guide: clarify guidance and warnings related to cloning repo

flowey/flowey_lib_common/src/gh_workflow_id.rs
From [this run](https://github.com/microsoft/openvmm/actions/runs/13446070583/job/37571567182?pr=885), it looks like it's possible to get an empty string as the action id which isn't currently being checked for in the binary comparison. 
This change adds handling for an empty string by converting it into an error and continuing to traverse commits in that case. I've also added some logging for this case.
=> flowey: handle empty action id in binary comparison

vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs
The vmbus server only saved channel state when connected. Since reserved channels can be open even if the guest is not currently connected to host vmbus, this creates a small window where reserved channels can be lost.
This change separately saves reserved channels when the guest is disconnected. This is done only when disconnected; when connected, reserved channels are saved with the connected state as before, to maintain compatibility with the saved state of versions prior to this fix.
Fixes #882.
=> vmbus_server: save reserved channels when disconnected.

openhcl/openhcl_boot/src/main.rs
Few of the module parameters that were earlier supported in uio_hv_generic driver no longer exist in kernel. Remove the logic which adds these parameters in kernel cmdline from openvmm.
=> openhcl_boot: Remove few kernel parameters for uio_hv_generic

flowey/flowey_lib_hvlite/src/artifact_openhcl_igvm_from_recipe_extras.rs
Although this flowey task is not currently used, replace an incorrect filename with the correct one.
=> Fix symbols name for openvmm_hcl

openhcl/openhcl_boot/src/host_params/dt.rs, openhcl/underhill_mem/src/lib.rs, vm/x86/tdcall/src/lib.rs, vm/x86/x86defs/src/tdx.rs
Our mask was previously being constructed by just using the attributes. This allowed us to add permissions, but never remove them. Fix this by always setting the mask to have all true bits. Also fixup the debug assertions to only check the bits specified by the mask. Fixes #901 .
=> TDX: Properly handle memory protections

flowey/flowey_lib_hvlite/src/_jobs/check_openvmm_hcl_size.rs
As part of #475, I added a new baseline artifact for binary comparison but didn't use it yet as I wanted to wait for there to be builds to diff against but hadn't followed up yet. #895 renamed the binary in igvm-extras that we were using to diff and broke the comparison.
This change uses the baseline artifact for comparison and keeps the binary size artifacts limited in scope.
=> flowey: use baseline artifact instead of igvm-extras for binary comparison

openhcl/virt_mshv_vtl/src/processor/snp/mod.rs
Fixes a bug introduced by a refactor that causes a multi-vp SNP VM to get stuck when a kernel debugger is attached to the guest.
Tested:
SNP with kernel debugging boots
=> snp: reset nmi pending when nmi is delivered

openvmm/hvlite_core/src/worker/dispatch.rs, vm/devices/vmbus/vmbus_server/src/lib.rs, vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This change makes it possible for vmbusproxy to offer channels to VTL2. Previously, vmbusproxy ignored an offer's target VTL and would always offer to VTL0.
=> vmbus_server: support VTL2 channels for vmbusproxy.

Guide/src/dev_guide/getting_started/suggested_dev_env.md, xtask/src/main.rs, xtask/src/tasks/verify_size.rs
Fixing the underlying issue from #914
This PR does a few things:
1. The `xtask-path` logic has been fixed to always drop the file under `target/xtask-path`, regardless of whether a `--custom-root` is being used or not.
2. A new `--run-on-save` parameter has been added to `xtask`, which can be used to skip certain expensive checks when running `xtask` in response to a file save event. It is not currently being used by the open-source `xtask`, but plays an important role in the internal repo's `xtask fmt` implementation.
3. Updates the Guide to make it more clear why one may or may not want to opt into this functionality.
**These changes are not particularly interesting in isolation, but make more sense when reviewed alongside the changes being made in the internal repo.**
The fact we have …
=> xtask: fix interplay between fmt-on-save and xsync

Cargo.lock, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, vm/aarch64/aarch64emu/src/opcodes.rs, vmm_core/virt_support_aarch64emu/Cargo.toml, vmm_core/virt_support_aarch64emu/src/emulate.rs
Add a fast path for MNF writes using the ldset instruction.
#863
=> [aarch64emu] enable ldset fast path for MNF (#863)

Cargo.lock, clippy.toml, support/pal/pal_uring/src/threadpool.rs, support/pal/pal_uring/src/uring.rs, vm/chipset_device_fuzz/Cargo.toml, vm/chipset_device_fuzz/src/lib.rs, vm/devices/chipset/src/battery/mod.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_server/src/lib.rs, vmm_core/src/synic.rs
Std's is stable now, no reason to use the one from futures anymore.
=> Use std's noop waker instead of futures'

petri/src/vm/openvmm/runtime.rs, support/mesh/mesh_channel_core/src/oneshot.rs, vm/devices/hyperv_ic/src/shutdown.rs, vm/devices/hyperv_ic_resources/src/shutdown.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
The shutdown IC is handled specially, so ensure it behaves as expected across OpenHCL servicing.
=> vmm_tests: add test for using the shutdown IC across servicing

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client/src/saved_state.rs, vm/devices/vmbus/vmbus_core/src/protocol.rs, vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
The vmbus client requested all feature flags, which includes confidential channels, which it doesn't actually support. This was harmless, as the host cannot support confidential channels, but it would cause the host to log a warning that unsupported feature flags were requested.
=> vmbus_client: don't request confidential channel support.

openhcl/openhcl_boot/src/cmdline.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_uefi.rs
After updating CI gates to use Rust 1.85 we started to see test errors which looks like OOM errors.
Unfortunately, weren't reproducible on DevBox testing (both WSL2 and Windows).
This change will return some reserved memory back to Linux pool in attempt to see if it can help.
The change can stay permanent because 512 pages is enough to pass the tests.
=> Reduce GPA pool from 1024 to 512 pages for VMM tests

openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
This is a partial cherry-pick of https://github.com/microsoft/openvmm/commit/6e390e91bc33f490f24067c3377544b2feef0df0
=> TDX: Fill in get_vsm_capabilities and properly mark DR6 as shared

.github/workflows/openvmm-pr.yaml, flowey/flowey_lib_common/src/git_merge_commit.rs
Right now the binary size comparison gets the merge base of a PR branch and main, but what we really want is the merge base of the result of merging the PR branch into main. This change reflects that.
=> [flowey]: try getting better merge base

xtask/src/tasks/verify_size.rs
Now that it's doing proper baselining we can lower the threshold. Cut it in half for now, from 100kb to 50kb.
=> Lower the binary size gate's threshold

flowey/flowey_lib_common/src/install_rust.rs
Turns out `rustup` doesn't guarantee CLI output stability (see https://github.com/rust-lang/rustup/issues/450).
To get folks and CI unblocked, update the current parsing logic to work with both the old and new output format.
=> flowey: fix rust toolchain detection on rustup 1.28.0+

flowey/flowey_core/src/pipeline.rs, flowey/flowey_lib_common/src/run_cargo_build.rs, flowey/flowey_lib_common/src/run_cargo_doc.rs
This PR updates the cargo logic in `run_cargo_build.rs` and `run_cargo_doc.rs` to work correctly when a custom CARGO_TARGET_DIR is set.
The build logic is also updated to work correctly even if the target dir is on a different mount from flowey's working folder, by adding a `fs_err::copy`-based fallback path to `fs_err::rename` operations.
Lastly, this PR adds a few helper methods to `PipelineJob`, which are useful when implementing platform-specific policy via APIs like `inject_all_jobs_with`.
=> flowey: update cargo logic to support custom CARGO_TARGET_DIR

flowey/flowey_lib_common/src/install_rust.rs
Cherry pick of #944.
I'm not sure if `rustup` supports version pinning in the same way as Rust does (i.e: via a `rust-toolchain.toml`), but we may want to look into what options we have here, to avoid these sorts of breaks on our release branches.
* * *
Turns out `rustup` doesn't guarantee CLI output stability (see https://github.com/rust-lang/rustup/issues/450).
To get folks and CI unblocked, update the current parsing logic to work with both the old and new output format.
=> release/2411: flowey: fix rust toolchain detection on rustup 1.28.0+ (#944)

flowey/flowey_core/src/pipeline.rs, flowey/flowey_lib_common/src/run_cargo_build.rs, flowey/flowey_lib_common/src/run_cargo_doc.rs
Cherry pick of #949
* * *
This PR updates the cargo logic in `run_cargo_build.rs` and `run_cargo_doc.rs` to work correctly when a custom CARGO_TARGET_DIR is set.
The build logic is also updated to work correctly even if the target dir is on a different mount from flowey's working folder, by adding a `fs_err::copy`-based fallback path to `fs_err::rename` operations.
Lastly, this PR adds a few helper methods to `PipelineJob`, which are useful when implementing platform-specific policy via APIs like `inject_all_jobs_with`.
=> release/2411: flowey: update cargo logic to support custom CARGO_TARGET_DIR (#949)

openhcl/underhill_core/src/worker.rs, vm/devices/vmbus/vmbus_server/src/lib.rs
The synic may be saved or reset while the vmbus server is paused. Don't send any messages during this time, since this can result in torn or corrupt state.
Skip this for vmbus running inside OpenHCL for now, since this relies on the newer saved state field for messages queued by vmbus, and release/2411 won't process that field.
=> vmbus_server: don't send synic messages while paused

Cargo.lock, openvmm/hvlite_core/src/worker/dispatch.rs, vm/devices/vmbus/vmbus_client/src/hvsock.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_core/src/lib.rs, vm/devices/vmbus/vmbus_proxy/Cargo.toml, vm/devices/vmbus/vmbus_proxy/src/lib.rs, vm/devices/vmbus/vmbus_proxy/src/proxyioctl.rs, vm/devices/vmbus/vmbus_proxy/src/vmbusioctl.rs, vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/lib.rs, vm/devices/vmbus/vmbus_server/src/proxyintegration.rs
This change updates vmbusproxy to correctly handle hvsocket channel offers. It also allows it to pass connection requests from the guest (the `TlConnectRequest` message) to the proxy driver, and for the driver to request a response (`TlConnectRequestResult`) be sent to the guest.
This functionality is not enabled for openvmm, as it is mutually exclusive with openvmm's normal hvsocket handling, and requires vmbusproxy.sys driver updates.
=> vmbus_server: support hvsocket with vmbusproxy.

vm/devices/net/netvsp/src/lib.rs, vm/devices/net/netvsp/src/test.rs
If the guest specifies a RSS receive indirection table that does not specify queue 0, need to still give it the reserved ranges of the receive buffer as only worker[0]/queue[0] uses them. If the indirection table results in no active queues, fallback to not using it.
=> netvsp: primary queue should always have reserved receive buffers

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_relay/src/lib.rs
There is no reason to keep these as separate operations. Combining them will allow a future change to provide a consistent interface between `connect` and `restore`.
=> vmbus_client: combine connect and request offers

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client/src/saved_state.rs, vm/devices/vmbus/vmbus_relay/src/lib.rs, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
Simplify GPADL handling:
* Remove the separate GPADL map and just have the GPADLs be owned by the channels.
* Report GPADL torndown responses via individual oneshot mesh channels instead of a single mesh channel for the whole device.
=> vmbus_client: clean up gpadl handling

vm/devices/net/netvsp/src/lib.rs, vm/devices/net/netvsp/src/test.rs
If a netvsp worker task is stopped waiting for external processing, avoid restarting it due to other signals. This is mainly a problem for the primary worker task which will stop itself to wait for work to be done. If some other trigger starts it before that work is complete, then it is in an invalid state. Move all worker start logic to a single location in the coordinator.
For the primary worker make sure there are no outstanding messages to process before starting it, as most messages will stop it again anyway, but more importantly one of the outstanding messages may be from the primary worker, requesting work to be done before starting it up again.
=> netvsp: Move all worker start logic to coordinator to avoid races

vm/devices/vmbus/vmbus_channel/src/bus.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_relay/src/lib.rs, vm/devices/vmbus/vmbus_relay_intercept_device/src/lib.rs
The vmbus client and vmbus relay channel states need to stay in sync, since we cannot save/restore in intermediate states (such as in the middle of opening a channel).
Close currently breaks this--the relay can send a close just before pausing saving, and there is no guarantee (that I can see) that the client will process it before it is saved.
Fix this by making `Close` an RPC, so that the relay can wait for the message to be sent to the host, and the client state updated, before it pauses and saves its own state.
=> vmbus_client: make Close an RPC

support/pal/pal_async/src/timer.rs, vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client/src/saved_state.rs, vm/devices/vmbus/vmbus_relay/src/lib.rs
To avoid deadlocks with the host, queue and retry sending messages
asynchronously rather than blocking the thread.
Also, support restoring pending messages for saved state compatibility
with changes in main, especially #962.
This is a partial backport of #884.
=> vmbus_client: handle host backpressure properly

Cargo.lock, support/mesh/mesh_channel_core/src/oneshot.rs, support/mesh/mesh_node/Cargo.toml, support/mesh/mesh_node/src/local_node.rs, support/mesh/mesh_node/src/local_node/protocol.rs
Send the message and the close notification in a single event packet. This improves oneshot performance.
=> mesh_node: send and close channels in one operation

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
This allows us to remove the annoying 'delay-flush' struct I added as a workaround previously. This is needed so we can perform similar types of activities elsewhere without having to use the same delayed workaround, like in https://github.com/microsoft/openvmm/pull/921. 
This did require the removal of `vtls_tlb_waiting` in order to make all the partial borrowing possible, however this field was only being used as a small performance optimization to avoid a relaxed atomic load. Since this load is relaxed, I think this is ok?
=> virt_mshv_vtl: Refactor TLB flush and lock code to allow for partial borrows

support/mesh/mesh_channel_core/src/lib.rs, support/mesh/mesh_channel_core/src/mpsc.rs, support/mesh/mesh_channel_core/src/oneshot.rs, support/mesh/mesh_channel_core/src/sync_unsafe_cell.rs
Shrink the size of `Receiver` by carefully moving the state into the `Arc` allocation.
=> mesh_channel_core: move receiver state into Arc

vm/devices/storage/storvsp/Cargo.toml, vm/devices/storage/storvsp/benches/ioperf.rs
1. Fix the missing docs lint in the ioperf bench
2. Add a missing feature dependency to storvsp
=> Fix a missed lint and feature dependency

openhcl/minimal_rt/src/arch/aarch64/intrinsics.rs
This is needed for internal toolchain compatibility. Cherrypick of fa11f4da57a548e790f64eb97c6c45736bcf901d
=> minimal_rt: Add ARM64 stack guard intrinsics (#660)

vm/hv1/hv1_emulator/src/cpuid.rs
There is a known race condition in TDX's TLB flushing infrastructure that needs to be addressed. We had hoped that it was rare enough nobody would hit it in practice, but it seems that someone now has. Disable it for now until things are working better.
Part of https://github.com/microsoft/openvmm/issues/699
=> TDX: Disable TLB flush hypercalls for the time being

vm/loader/src/elf.rs
Sections with zero file length still need to be loaded. Our existing
binaries don't have these sections, since BSS and data sections tend to
get combined into a single load directive, but fix this for
compatibility with other binary layouts.
=> loader: don't skip program headers with zero file length

vmm_core/virt/src/io.rs
Allow it to have per-VP state that's bound to the VP thread.
=> virt: CpuIo doesn't need to be Send+Sync

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client/src/saved_state.rs, vm/devices/vmbus/vmbus_core/src/protocol.rs, vm/devices/vmbus/vmbus_server/src/channels.rs, vm/devices/vmbus/vmbus_server/src/channels/saved_state.rs, vmm_tests/vmm_tests/tests/tests/x86_64/openhcl_servicing.rs
During VTL2 servicing, the host resets the VTL2 synic state, causing any pending vmbus messages to be lost. To mitigate this, `vmbus_client` masks the synic sint and drains and processes any pending messages before saving its state. This prevents the vmbus server in the Hyper-V host from posting new messages, so that they are not lost; Hyper-V retries them later when the sint is unmasked.
Unfortunately, this mask/unmask behavior is not supported by OpenVMM with `virt_whp`, because `virt_whp`'s synic emulation relies on `HvPostMessageDirect`, which does not allow posting a message to the message slot when the sint is masked. This means that it is impossible for `virt_whp` to support this process for draining the message queue, and so any pending messages are lost across VTL2 servicing. …
=> vmbus: add pause/resume messages, use them in vmbus_client save/restore

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Try to use VpIndex everywhere instead of usize and u32. The main place where we aren't today is in the hypercall traits, which are defined elsewhere.
This also removes a TODO about cpu_index potentially being different than vp_index, and the cpu_index field entirely, under the assumption that if it hasn't been an issue up till now it's not going to be. If we do want to keep this field we should probably have some docs and a more careful audit of when we should be using vp_index vs cpu_index.
=> virt_mshv_vtl: Cleanup some vpindexes

rustfmt.toml
rustfmt.toml's 'edition' key only controls parsing behavior. We should leave this to the default (read from Cargo.toml) so that rustfmt's parsing behavior always matches what our code is targeting. Formatting behavior is controlled by this separate key, 'style_edition', which we can change separately from the actual code edition. This will allow us to take 2024 edition formatting changes separately from code behavior changes, should we so choose.
Part of #288
=> Fix incorrect key name in rustfmt.toml

Cargo.lock, Cargo.toml, flowey/flowey_lib_common/src/run_cargo_nextest_run.rs, xsync/xsync/src/tasks/cargo_toml.rs, xsync/xsync/src/tasks/rustfmt_toml.rs, xtask/src/tasks/fmt/house_rules/crate_name_nodash.rs, xtask/src/tasks/fmt/house_rules/package_info.rs, xtask/src/tasks/fmt/unused_deps.rs, xtask/src/tasks/fmt/workspace.rs, xtask/src/tasks/fuzz/init_from_template.rs
This brings Rust 2024 compatibility. Part of #288
=> Update our cargo-toml and toml-edit dependencies

openhcl/bootloader_fdt_parser/src/lib.rs, openhcl/openhcl_boot/src/dt.rs, openhcl/underhill_core/src/worker.rs, openhcl/underhill_mem/src/registrar.rs, openvmm/hvlite_core/src/worker/dispatch.rs, openvmm/hvlite_core/src/worker/vm_loaders/igvm.rs, openvmm/membacking/src/memory_manager/mod.rs, vm/devices/firmware/firmware_pcat/src/default_cmos_values.rs, vm/devices/net/net_backend/src/tests.rs, vm/loader/src/common.rs, vm/vmcore/vm_topology/src/memory.rs, vmm_core/src/acpi_builder.rs, vmm_core/virt/src/generic.rs, vmm_core/virt/src/x86/mod.rs, vmm_core/virt_whp/src/lib.rs
The physical address width is not really a singular thing--there are many different interesting address widths:
* The width the virtual processor can access via CPU instructions.
* The width virtual devices/mapped devices/the IOMMU can access via DMA.
* The width the hypervisor supports for mapping memory (usually this is limited to the min of the previous two)
* The width reported to the guest
* By cpuid on x86.
* By a sysreg on arm64 (this will be rounded up to the next multiple of 4).
* The offset of the VTL0 alias map.
* The size of the VA range we allocate for guest memory mappings.
Some of these have ended up getting conflated in our designs since these are often the same/related to each other in useful ways. But in practice, there are subtle differences. And in reality, we don't …
=> vm_topology: remove physical address width from MemoryLayout

vm/devices/vmbus/vmbus_client/src/lib.rs, vm/devices/vmbus/vmbus_client/src/saved_state.rs
When the server revokes a channel:
* Don't allow the channel ID to be reused until the user of the channel releases it. This ensures the server cannot overwhelm the client and its users with channel offers and that we won't see any duplicate offers in either the client or the downstream relay/server.
* Ensure channel requests can continue to be issued without unpredictable behavior.
* Save a channel ID release message for the channel if the client is saved before the user releases the revoked channel.
Add some tests to cover these cases.
=> vmbus_client: fix state machine around revoke

vm/devices/net/netvsp/src/lib.rs, vm/devices/net/netvsp/src/test.rs
#958
If a netvsp worker task is stopped waiting for external processing, avoid restarting it due to other signals. This is mainly a problem for the primary worker task which will stop itself to wait for work to be done. If some other trigger starts it before that work is complete, then it is in an invalid state. Move all worker start logic to a single location in the coordinator.
For the primary worker make sure there are no outstanding messages to process before starting it, as most messages will stop it again anyway, but more importantly one of the outstanding messages may be from the primary worker, requesting work to be done before starting it up again.
#960
If the guest specifies a RSS receive indirection table that does not specify queue 0, need to still give it the reserved ranges …
=> netvsp: take recent fixes to release/2411

.git-blame-ignore-revs
Since this commit was large but didn't actually change anything meaningful, we can exclude it from git blames to provide better history.
=> Add a .git-blame-ignore-revs for the 2024 formatting commit

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
1. Advertise TDX Guest VSM support through CPUID when the necessary env var allows it. No additional checks are required. Fixes #557.
2. Remove the todo comment from enable_vp_vtl. No additional work is required. Part of #698.
=> TDX: Cleanup two small TDX guest VSM comments

openhcl/underhill_core/src/worker.rs, openhcl/virt_mshv_vtl/src/devmsr.rs, openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/tlb_lock.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Not an ideal solution, but it makes things a lot better IMO.
=> virt_mshv_vtl: Make much of crate non-pub by carefully allowing private-in-pub warnings

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/apic.rs, openhcl/virt_mshv_vtl/src/processor/hardware_cvm/mod.rs
The important question here is not whether VTL 1 is enabled or not, but whether during enablement deny_lower_vtl_startup was set. This is also an HCL bug, but we should be correct.
=> cvm: Check for deny_lower_vtl_startup when handling INIT and SIPI

openhcl/underhill_core/src/loader/mod.rs, openhcl/underhill_core/src/worker.rs, openvmm/hvlite_core/src/worker/dispatch.rs, openvmm/hvlite_core/src/worker/vm_loaders/igvm.rs, openvmm/hvlite_core/src/worker/vm_loaders/uefi.rs, vm/loader/src/common.rs, vm/vmcore/vm_topology/src/memory.rs
PCAT and UEFI firmware require 2 MMIO gaps, but this isn't a fundamental requirement of a VM topology. Remove this restriction.
=> vm_topology: don't require 2 MMIO gaps

vm/x86/tdcall/src/lib.rs
Added error types for AcceptPagesError reflecting the error types mentioned in the spec and updated the tdcall_accept_pages error handling accordingly.
Added a check to validate the return code in rax for tdcall_map_gpa.
Addresses Issue #545
=> tdcall: Adding check for return status and updating error types.

vm/devices/net/netvsp/src/lib.rs, vm/devices/net/netvsp/src/test.rs
The number of receive buffers may not always divide equally among the active queues. If there are extras, assign them to the last queue. This way all of the receive buffers are always accessible from one of the queues.
=> netvsp: assign any extra receive buffers to the last active queue

openhcl/hcl/src/ioctl.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, vm/hv1/hv1_emulator/src/message_queues.rs, vm/hv1/hv1_hypercall/src/imp.rs, vm/hv1/hvdef/src/lib.rs
Align `HvMessage` to 16 bytes since it sometimes contains messages from the hypervisor that have 16-byte alignment, and it is always 16-byte aligned in mapped memory interfaces.
Add new `as_message` method for casting the payload to a message type without having to use an explicit zerocopy dance. This method validates that the type being cast to is supposed to be a message type and that it has the proper size and alignment.
Use `as_message` in virt_mshv_vtl.
=> hvdef: clean up `HvMessage` type and handling

vm/x86/x86emu/fuzz/fuzz_x86emu.rs, vm/x86/x86emu/src/emulator.rs, vmm_core/virt_support_x86emu/src/emulate.rs
This has happened twice now, so let's give a more clear error message. Open to bikeshedding.
=> Give a better error message when we hit the instruction emulator's fail-fast condition

vm/whp/src/abi/arm64.rs, vm/whp/src/lib.rs, vmm_core/virt_whp/src/vp.rs
Use the new `MessagePayload` trait to cast with confidence.
Also, fix the alignment problem with `WHV_RUN_VP_EXIT_CONTEXT`; messages
must be 16-byte aligned.
=> virt_whp: simplify hypervisor message access

openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
Cherry pick of #940 
optimization for Vmxexit path where hardware breakpoint checks are only made if GDB feature is enabled, this avoids unnecessary trip to kernel space.
=> Add conditional check for hardware breakpoint in VMX exit handling

openhcl/hcl/src/ioctl/snp.rs
This probably doesn't matter thanks to the UnsafeCells, but better safe than sorry.
=> SNP: Fix a ref/mut disagreement

xsync/Cargo.lock
This is needed because it transitively picked up new deps through ci_logger. We probably should get rid of that dependency link.
=> Regen xsync's lockfile

openhcl/virt_mshv_vtl/src/lib.rs, openhcl/virt_mshv_vtl/src/processor/mod.rs, openhcl/virt_mshv_vtl/src/processor/mshv/arm64.rs, openhcl/virt_mshv_vtl/src/processor/mshv/x64.rs, openhcl/virt_mshv_vtl/src/processor/snp/mod.rs, openhcl/virt_mshv_vtl/src/processor/tdx/mod.rs
As requested. This can't be quite as clean as hcl's BackingPrivate due to leaking out the associated StateAccess type through our impl of virt::Processor requiring BackingPrivate to be fully pub. I played around with the types for a while but couldn't get anything that was better than this. So just leave the expects in.
=> virt_mshv_vtl: Bring back BackingPrivate

Cargo.lock, Cargo.toml
Instead of using the github branch, use the published releases on crates.io for these two crates. There seems to be a bug with xsync when git dependencies are being used, which this works around.
=> deps: use crates.io release of mshv-bindings, mshv-ioctl
